### ISSUE TITLE
Chromatic TurboSnap builds don't work with Rsbuild

### ISSUE THREAD

**Issue by phildenhoff** [chromaui/chromatic-cli#1017]
_[I've created a codesandbox to demonstrate this issue](https://codesandbox.io/p/devbox/rsbuild-storybook-iframe-html-compile-error-forked-l5nd2t), using a throwaway Chromatic project with TurboSnap enabled._

When Storybook is built using [Rsbuild](https://rsbuild.dev/)/Rspack (via the [storybook-rsbuild](https://github.com/rspack-contrib/storybook-rsbuild) package), Chromatic fails to detect any CSF globs in the preview-stats.json file, and so TurboSnap fails. Full builds work fine.

E.g. running `npx chromatic --only-changed` would give an error like this

```
  Error: ✖ Failed to publish your built Storybook
  Could not retrieve dependent story files.
  Did not find any CSF globs in preview-stats.json
```

I'm not super familiar with Webpack or the stats files in general, but this seems to stem from the "reason" files having module names from [this list](https://github.com/chromaui/chromatic-cli/blob/c91d3010049ed7803cc369d61c6c0161530f4f0c/node-src/lib/getDependentStoryFiles.ts#L100-L111) when doing a Webpack or Vite build. Rsbuild, instead, has very different names.

For example, a Vite module name would look like this:

```json
{
  "moduleName": "/virtual:/@storybook/builder-vite/vite-app.js"
}
```

and an Rsbuild one like this:

```json
{
  "moduleName": "/Users/phil/work/ts-wholesale/ui/src|lazy|/^\\.\\/.*$/|include: /(?!.*node_modules)(?:\\/src(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)\\/|\\/|$)(?!\\.)(?=.)[^/]*?\\.stories\\.(js|jsx|mjs|ts|tsx))$/|chunkName: [request]|groupOptions: {}|strict namespace object"
}
```

Because the second module name (in modules[0].reasons[0].moduleName) is not one of the "approved" items, the CSF story module is skipped.

I _think_ that's it. Hopefully you can advise how we can use Rsbuild & Chromatic together!

**Comment by ghengeveld** [comment]
:rocket: Issue was released in [`v11.10.0`](https://github.com/chromaui/chromatic-cli/releases/tag/v11.10.0) :rocket:

**Comment by phildenhoff** [comment]
Thank you @ghengeveld and @joshwooding!

**Comment by binarykitchen** [comment]
Afraid it still happens with the most recent upgrades ...

**Comment by cgbl-90** [comment]
@binarykitchen Can you share a repro or reach out to support@chromatic.com and share the logs of your latest builds?

**Comment by binarykitchen** [comment]
Weird. I deleted node_modules folder along with the lock file and now the warning has disappeared.

**Comment by binarykitchen** [comment]
And it happened again, and then I realise it is because of the build script name which defaults to `build-storybook` while I had it at `build:storybook`.  I do not like the dash notation of npm scripts. How can I globally rename this?

**Comment by codykaup** [comment]
@binarykitchen I'm not sure what you mean by global but we have a `--build-script-name` flag that you could set to `build:storybook`.
