### ISSUE TITLE
test-runner.ts not executing

### ISSUE THREAD

**Issue by ludicast** [chromaui/chromatic-cli#1024]
**Bug report**

When I add waits/errors to the `.storybook/test-runner.ts` file, they appropriately affect the test-storybook command.

But these do not affect the execution of tests during  `npx chromatic`. As an example I set the test runner file to be

    import type { TestRunnerConfig } from '@storybook/test-runner';
    throw new Error("dkjdkdjkdjdjd")

and test-storybook fails while the tests executed by chromatic happily chug along.

also can confirm that adding an error/wait to the `play` function does properly affect the tests when chromatic runs the tests during execution.

**Comment by ludicast** [comment]
`. The test runner doesn't work on Chromatic since we disabled JS to snapshot on the Chromatic side. `

This might partially be the case @irashid1, but I do experience that when the `play` function is set to throw an error it breaks the story in chromatic

    const meta = {
      title: 'Ui/Buttons',
      component: Button,
      play: () => { throw new Error("error")},
    } satisfies Meta<typeof Alert>;

so somehow some javascript is still sometimes executing it seems, unless I'm misunderstanding you.

**Comment by irashid1** [comment]
Hi Nate,

@ludicast We have taken this issue to our engineering team, and we are conducting an investigation. Thank you for bringing this to our attention, and I'll follow up with any updates we may have. We appreciate your patience during our investigation 🙌🏼 

Best, 

Imtiaz @ Chromatic

**Comment by irashid1** [comment]
Hi Nate, 

Here's a summary of what I learned from the engineering team so far. 

`The test runner doesn't work on Chromatic since we disabled JS to snapshot on the Chromatic side. It works in Storybook because JS is not disabled.`

This is partially the case. The test runner is replaced for anything pre-storybook. The play function, which is specified in the story itself, is still actually being run. In other words, not all JS is being disabled. 

Additionally, we also wanted to clarify that we don't really disable JS in chromatic, even for e2e. but for e2e, we capture the DOM snapshot after all the JS runs on the page, and then that JS does not run again when it is rendered in chromatic because we're just rendering the static DOM. but this is only for e2e. 

I hope that clarifies. If there is anything else you'd like me to relay to the engineering team, please let me know. 

Best, 

Imtiaz @ Chromatic

**Comment by ludicast** [comment]
Gotcha @irashid1. It's a little weird without a flowchart because it's essentially "all js".  So it catches me offguard that js both js and isn't running.

So here's a case that I'm stumbling on. Which I assume hits folks using storybook/chromatic for elaborate stories (namely [pages](https://storybook.js.org/blog/building-pages-in-storybook/)).

The stories might be fast, but occasionally takes an extra few seconds to load for unavoidable reasons (say it's loading stripe or wistia's ui elements and manipulating them).

Locally, if the play function takes a while to run 

    const meta = {
      title: 'Ui/Buttons', component: Button,

      play: () => async ({ canvasElement }) => {
         // wait for something with canvasElement
         // or to mock:
        // await new Promise((resolve) => setTimeout(resolve, 20000))
      }
    }

locally we can treat it with 

`yarn test-storybook --testTimeout $SOME_TIMEOUT ./blaf.stories.ts`

and this `play` always passes. but in chromatic this delay doesn't get passed down. But discussing with you, and thinking about it,  it seems it's specifically that storybook sometimes times out the play and it might not have to do with chromatic (even though that's where I'm seeing it when the screenshots occasionally fail.).

Maybe there's a some do in getting the storybook to accept a potentially longer play function (since it runs before the snapshot is taken).

**Comment by ludicast** [comment]
bet it's connected to this (prematurely) closed issue I just saw

https://github.com/storybookjs/test-runner/issues/300

**Comment by ludicast** [comment]
I'm closing this issue because it's not particular to chromatic, but rather in how storybook runs (or doesn't run stuff).  So if I re-open I'll do it in a storybook repo rather than here. 

Thanks for your research @irashid1 , was able to fix my own issue at least with the info you imparted.

**Comment by irashid1** [comment]
It was my pleasure, @ludicast; please let us know if anything else comes up. We would be happy to help!

Best, 

Imtiaz @ Chromatic
