### ISSUE TITLE
onlyStoryNames, onlyStoryFiles ignored on subsequent builds

### ISSUE THREAD

**Issue by james-gough-op** [chromaui/chromatic-cli#1026]
**Bug report**

I'm evaluating Chromatic against some other testing tools.

I needed to evaluate 2 key things:
- how we could narrow down the list of stories we are snapshotting to just a core set.
- make a single deliberate change to verify Chromatic would notice the one change and report it and nothing else.

I started with a new project and tried to use the `onlyStoryFiles` config setting. This didn't work. Every story was getting snapshotted. Tried using the flag equivalent on the CLI. Same result.

Created an entirely new project.

Used the `--only-story-names` flag to filter down the snapshots:

```
npx chromatic --project-token=[xxxx_0000000000] --only-story-names "Foundations/**" --only-story-names "Components/**"
```

The first build runs perfectly. Only stories that fit the name I've defined are added as snapshots 👍 

I went ahead and accepted those as my initial baseline.

I then made a single change to a single story in that filtered set.

All subsequent builds are ignoring the config option and snapshotting everything in the project. 👎 

I've tried using just the config file, command line params, same result.

Here's my list of builds. 

![Screenshot 2024-08-19 at 15 28 30](https://github.com/user-attachments/assets/95f06a0a-90dd-4770-bec5-f431c99969ae)

Note that every build after the first has an additional 321 changes despite me making a single change to one story. In the most recent build I even reverted that change.

Is this a bug or am I misreading what the `--only-story-names` and `--only-story-files` flags are supposed to do?

Edit: 

Here's an example repo: https://github.com/slashwhatever/chromatic-test
And it's corresponding project: https://www.chromatic.com/builds?appId=66c88e393e9ae20b6f01f08f

config: 

```
{
  "$schema": "https://www.chromatic.com/config-file.schema.json",
  "projectId": "Project:66c88e393e9ae20b6f01f08f",
  "autoAcceptChanges": "main",
  "exitOnceUploaded": true,
  "skip": "dependabot/**",
  "onlyStoryFiles": ["./src/components/button/**"]
}
```

This still snapshots stories outside the `/button/` folder

**Comment by codykaup** [comment]
Thanks for letting us know!

For any external viewers, we were able to verify this was a bug but it lives outside of the CLI. It's actively being worked on!

**Comment by james-gough-op** [comment]
@codykaup Thanks for the update. Any chance you can link me to the change so I can subscribe to progress?

**Comment by cgbl-90** [comment]
Hey @james-gough-op we don't have a link we could share, but we will let you know when it's resolved here.
