### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by ghengeveld** [chromaui/chromatic-cli#104]
Oftentimes `storybook-chromatic` fails with cryptic error messages (or Node.js warnings) which might not be clear to inexperienced users. This is especially an issue since some users have never run `storybook-build` before and thus blame us when the Chromatic CLI fails (when running `storybook-build` in the background).

Lets come up with a strategy for mitigating this issue.

**Comment by zol** [comment]
This is coming up often in support, again today: https://app.intercom.com/a/apps/zj7sn9j1/inbox/inbox/unassigned/conversations/26556622197

Improving this is a big priority after 2.0

**Comment by tmeasday** [comment]
I think we tried to address this
