### ISSUE TITLE
chromaui/action appears broken, cannot pin version

### ISSUE THREAD

**Issue by nathanielobrown** [chromaui/chromatic-cli#1087]
I'm getting an error in my CI like `Error: File not found: '/home/machine_name/actions-runner/_work/_actions/chromaui/action/latest/action/register.js'`. I think it just started happening and I see you deployed a version about 30 minutes ago.

When I go to pin the version I get an error like `chromaui/action@11.11.0`, unable to find version `11.11.0`. Looking at https://github.com/chromaui/action/tree/latest/, seems like there is only a single version. Is there no way to ping to older versions?

**Comment by felixmokross** [comment]
Same for me. Yesterday it still worked; now without any change to my workflow it breaks with this exact error message when I run the action.

**Comment by nathanielobrown** [comment]
It's working for me now, but appears to be using the older version again, which makes sense as looking at https://github.com/chromaui/action/tree/latest/ the version is now `v11.11.0`
![CleanShot 2024-10-08 at 15 28 46](https://github.com/user-attachments/assets/65464980-9d55-4ccc-b8cc-b094edb50214)

Thank you to whoever fixed this! Ability to select version would be excellent for any future issues

**Comment by jmhobbs** [comment]
Yes, we had a bad push and reverted to the v11.11.0 code in the action, sorry about that.  We will be releasing an update with the v11.12.0 code tomorrow to bring it up to date.

I'll look into the format for pinning versions based on tag, I've not used that before.

**Comment by codykaup** [comment]
>When I go to pin the version I get an error like chromaui/action@11.11.0, unable to find version 11.11.0. Looking at https://github.com/chromaui/action/tree/latest/, seems like there is only a single version. Is there no way to ping to older versions?

@nathanielobrown you can pin versions based on the tag! Looks like you might've missed the `v` in the tag version so `chromaui/action@v11.11.0` should work for you.

**Comment by jmhobbs** [comment]
The [action](https://github.com/chromaui/action) is now on v11.12.1 and up for the last 5 hours or so.

The CLI releases 11.12.2 - 11.12.4 are from working on the deploy/release system, so there are no code/behavior changes from 11.12.1 in those.

Sorry for the delay on all of this, and thanks for reporting it.
