### ISSUE TITLE
Uploading the Playwright Artifact in a GitHub Action throws an error

### ISSUE THREAD

**Issue by ynotdraw** [chromaui/chromatic-cli#1099]
## Overview

I have a repository at https://github.com/ynotdraw/chromatic-testing to experiment with Chromatic. I'm following the guide at https://www.chromatic.com/docs/playwright/configure/ to get things set up in a GitHub Action, but I'm hitting an issue that I can't find any documentation for.

## Bug Report

When copy/pasting the suggested documentation into my [GitHub Action workflow](https://github.com/ynotdraw/chromatic-testing/blob/main/.github/workflows/playwright.yml), I receive an error when attempting to upload the artifacts in the `upload-artifact` step as you can see in [the output](https://github.com/ynotdraw/chromatic-testing/actions/runs/11394766085/job/31705694996).

```bash
The path for one of the files in artifact is not valid: /chromatic-archives/archive/@id/__x00__/virtual:/@storybook/builder-vite/setup-addons.js. Contains the following character:  Colon :
          
Invalid characters include:  Double quote ", Colon :, Less than <, Greater than >, Vertical bar |, Asterisk *, Question mark ?, Carriage return \r, Line feed \n
          
The following characters are not allowed in files that are uploaded due to limitations with certain file systems such as NTFS. To maintain file system agnostic behavior, these characters are intentionally not allowed to prevent potential problems with downloads on different file systems.
```

It appears not happy with the `virtual:` in the directory name as you can see in the last sentence of the error (with slightly more info at https://github.com/actions/upload-artifact/issues/35#issuecomment-573331997). I can see this directory structure also exists locally. I couldn't find a way to modify Chromatic/storybook to adjust this directory location, as it seems generated by Chromatic itself?

<img width="544" alt="Screenshot 2024-10-17 at 7 52 45 PM" src="https://github.com/user-attachments/assets/7d4ceaf8-2c87-4938-bbc0-3b59804ec1ca">

## Reproduction Steps

1. Pull down or fork the repository at https://github.com/ynotdraw/chromatic-testing
2. I'm currently using `Node.js v19.1.0` and `pnpm@9.4.0`
3. Run `pnpm i`
4. Run `pnpm test`
5. Configure the GitHub Action to have a proper `CHROMATIC_PROJECT_TOKEN` following [the docs](https://www.chromatic.com/docs/github-actions/#project-token-secret)
6. Push the code to a GitHub repository

**Comment by jmhobbs** [comment]
Hi @ynotdraw!  This is happening because you are running Playwright against a Storybook running in dev mode, which has HMR, etc and includes virtual paths.  You can see this by opening the network tab on your running Storybook and looking at the `vite-app.js` file, you'll see it's coming from `http://localhost:6006/virtual:/@storybook/builder-vite/vite-app.js`

Your Storybook needs to be statically built to get rid of these virtual paths which [actions/upload-artifact](https://github.com/actions/upload-artifact) does not support.  You could do this by using [another webserver](https://www.npmjs.com/package/http-server) for serving the built Storybook:

```
// playwright.config.ts
@@ -73,7 +73,7 @@ export default defineConfig({

   /* Run your local dev server before starting the tests */
   webServer: {
-    command: 'pnpm start',
+    command: 'pnpm http-server storybook-static --port 6006',
     url: 'http://localhost:6006/',
     reuseExistingServer: !process.env.CI,
   },
```

```
$ pnpm build-storybook
$ pnpm test
```

**Comment by ynotdraw** [comment]
That worked! Thanks again, @jmhobbs 🎉
