### ISSUE TITLE
Cannot call static methods on `Intl` mocks

### ISSUE THREAD

**Issue by tmeasday** [chromaui/chromatic-cli#115]
This line of code (which works in a browser) breaks:

```js
Intl.DateTimeFormat.supportedLocalesOf(['ban'])
```

Related to https://github.com/chromaui/chromatic-cli/pull/53 and https://github.com/chromaui/chromatic-cli/issues/48

**Comment by ndelangen** [comment]
strange:
https://github.com/chromaui/chromatic-cli/blob/19751d87d950a2aecefb522e57c9a13c8c34fe54/bin/lib/jsdom-shims.js#L261-L264

code is there, I'm not sure why it wouldn't work.

**Comment by ndelangen** [comment]
If I just add 
```
console.log(Intl.DateTimeFormat.supportedLocalesOf(['ban']));
```

to a story is works in chromatic.

**Comment by ndelangen** [comment]
I've also tried using `react-intl` in a few various ways. I've not been able to reproduce yet..

**Comment by ndelangen** [comment]
I've been searching for where "intlConstructor" might be from, and this is what i found:

https://github.com/formatjs/intl-locales-supported/commit/f2faf42b1cbdc1ebf6c958a0069a333d861f0ade#diff-168726dbe96b3ce427e7fedce31bb0bcR23-R38

that repo is deprecated however, it's related to react-intl:
https://github.com/formatjs/react-intl

(It's in the same github org.)

**Comment by ndelangen** [comment]
https://www.staging-chromatic.com/component?appId=5e92fbc4f60aba00228b8a0a&name=Intl&buildNumber=2&mode=snapshot

seems to work fine?

**Comment by ndelangen** [comment]
Is it IE11 specific perhaps?

I am running this in IE11 and it fails:
https://5d3a9b0c6b939d00207f7729-mqrplctozt.staging-chromatic.com/?path=/story/basics-a--simple

**Comment by ndelangen** [comment]
It seems like react-intl might have some code in it that's IE11 incompatible:
<img width="403" alt="Screenshot 2020-04-12 at 13 56 11" src="https://user-images.githubusercontent.com/3070389/79068215-98ab8300-7cc5-11ea-99c8-62ca6bba720e.png">

**Comment by ndelangen** [comment]
But I don't really how that might cause: 
> `Cannot call static methods on `Intl` mocks`

**Comment by tmeasday** [comment]
@ndelangen you need it to be outside of a story so it is evaluated in JSDOM

**Comment by tmeasday** [comment]
Repro: https://app.intercom.com/a/apps/zj7sn9j1/inbox/inbox/conversation/26604482712

**Comment by ndelangen** [comment]
I'll attempt this on master

**Comment by ndelangen** [comment]
ok, can reproduce on master now

**Comment by QuadDamn** [comment]
@tmeasday @ndelangen Thank you for your work on this!  I am doing this within my story and running into the issue:

```
import { createIntl } from 'react-intl';

const intl = createIntl({
    defaultLocale: 'en',
    locale: 'en'
});

**Comment by tmeasday** [comment]
No longer relevant!
