### ISSUE TITLE
Reporting tweaks [Alpha Release]

### ISSUE THREAD

**Issue by zol** [chromaui/chromatic-cli#119]
Testing the new alpha release as part of 2.0, I found a couple of nitpicks/tweaks:

1. Regarding the following output:
<img width="746" alt="chromatic info Building your Storybook" src="https://user-images.githubusercontent.com/81672/79082184-a1598480-7cd8-11ea-8a9c-68a839eb3b5c.png">

It doesn't make sense to say "Uploading and verifying build..." after we've said "Uploaded your build, verifying"

2. We need to update the docs url to `https://docs.chromatic.com`
<img width="757" alt="chromatic info Pass --exit-zero-on-changes if you want this command to exit successfully in this case" src="https://user-images.githubusercontent.com/81672/79082384-5fc9d900-7cda-11ea-9ff1-cf249e5b8c81.png">

3. We should finally fix the fact that it says "Build 1 has 3 changes" for the first build:

<img width="734" alt="image" src="https://user-images.githubusercontent.com/132554/79223416-a0715000-7e9c-11ea-8acc-39e3916b4fcf.png">

4. At the end it says:

```
NOTE: I wrote your project token to the script via the \`--projectToken\` flag.
```

Isn't it `--project-token`? In any case it just wrote `"chromatic": "chromatic"`.

**Comment by ndelangen** [comment]
1. Uploading..
2. Verifying..

**Comment by zol** [comment]
@ndelangen please be more verbose

**Comment by tmeasday** [comment]
I added a couple of minor things too @ndelangen

**Comment by domyen** [comment]
Related: https://github.com/chromaui/chromatic/issues/3484

Can we add a spinner, progress bar, or an extra message to "Building your Storybook" info log?

**Comment by domyen** [comment]
![image](https://user-images.githubusercontent.com/263385/79774678-22300600-8301-11ea-8b14-474ce7a2b89d.png)

Re:#4 I'd expect this to add:
`"chromatic": "chromatic --project-token=<project-token>"`

**Comment by tmeasday** [comment]
@ndelangen what it the status of this?

**Comment by tmeasday** [comment]
Deployed as release 43
