### ISSUE TITLE
Allow output in JUnit format

### ISSUE THREAD

**Issue by ljowen** [chromaui/chromatic-cli#134]
Many CI systems such as Jenkins and Bamboo work very nicely with JUnit. 

Please consider an option to output visual regression test results in this format as it would make life much better for users and save us having to trawl through build logs to get the link to failed tests.

**Comment by flo-sch** [comment]
Hi @ljowen, it looks like support for this was released in [v5.0.0](https://github.com/chromaui/chromatic-cli/blob/next/CHANGELOG.md#500---2020-06-19)

There is now a `--junit-report [filepath]` CLI [option](https://www.chromatic.com/docs/cli#debug-options)

**Comment by tmeasday** [comment]
Thanks @flo-sch - you are correct!
