### ISSUE TITLE
Issue authenticating in CLI

### ISSUE THREAD

**Issue by zol** [chromaui/chromatic-cli#151]
I'm getting this error when trying to run the new CLI against an existing project:

```
% yarn chromatic-staging 
yarn run v1.17.3
$ CHROMATIC_INDEX_URL=https://staging-www.chromatic.com chromatic --project-token 71wybmryxr8

Chromatic CLI v5.0.0-alpha.4
https://github.com/chromaui/chromatic-cli

  ✖ Authenticating with Chromatic
    → HTTPClient failed to fetch https://staging-www.chromatic.com/graphql, got 403/Forbidden
    Retrieve git information
    Collect Storybook metadata
    Build Storybook
    Publish your built Storybook
    Verify your Storybook
    Take snapshots of your stories

✖ Failed to authenticate
HTTPClient failed to fetch https://staging-www.chromatic.com/graphql, got 403/Forbidden
→ View the full stacktrace below

If you need help, please chat with us at https://www.chromatic.com/docs/ for the fastest response.
You can also email the team at support@chromatic.com if chat is not an option.

Please provide us with the following info:
{
  "timestamp": "2020-06-13T00:27:53.912Z",
  "sessionId": "d65149a9-685d-4d9f-befe-5a849a2b484c",
  "nodePlatform": "darwin",
  "nodeVersion": "12.6.0",
  "packageName": "chromatic",
  "packageVersion": "5.0.0-alpha.4",
  "flags": {
    "projectToken": "71wybmryxr8",
    "interactive": true
  },
  "errorType": "Error",
  "errorMessage": "✖ Failed to authenticate\nHTTPClient failed to fetch https://staging-www.chromatic.com/graphql, got 403/Forbidden"
}

Error: ✖ Failed to authenticate
HTTPClient failed to fetch https://staging-www.chromatic.com/graphql, got 403/Forbidden
    at retry.retries.retries (/Users/zol/Git/shapes/node_modules/chromatic/bin/io/HTTPClient.js:41:25)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I've verified that the project token is correct here: https://www.staging-chromatic.com/manage?appId=5e294ce2f99ed20022e96617

**Comment by tmeasday** [comment]
@zol - first can you try the latest beta?

Second what if you set staging URL to https://www.staging-chromatic.com/graphql?

**Comment by ghengeveld** [comment]
For staging we're still using `chromaticqa.com`. So this should work:
```
CHROMATIC_INDEX_URL=https://staging-www.chromaticqa.com/graphql
```

**Comment by zol** [comment]
Can confirm using the *qa.com url fixes the issue with both the alpha and latest beta. The latest beta DOES NOT work with the *chromatic.com url.

**Comment by tmeasday** [comment]
> For staging we're still using chromaticqa.com.

Huh? Are we? that is just a secondary domain for staging-chromatic.com.

> CHROMATIC_INDEX_URL=https://staging-www.chromaticqa.com/graphql

This is wrong it shouldn't have the `/graphql` at the end in any case.

> The latest beta DOES NOT work with the *chromatic.com url.

Ummm I have been testing for the last few days with that URL, I suspect you specified it wrong somehow. Can confirm *it does* work with `CHROMATIC_INDEX_URL=https://index.staging-chromatic.com`

> I'm getting this error when trying to run the new CLI against an existing project:
> `CHROMATIC_INDEX_URL=https://staging-www.chromatic.com `

The original mistake here is it is www.staging-chromatic.com (or index.staging-chromatic.com, both work), not staging-www.chromatic.com.

**Comment by zol** [comment]
Gotcha, can confirm `CHROMATIC_INDEX_URL=https://staging-www.chromatic.com` works. Closing this out.

**Comment by tmeasday** [comment]
> Gotcha, can confirm CHROMATIC_INDEX_URL=https://staging-www.chromatic.com works. Closing this out.

Hahaha this was the original incorrect URL you used! I think you mean www.staging-chromatic.com.

**Comment by zol** [comment]
Ugh yeah that's what I meant

**Comment by Murodali** [comment]
> Gotcha, can confirm `CHROMATIC_INDEX_URL=https://staging-www.chromatic.com` works. Closing this out.

How did you the request url to this url above?

**Comment by ghengeveld** [comment]
@Murodali do not use the `CHROMATIC_INDEX_URL` provided in this thread. It's only meant for testing purposes.

**Comment by ghengeveld** [comment]
Deleting this issue to prevent others from accidentally using this in the future.
