### ISSUE TITLE
Environment proxy variables for HTTP(S) Requests

### ISSUE THREAD

**Issue by pascal-puetz** [chromaui/chromatic-cli#152]
**What happens?**
The CLI fails when trying to connect to the GraphQL endpoint (https://index.chromatic.com/graphql). The request times out after 3 tries.

**Why?**
We are currently evaluating chromatic in our company. So far it does looks very promising.
But unfortunately, we can't get it to work in our build pipeline. I'm strongly suspecting our corporate proxy might be the culprit. I could narrow the code throwing the error down to the following (https://github.com/chromaui/chromatic-cli/blob/54f4176af352e582b5f2014ae2bd01ea11a2a555/bin/io/HTTPClient.js#L30) and saw that node-fetch is used which does not use the http_proxy, https_proxy and no_proxy variables from the environment.

This is the log we are getting (project token removed from log):

>  $ chromatic --project-token=XXXXXX --debug
> 79 Chromatic CLI v5.0.0
> 80 https://www.chromatic.com/docs/cli
> 81 Authenticating with Chromatic
> 82  → Connecting to https://index.chromatic.com
> 83 Could not retrieve package info from registry; skipping update check
> 84 Fetch failed; retrying 1/3
> 85 Fetch failed; retrying 2/3
> 86 Fetch failed; retrying 3/3
> 87  → request to https://index.chromatic.com/graphql failed, reason: connect ETIMEDOUT 35.175.20.97:443
> 88  ✖ Failed to authenticate
> 89 request to https://index.chromatic.com/graphql failed, reason: connect ETIMEDOUT 35.175.20.97:443
> 90 → View the full stacktrace below
> 91  If you need help, please chat with us at https://www.chromatic.com/docs/cli for the fastest response.
> 92  You can also email the team at support@chromatic.com if chat is not an option.
> 93  Please provide us with the following info:
> 94  {
> 95 "timestamp": "2020-06-20T21:35:19.746Z",
> 96 "sessionId": "8965a651-50e4-4338-a2cd-e4c24f1d5ce3",
> 97 "nodePlatform": "darwin",
> 98 "nodeVersion": "10.17.0",
> 99 "packageName": "chromatic",
> 100 "packageVersion": "5.0.0",
> 101 "flags": {
> 102  "projectToken": "XXXXXX",
> 103  "debug": true,
> 104  "interactive": true
> 105 },
> 106 "errorType": "FetchError",
> 107 "errorMessage": "✖ Failed to authenticate\nrequest to https://index.chromatic.com/graphql failed, reason: connect ETIMEDOUT 35.175.20.97:443"
> 108 }
> 109

> 110 FetchError: ✖ Failed to authenticate
> 111 request to https://index.chromatic.com/graphql failed, reason: connect ETIMEDOUT 35.175.20.97:443
> 112  at ClientRequest.<anonymous> (/Users/buildadm/.gitlab-runner/builds/182c2cf3/0/PATH_TO_PROJECT/node_modules/node-fetch/lib/index.js:1455:11)
> 113  at ClientRequest.emit (events.js:198:13)
> 114  at ClientRequest.EventEmitter.emit (domain.js:448:20)
> 115  at TLSSocket.socketErrorListener (_http_client.js:392:9)
> 116  at TLSSocket.emit (events.js:198:13)
> 117  at TLSSocket.EventEmitter.emit (domain.js:448:20)
> 118  at emitErrorNT (internal/streams/destroy.js:91:8)
> 119  at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
> 120  at process._tickCallback (internal/process/next_tick.js:63:19)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199921881886840/1199953396965821) by [Unito](https://www.unito.io)

**Comment by pascal-puetz** [comment]
I could verify that it is indeed the proxy's fault. I injected a small code snipped that sets a global HttpsAgent into the chromatic cli's node file (located in node_modules/.bin) - and the command works. I'll attach the snipped (obviously, this was only for debugging purposes but works as a very ugly workaround, too).

Script to that handles the injection:
```
const fs = require('fs');
const data = fs.readFileSync('./node_modules/.bin/chromatic').toString();

const [firstLine, ...restLines] = data.split('\n');
const linesWithInjectedScript = [
  firstLine,
  `
    var http = require('http');
    var https = require('https');
    var HttpsProxyAgent = require('https-proxy-agent');

    const globalAgent = new HttpsProxyAgent(process.env.http_proxy || process.env.HTTP_PROXY);
    http.globalAgent = globalAgent;
    https.globalAgent = globalAgent;
  `
    .split('\n')
    .map(line => line.trim())
    .join('\n'),
  ...restLines,
];

fs.writeFileSync('./node_modules/.bin/chromatic', linesWithInjectedScript.join('\n'), 'UTF-8');
```

And this is what the modified node_modules/.bin/chromatic file looks like:
```
#!/usr/bin/env node

// INJECTED PART START
var http = require('http');
var https = require('https');
var HttpsProxyAgent = require('https-proxy-agent');

const globalAgent = new HttpsProxyAgent(process.env.http_proxy || process.env.HTTP_PROXY);
http.globalAgent = globalAgent;
https.globalAgent = globalAgent;
// INJECTED PART END

require('dotenv').config();
require('esm')(module)('./main.js').main(process.argv.slice(2));
```

**Comment by tmeasday** [comment]
Thanks for the report @pascal-puetz.

This does come up from time to time, although I guess as people run chromatic in CI situations (where proxies usually aren't an issue) they typically find a way to work around it.

It's a pain that node doesn't do this automatically.

**Comment by ricovitch** [comment]
Also stuck on using chromatic behind corporate proxy without a manual workaround like pascal mentioned.
Would be very nice to support "standard" HTTP_PROXY environment variable.

**Comment by tmeasday** [comment]
Hi @ricovitch -- yes we have this planned to be worked on this quarter.
