### ISSUE TITLE
License for older packages

### ISSUE THREAD

**Issue by ariel11** [chromaui/chromatic-cli#154]
Hi,

I help out with the open source project, ClearlyDefined.  It's a database of open source license information.

For the older NPM packages like version 2.2.2, we are not finding any license info - http://registry.npmjs.com/storybook-chromatic/2.2.2 or https://cdn.jsdelivr.net/npm/storybook-chromatic@2.2.2/package.json.  

Do you intend for these older packages to also be licensed under the MIT license?

Thanks!

**Comment by tmeasday** [comment]
Hi @ariel11, yes that is correct!
