### ISSUE TITLE
Detect or even handle when build-storybook script includes `-o`

### ISSUE THREAD

**Issue by tmeasday** [chromaui/chromatic-cli#162]
We quite commonly get this issue when teams' `build-storybook` script includes a `-o`:

> ✖ Failed to verify your Storybook\nJavaScript failed to load at ...

The URL posted 404s as the directory we uploaded was empty.

We should handle this better by:

1. detecting the directory is empty, and telling them the likely reason (good) 👉 #163
2. detecting the script has a flag, and warning them if it's not going to yield what they expect
3. actually just grabbing their SB from the specified output location if they set it

We should detect the actual output dir from what build-storybook returns, instead of relying on our passed output dir to have been propagated and used. If the two locations differ, we can additionally warn the user about this.

**Comment by ghengeveld** [comment]
This can be reproduced as follows:

In package.json scripts:
```
"build-storybook": "npm run buildit",
"buildit": "build-storybook -o storybook-out"
```

Now run `yarn chromatic`, which defaults to using `build-storybook`.

**Comment by tmeasday** [comment]
Works great!

**Comment by ndelangen** [comment]
Yeah I verified this too
