### ISSUE TITLE
Better handling for missing iframe.html and build 404s

### ISSUE THREAD

**Issue by domyen** [chromaui/chromatic-cli#163]
We should check if the output dir contains an iframe.html before uploading. Otherwise throw an error.

Actually preventing this situation from happening goes in #162

**Comment by tmeasday** [comment]
This is related to https://github.com/chromaui/chromatic-cli/issues/162 which i opened yesterday.

**Comment by tmeasday** [comment]
Works great.

**Comment by ndelangen** [comment]
verified
