### ISSUE TITLE
Improve messaging for "no stories found" error

### ISSUE THREAD

**Issue by domyen** [chromaui/chromatic-cli#175]
Users can run into this error when Storybook fails to build: 
![image](https://user-images.githubusercontent.com/263385/89939512-0de08380-dbe6-11ea-9bc6-18effbc6aa7d.png)

We should assume that a users Storybook has stories. After all, why else would they use Chromatic? And add more messaging to the error at the **bottom** that says:

> Your statically built Storybook has no stories. This is likely not a Chromatic issue. Usually, there's an error with the output of Storybook's default build-storybook command. You can debug by running build-storybook in your command line and opening the generated index.html in your browser.

**Comment by tmeasday** [comment]
Another thing that's come up a couple of times is setting `parameters.chromatic.disable = true` on all stories.

**Comment by domyen** [comment]
@tmeasday Can we detect that and use a different error message? 

> You disabled Chromatic on all your stories. Re-enable Chromatic in your main.js.

**Comment by tmeasday** [comment]
Hmm, maybe. Not sure it'd be easy.

Realistically we should allow builds with all stories disabled; they should get uploaded but not captured.

**Comment by domyen** [comment]
Ah right, I always forget about publish-only SBs

**Comment by tmeasday** [comment]
@domyen I guess this is different to publish-only (where you turn off capture in our UI) -- but it is effectively the same thing I guess. We actually need to think about it in a bit more detai.
