### ISSUE TITLE
CLI fails on setup for very basic CRA flow

### ISSUE THREAD

**Issue by kylesuss** [chromaui/chromatic-cli#177]
https://github.com/kylesuss/basic-storybook/tree/7d7d823f896b1828b6b682860bd891046fc3908c

In the above repo/commit, I had:

1. Bootstrapped a new CRA app: `npx create-react-app basic-storybook`
2. `cd`ed into my app
3. Run `npx sb init`
4. Run `npx chromatic --project-token=<token>`

In doing so, I get this error:

```
Cannot find module '../../package.json'
Require stack:
- /Users/kyle/Code/chromatic/packages/storybook-chromatic/dist/bin/chromatic.js
```

You can replicate by cloning the repo, setting up a new project on Chromatic & then repeating step 4 w/ your new token.

**Comment by tmeasday** [comment]
@kylesuss I reckon `npx` is using a linked version of the CLI there (see the path of the error?)

If you put `yarn add chromatic` in between steps 3 & 4 I bet it works.

**Comment by kylesuss** [comment]
Oh good call. That's annoying. I didn't realize `npx` did that.
