### ISSUE TITLE
Surface component errors in CLI output

### ISSUE THREAD

**Issue by kylesuss** [chromaui/chromatic-cli#178]
Not sure of the feasibility of this (it seems possible to me) but is it possible to surface component errors during the CLI build? I'm talking about things that don't break the Storybook build, but will fail in a browser. Presumably our snapshot will have that status, right?

**Comment by tmeasday** [comment]
Yeah, this seems like a good idea!

**Comment by paulelliott** [comment]
Closed due to age. Please reopen if you feel this is still relevant for you.
