### ISSUE TITLE
Add support for .env.local

### ISSUE THREAD

**Issue by christopher-francisco** [chromaui/chromatic-cli#182]
We commit our .env since we bootstraped from create-react-app.  The .env.local is ignored. 

We'd like to avoid ignoring .env as that's where we share envs between `.env.development` and `.env.production`. Would like to avoid maintaining 2 files

**Comment by tmeasday** [comment]
Hi @christopher-francisco can you not use `dotenv` on the CLI to turn your `.env-local` into environment varialbes?

**Comment by christopher-francisco** [comment]
@tmeasday I am dumb, it never crossed my mind even though I've done it before 🤦 Thanks for the idea, I'll closet this
