### ISSUE TITLE
Support for self signed certificates

### ISSUE THREAD

**Issue by kylesuss** [chromaui/chromatic-cli#184]
I received a support request with the following CLI failure details:

```
"errorType": "FetchError",
"errorMessage": "✖ Failed to authenticate\nrequest to https://index.chromatic.com/graphql failed, reason: self signed certificate in certificate chain"
```

The customer noted that: "There is self signed cert in yarnrc"

The yarnrc looks like:

```
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


cafile "/path/to/certificates.crt"
lastUpdateCheck 1599849070591
strict-ssl true
```

NOTE: you can work around this via setting `NODE_TLS_REJECT_UNAUTHORIZED=0`

**Comment by tmeasday** [comment]
@kylesuss I'm not sure what's going on here but we don't have a SS cert at that URL, that's for sure. Should we close this?

**Comment by kylesuss** [comment]
@tmeasday it wasn't us who had the cert, it was the customer. They said:

> Yes, I have to setup the self signed cert. It is company required cert.

So for some reason their company requires that they use this & it doesn't work when they try to use it w/ Chromatic. Seems rare, but I wanted to document it.

**Comment by tmeasday** [comment]
Hmm, so maybe not a self signed certificate but a custom certificate authority?

**Comment by tmeasday** [comment]
I guess a custom CA that uses self-signed-certs to do MITM.

**Comment by tmeasday** [comment]
Possibly passing `NODE_TLS_REJECT_UNAUTHORIZED=0` works around this.

**Comment by brycesnyder** [comment]
`NODE_TLS_REJECT_UNAUTHORIZED=0` is last minute fix, but, it worked for me.. potentially a suggestion, but, not preferred.

**Comment by tmeasday** [comment]
@brycesnyder I would guess the best we could do here is something like `yarn chromatic --no-reject-unauthorized` and a hint about why you might do that if the error is thrown.

I'm sort of wondering if just suggesting users use the env var is really so different? In which case the "fix" here would just be catching the specific error and making the suggestion.

**Comment by tmeasday** [comment]
Let's add the flag (maybe `--allow-self-signed`?), and intercept the error with a hint to try the flag.

**Comment by brycesnyder** [comment]
@tmeasday  the only issue I'm finding is how to do that with my PC boxes, doesn't seem to work for them...

**Comment by tmeasday** [comment]
@brycesnyder you could try using [`cross-env`](https://www.npmjs.com/package/cross-env)?

This is one reason for us too add the flag ;)

**Comment by brycesnyder** [comment]
@tmeasday ahh I didn't even think of using that.. I'll try it out!

**Comment by thafryer** [comment]
Closing this! We have not had any more requests for this recently. If more people run into this, we can reopen!
