### ISSUE TITLE
Adding chromatic-ignore css class to element isn't working in Chrome

### ISSUE THREAD

**Issue by markcellus** [chromaui/chromatic-cli#189]
Hello! I have an element in a Story that has a looping animation set via the `animation` CSS property that uses a `@keyframe`. I'm trying to ignore the element using the chromatic-ignore CSS class specified in the [docs](https://www.chromatic.com/docs/ignoring-elements#ignore-dom-elements) and it appears to be working for Firefox and IE11 when evaluated by Chromatic. But Chrome seems to always still trigger visual changes when the component code hasn’t changed. Any idea what could be the problem? Thanks in advance!

**Comment by tmeasday** [comment]
Hi @mkay581 perhaps you could open a conversation in-app (using intercom, bottom right) and link us to an example so we can take a closer look?
