### ISSUE TITLE
Outside of recreating the project, regenerate token?

### ISSUE THREAD

**Issue by JackHowa** [chromaui/chromatic-cli#205]
The chromatic/storybooks teams(s) do an awesome job! Really like the service and helpful. I'm curious about a feature: Can we regenerate the project token for a project? 

I've looked around the UI near the screenshot below. I've also looked through issues. Feel free to email me if it's easier at jack.howard@washpost.com

<img width="657" alt="Screen Shot 2020-11-06 at 14 56 07" src="https://user-images.githubusercontent.com/5950956/98413948-26730500-2040-11eb-8885-1fb957808d21.png">

**Comment by tmeasday** [comment]
Hi Jack, right now you need to send a message to support for this. You can email support @chromatic.com or use the intercom chat widget.
