### ISSUE TITLE
Monorepo support for the action

### ISSUE THREAD

**Issue by julien51** [chromaui/chromatic-cli#209]
We are using Chromatic in our monorepo. Only a single of our repos currently has chromatic setup and we'd love to use the `chromaui/action` actions, but it looks like they assume that the chromatic commands are set at the root of the repo?

**Comment by thelfensdrfer** [comment]
See #197

**Comment by QuinnNgo** [comment]
Hi! Would it be possible to add `workingDir` to the documentation for https://github.com/chromaui/action? Had to do a little digging to find this! Thanks so much for implementing it :)

**Comment by tmeasday** [comment]
Going to close this in favor of #197.
