### ISSUE TITLE
Add `--ignore-last-build-on-branch` option to the GitHub Action

### ISSUE THREAD

**Issue by domyen** [chromaui/chromatic-cli#210]
[Reported by customer](https://app.intercom.com/a/apps/zj7sn9j1/inbox/inbox/all/conversations/27253873299)

Expose `[--ignore-last-build-on-branch](https://www.chromatic.com/docs/branching-and-baselines#rebasing)` as an option in the GH Action. For example:

```
ignoreLastBuildOnBranch: branch-name
```

**Comment by tmeasday** [comment]
Maybe just a documentation issue?

**Comment by domyen** [comment]
Yup – closing
