### ISSUE TITLE
Chromatic CLI not building storybook

### ISSUE THREAD

**Issue by stefan-cross** [chromaui/chromatic-cli#213]
Hello, 

I am having issues getting chromatic cli to build the storybook after the intial run... It hangs and doesnt appear to create any artifacts in the `/var/...` folder. I raised this on SO the other day but thought it might be worth raising here also. 

In order to get chromatic to build the storybook I have to exectute the following:

`./node_modules/.bin/chromatic --project-token=xxxxfooxxxx`

Let me know if theres more info that might help... Or if you would rather the detials were lifted out of the SO post...

https://stackoverflow.com/questions/65094064/chromatic-cli-not-building-storybook

**Comment by jtloomos** [comment]
This has been reported by another user via Intercom (https://app.intercom.com/a/apps/zj7sn9j1/inbox/inbox/conversation/27253892088)

**Comment by sean-rallycry** [comment]
If it is the same issue I am encountering, I see the following in the `build-storybook.log`:

```
Starting: --silent build-storybook -- --output-dir C:\Users\refuz\AppData\Local\Temp\chromatic--8916-TLKmiTwitUfY
node: bad option: --silent
```

I am running node v15.5.1 and npx 7.3.0

**Comment by sean-rallycry** [comment]
I believe this line of code is why the workaround proposed by the OP is effective:  https://github.com/chromaui/chromatic-cli/blob/c6964c91ee42a5020e8ce6633cbccd6e773428c2/bin/tasks/build.js#L33

**Comment by ghengeveld** [comment]
I've made a prerelease for the fix, can you verify it works? `yarn add chromatic@5.5.1-dev.0`

**Comment by stefan-cross** [comment]
Awesome, I can confirm that has fixed things for myself, updated https://stackoverflow.com/questions/65094064/chromatic-cli-not-building-storybook/65633940#65633940

**Comment by stefan-cross** [comment]
Not sure what the process is now, shall I close this?

**Comment by ghengeveld** [comment]
No need, it'll be auto-closed when the PR gets merged.

**Comment by manoadamro** [comment]
same problem in v5.6.2
