### ISSUE TITLE
Compatibility with npm 7

### ISSUE THREAD

**Issue by kokiebisu** [chromaui/chromatic-cli#217]
I am currently trying to publish storybook but the process keeps hanging on step 6: Building your Storybook.

![スクリーンショット 2020-12-06 午後7 13 38 2](https://user-images.githubusercontent.com/43525282/101305434-8ef80200-37f7-11eb-938f-8518fc14af77.png)

I tried running the build-storybook command alone and then it works.
```
build-storybook -- --output-dir /var/folders/b6/g83mw8h9531btnbcmd3s7dh80000gn/T/chromatic--84494-mYwHeFxGFSLu
```

I checked the build-storybook.log generated and it gives me this message. 
```
Starting: --silent build-storybook -- --output-dir /var/folders/b6/g83mw8h9531btnbcmd3s7dh80000gn/T/chromatic--84494-mYwHeFxGFSLu
node: bad option: --silent
```

Thanks in advance for the help!

**Comment by tmeasday** [comment]
Hey @kokiebisu -- what version of `npm` or `yarn` are you using?

**Comment by kokiebisu** [comment]
Thanks for the reply! 
I’m using 
Yarn: 1.22.5
Npm: 7.0.15

**Comment by tmeasday** [comment]
Sounds like maybe a npm7 compatibility issue?

@kokiebisu in the meantime you can manually build your storybook and then run `chromatic` with the `-d` (or `--storybook-build-dir`) flag pointing to the build storybook directory.

**Comment by dbvisel** [comment]
I think the same thing is happening to me with NPM v7.0.14, Node v15.3.0. Will try with an older version of Node?

**Comment by tmeasday** [comment]
Sure!

**Comment by kokiebisu** [comment]
I was able to publish storybook but now I am getting a new error when I open storybook on chromatic. Does this have anything to do with the build? 
![スクリーンショット 2020-12-10 午後2 52 05](https://user-images.githubusercontent.com/43525282/101839761-ccaaa280-3af7-11eb-9ad7-318c6477a228.png)

**Comment by kokiebisu** [comment]
This was an issue on the storybook side.
https://github.com/storybookjs/storybook/issues/12952

I also used yarn to get everything to work since npm gave me a bunch of issues. I think there are compatibility issues with npm 7 just as @tmeasday mentioned. I will close.

**Comment by tmeasday** [comment]
Let me reopen for other users.

**Comment by tmeasday** [comment]
I think this was fixed with https://github.com/chromaui/chromatic-cli/pull/237
