### ISSUE TITLE
Debugging broken stories

### ISSUE THREAD

**Issue by mrlubos** [chromaui/chromatic-cli#230]
Hey! I am wondering how would one go about debugging a broken story in a large Storybook collection? Let's say I have 1,000 of stories and I want to debug a specific story because something is not working correctly, e.g. the viewport gets cut off. I can use trial and error until I arrive at the solution, but this will be slow and waste a lot of resources as every run produces thousands of snapshots. Is it possible to use the CLI locally to preview the final result? Thanks!

**Comment by ghengeveld** [comment]
You can use the `only` flag to run a single story (or a set matching a glob) on Chromatic. See https://www.chromatic.com/docs/cli#debug-options

Alternatively, you can run `build-storybook` and browse the static output using Chrome 84 on BrowserStack. Using Safari also tends to reveal a lot of problems.

**Comment by mrlubos** [comment]
Thank you @ghengeveld !
