### ISSUE TITLE
UI Review isn't being reported on GitHub in 5.6.0

### ISSUE THREAD

**Issue by domyen** [chromaui/chromatic-cli#238]
UI Review status is not being reported to GitHub in 5.6.0. Previous versions 5.2–5.5 work so it does not look like a change in the way Chromatic talks to GitHub but in the package code itself.

Reported by @lifeiscontent 

https://app.intercom.com/a/apps/zj7sn9j1/inbox/inbox/1497205/conversations/27253895362

**Comment by ghengeveld** [comment]
Hotfixed deployed and looking good.
