### ISSUE TITLE
Storybook composition inside only one chromatic instance

### ISSUE THREAD

**Issue by OleksiiBruma** [chromaui/chromatic-cli#240]
Hi guys. I hope you are doing ok!

We have a project which is migrated from handlebars (@storybook/html) to react (@storybook/react) 
Node.js 10
Each storybook has separate package.json but we start them simultaneously:

`"storybook" : "npm run start-storybook -p 7010 --prefix 'path to the react project' & npm run start-storybook"`

@storybook/react is nested in @storybook/html using refs (see below)
```
refs: {
    react: {
      title: "React",
      url: "http://localhost:7010",
    },
  },
```
Build for chromatic: 

`"build-storybook": "npm run build-storybook --prefix 'path to the react project' -- -o & npm run build-storybook -- -o"`

Questions:
1. There is a problem with the CORS during starting both storybooks. How to configure it properly? 
2. Is it possible to have a storybook composition inside only one chromatic instance?

**Comment by tmeasday** [comment]
Hi @OleksiiBruma, I'm not quite sure what you are looking for here -- are you hoping to capture stories from both storybooks in Chromatic via composition? This isn't currently supported in Chromatic, sorry about that! 

It might be worth writing into support if you want to discuss your use case further.
