### ISSUE TITLE
Shim for CustomElements

### ISSUE THREAD

**Issue by tmeasday** [chromaui/chromatic-cli#26]
I think polymer makes use of `window.CustomElementRegistry.prototype`.

Note this one is semi-urgent because simply adding it to `.storybook/config.js` doesn't work (I suspect because the code line runs when a dependency is loaded.

You can see the behaviour if you do:

```
git clone https://github.com/semisse/polymer-3-first-element
cd polymer-3-first-element
npm i
yarn chromatic test -a <some app-code>
```

**Comment by ndelangen** [comment]
There are multiple version of the custom-elements spec.

I'm afraid of opening a can of worms tbh.

here's a polyfill I'm considering: https://github.com/webcomponents/custom-elements

Should I just add this into JSDOM by default?

**Comment by tmeasday** [comment]
I'm not sure. We should just do the least possible to get something that vaguely looks like what Chrome offers. I don't want to add too much to people's bundle for a feature we don't actually make use of. 

We really just want to avoid errors. A polyfill seems too much.

**Comment by ndelangen** [comment]
I upgraded https://github.com/semisse/polymer-3-first-element to the latest release and it seems to work just fine?

**Comment by ndelangen** [comment]
Yeah I tried with both `npm` and `yarn`. upgraded to version `3.0.3` and it just works.
