### ISSUE TITLE
Snapshots doesn't match actual story...

### ISSUE THREAD

**Issue by MarkLyck** [chromaui/chromatic-cli#275]
I'm running into an issue with very flaky Chromatic tests...

In storybook my component always renders like this:
<img width="1680" alt="Screen Shot 2021-02-06 at 12 21 54" src="https://user-images.githubusercontent.com/6841110/107125116-ebb67e00-6875-11eb-90ad-e22be164fe54.png">

Even in the Chromatic library it still renders correctly:
<img width="1680" alt="Screen Shot 2021-02-06 at 12 22 33" src="https://user-images.githubusercontent.com/6841110/107125129-012ba800-6876-11eb-8dcd-d5a5cc116633.png">

But for some reason ~80% of the time, the snapshots are rendered like this:
<img width="1680" alt="Screen Shot 2021-02-06 at 12 22 56" src="https://user-images.githubusercontent.com/6841110/107125134-0ee12d80-6876-11eb-94ce-021268fb14d7.png">

My storybook includes making a network request which is mocked by `msw` https://mswjs.io/

the network request gets caught by the service worker and not hitting any actual API.

I am able to reproduce the success state 100% of the time in my storybook, both locally and on the one published. It never responds with a 401, and a real network request is never made.

I have also tried to build the storybook and it still works as expected. I have tested in offline mode and still works. It seems to only be a problem with Chromatic snapshots.

Chromatic renders the correct outcome about 40% of the time.

I've tried adding a delay of 0.1 seconds, 1 second and even 5 seconds. But doesn't change the outcome. Sometimes Chromatic shows the correct result, sometimes a loading screen & sometimes an error message.

Any idea why this is happening. These stories are pretty important for our testing so I don't want to just "disable" them for being "flaky"

**Comment by tmeasday** [comment]
@MarkLyck can you open a ticket with Chromatic support? You can link to this ticket and we can go from there.

 This repo is for issues with the CLI so I'll close this for cleanliness.

**Comment by peterlawless** [comment]
Was there any resolution to this?  I have a similar issue in which no amount of delay would capture content in chromatic that is clearly visible in storybook.

**Comment by tmeasday** [comment]
@peterlawless the reasons for this kind of issue are varied. You are best off writing into support as they are almost always specific to (usually private) details of your code base.
