### ISSUE TITLE
Publish to chromatic doesn't work on NPM 7

### ISSUE THREAD

**Issue by anthony-hull** [chromaui/chromatic-cli#276]
@anthony-hull wrote (npm 7.5.3):

I was getting an empty build folder and it was hanging on the build stage.
downgrading to `npm install -g npm@next-6 ` fixed the build stage

---

In https://github.com/chromaui/chromatic-cli/issues/299, @Ky6uk wrote:

Running `npm run build-storybook` manually works correctly, but `npm run chromatic` just hanging out after some timeout on `build-storybook` step.

* Node.js: `15.10`
* NPM: `7.6.0`
* Chromatic: `5.6.3`
* Storybook `6.1.21`

```js
Starting: build-storybook -- --output-dir /tmp/chromatic--34-bm7FCFVqGuuV
node:internal/modules/cjs/loader:926
  throw err;
  ^
Error: Cannot find module '/builds/company/webapp/storybook/build-storybook'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:923:15)
    at Function.Module._load (node:internal/modules/cjs/loader:768:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
    → Command failed: build-storybook -- --output-dir /tmp/chromatic--34-bm7FCFVqGuuV
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199921881886840/1199953259385715) by [Unito](https://www.unito.io/learn-more)

**Comment by manoadamro** [comment]
thanks @anthony-hull, I'd been stuck on this for a while!

**Comment by tmeasday** [comment]
@anthony-hull just to check were you running the latest version of the Chromatic CLI?

**Comment by anthony-hull** [comment]
Yes I was. I had run npx sb@latest upgrade before and I checked the version number against NPM for this project.

**Comment by OlegYakovlev1** [comment]
I got the same... `npm run build-storybook` works but `npm run chromatic` is failed
- node: 15.11.0
- npm: 7.6.0
- chromatic: 5.7.0
- storybook: 6.2.1

**Comment by Annet-4200** [comment]
I had the same issue with npm v7.8.0. 
The solution suggested in help is downgrade npm to v6.
I did this and with npm v6.14.12 it works fine.

**Comment by advanderveer** [comment]
Same issue on v7.9.0. Any update on a fix?

**Comment by cgodo** [comment]
Apparently, it works if calling chromatic from local package insted of using npx: See this comment #227 (https://github.com/chromaui/chromatic-cli/issues/227#issuecomment-811522687)

**Comment by tmeasday** [comment]
Thanks all for the help debugging this. The latest version of the CLI (`chromatic@5.8.0`) includes a fix and it should now be possible to use `npx` again w/ npm7

**Comment by aibrahim3546** [comment]
> Apparently, it works if calling chromatic from local package instead of using npx: See [this other's issue comment](https://github.com/chromaui/chromatic-cli/issues/227#issuecomment-811522687).
> 
> I guess the issue is how npx with npm >= 7.0 runs chromatic in a different way.
> 
> Summarizing the workaround:
> 
> 1. Install Chromatic locally
> 
> `npm i -D chromatic`
> 
> 1. Change package.json so it runs local chromatic:
> 
> Instead of `"chromatic": "npx chromatic --project-token <your-token>"` put `"chromatic": "chromatic --project-token <your-token>"`

This works. Thankkss.
