### ISSUE TITLE
permalink with slashes

### ISSUE THREAD

**Issue by woldtwerk** [chromaui/chromatic-cli#285]
Hi,
might not be the correct place to ask. How do I get a permalink to my storybook when the branch contains a slash?
e.g.: feature/abc

Obviously it doesn't work with the slash. I tried escaping it with %2F, but that didn't work.
The docs don't mention anything about special characters.
https://www.chromatic.com/docs/permalinks

**Comment by tmeasday** [comment]
Hi @woldtwerk -- this isn't currently supported, it is a common feature request, and we have it tracked fairly prominently internally. perhaps if you contact us in Chromatic support we can let you know when the feature ships.

**Comment by geisterfurz007** [comment]
Hey there, thanks for working on this amazing tool!
Will it also be mentioned in this issue thread when this is shipped? Then people can just subscribe to this issue and not everyone has to contact support to get updates. If not, I will be more than happy to reach out!
