### ISSUE TITLE
Gracefully handle missing "scripts" block in package.json

### ISSUE THREAD

**Issue by ghengeveld** [chromaui/chromatic-cli#290]
Currently, when attempting to run `chromatic` in a project with a package.json that doesn't contain the `"scripts"` property, we get the following error:

```
Cannot read property 'build-storybook' of undefined
```

We should tell the user to add a "scripts" section to their package.json.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199921881886840/1200015131426373) by [Unito](https://www.unito.io)

**Comment by amacneil** [comment]
Additionally, at least within a yarn 2 + workspaces environment, `chromatic` seems unable to find the `build-storybook` command. I had to add 

```json
"scripts": {
  "build:storybook": "yarn run build-storybook"
},
```

to my nested `package.json`, and run `yarn run chromatic --project-token=foo --build-script-name build:storybook` to make it find the storybook command.
