### ISSUE TITLE
about support for storybook package for vue3

### ISSUE THREAD

**Issue by nisshii0313** [chromaui/chromatic-cli#292]
Hello everyone.
In the vue community, there seems to be a movement to release a storybook package for vue3 as "@storybook/vue3".
(cf: https://github.com/storybookjs/storybook/issues/10654#issuecomment-779429245)

Is there any plan to support this movement in chromatic-cli?

(For example, I think we can add "vue3" to "viewLayers" here.
https://github.com/chromaui/chromatic-cli/blob/d17864b5002c440336687c80aa7da06074221744/bin/lib/getStorybookInfo.js#L5)

Please let me know if I've misunderstood something. Thanks :smiley:

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199921881886840/1200015132126433) by [Unito](https://www.unito.io/learn-more)

**Comment by tmeasday** [comment]
Sounds like a good idea @nisshii0313

**Comment by tmeasday** [comment]
@nisshii0313 you are right! Want to send a PR?

**Comment by nisshii0313** [comment]
@tmeasday  Yes, I want to send

**Comment by nisshii0313** [comment]
I sent a PR from my forked repository. I hope you will check it out. 👍

**Comment by tmeasday** [comment]
[Released in 5.7.0](https://github.com/chromaui/chromatic-cli/blob/next/CHANGELOG.md#570---2021-03-11)
