### ISSUE TITLE
Document outputs and publish new version of action?

### ISSUE THREAD

**Issue by mnquintana** [chromaui/chromatic-cli#293]
👋🏽 I just came across this recent change to add `storybookUrl` to the output of the Chromatic action: https://github.com/chromaui/chromatic-cli/commit/e5cf3c6b07bfeaa22f854aab12385aa606008cdd#diff-e0800b9a6c36cb7e1937f05f68784af42488be2266fad90cef27dc394b3b6b6fR152

I'm building a GitHub Actions step that needs access to the `storybookUrl` to work, so this is exactly what I've been looking for!

But, it looks like this change hasn't been published to the [action repo](https://github.com/chromaui/action) yet, which makes it really tricky to consume right now since actions require all dependencies to be bundled ahead of time.

It also looks like none of the currently supported `outputs` are documented in `action.yml`: https://github.com/chromaui/chromatic-cli/blob/next/action.yml

Would it be possible to:

1. document all supported outputs in `action.yml` (I'd be happy to submit a PR for this if it'd help)
1. publish a new version of the action?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199921881886840/1200015269989920) by [Unito](https://www.unito.io/learn-more)

**Comment by tmeasday** [comment]
> document all supported outputs in action.yml (I'd be happy to submit a PR for this if it'd help)

@mnquintana that would great!
