### ISSUE TITLE
Gracefully handle network issues by referring to the status page

### ISSUE THREAD

**Issue by ghengeveld** [chromaui/chromatic-cli#294]
E.g. `HTTPClient failed to fetch https://index.chromatic.com/graphql, got 503/Service Unavailable` should instruct the user to check http://status.chromatic.com

Reported [here](https://app.intercom.com/a/apps/zj7sn9j1/inbox/inbox/all/conversations/27253903140).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199921881886840/1200015183479697) by [Unito](https://www.unito.io/learn-more)

**Comment by paulelliott** [comment]
This work was completed in another issue.
