### ISSUE TITLE
Chromatic hangs out after timeout on "build-storybook" phase (npm 7.6.x)

### ISSUE THREAD

**Issue by Ky6uk** [chromaui/chromatic-cli#299]
Running `npm run build-storybook` manually works correctly, but `npm run chromatic` just hanging out after some timeout on `build-storybook` step.

* Node.js: `15.10`
* NPM: `7.6.0`
* Chromatic: `5.6.3`
* Storybook `6.1.21`

```js
Starting: build-storybook -- --output-dir /tmp/chromatic--34-bm7FCFVqGuuV
node:internal/modules/cjs/loader:926
  throw err;
  ^
Error: Cannot find module '/builds/company/webapp/storybook/build-storybook'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:923:15)
    at Function.Module._load (node:internal/modules/cjs/loader:768:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
    → Command failed: build-storybook -- --output-dir /tmp/chromatic--34-bm7FCFVqGuuV
```

**Comment by Ky6uk** [comment]
Possible related to #276.

**Comment by tmeasday** [comment]
Does this happen consistently @Ky6uk?

**Comment by tmeasday** [comment]
@Ky6uk based on this comment, I think downgrading to npm@6 should workaround this issue: https://github.com/chromaui/chromatic-cli/issues/227#issuecomment-795455449

**Comment by tmeasday** [comment]
I'm going to close this as a dupe of https://github.com/chromaui/chromatic-cli/issues/276 (even though the symptom is slightly different), as it helps with housekeeping at our end.
