### ISSUE TITLE
Package hangs after "uploading debug logs..." for a while

### ISSUE THREAD

**Issue by tmeasday** [chromaui/chromatic-cli#3]
E.g.If you do #2, on my machine it hangs for ~30s before exiting (sometimes it never exits?).

**Comment by ndelangen** [comment]
Yes, long term moving to winston sounds like a plan to me.

**Comment by ndelangen** [comment]
Is this closed by #7 @tmeasday ?

**Comment by tmeasday** [comment]
Sort of depending whether https://github.com/chromaui/chromatic-cli/issues/9 is the same thing ;)

**Comment by ndelangen** [comment]
"The uploading debug logs" has been deleted for sure, so in either case this issue is resolved. #9 is definitely the same thing, which should be resolved by my PR #19
