### ISSUE TITLE
Report build step durations

### ISSUE THREAD

**Issue by ghengeveld** [chromaui/chromatic-cli#303]
Besides the Chromatic test time, we should record the time spent running the CLI steps. In particular the Storybook build and upload times are relevant to report, because they are a significant part of the total Chromatic run time. Also it's relevant for analytics.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199921881886840/1200545736533991) by [Unito](https://www.unito.io)

**Comment by domyen** [comment]
That makes sense to me! That way folks can breakdown how much time is spent building Storybook vs capturing image snapshots.

**Comment by thafryer** [comment]
@ghengeveld @tmeasday did we ever do this?

**Comment by tmeasday** [comment]
I don't believe we current are recording this on the backend/in analytics at least

**Comment by paulelliott** [comment]
This was completed in another issue.
