### ISSUE TITLE
Consider adding support for `workflow_dispatch` event in GitHub Action

### ISSUE THREAD

**Issue by ghengeveld** [chromaui/chromatic-cli#307]
Requested [here](https://app.intercom.com/a/apps/zj7sn9j1/inbox/inbox/all/conversations/27253906975).

`workflow_dispatch` is a way to manually trigger a GitHub Action. See https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

This would need to be added here: https://github.com/chromaui/chromatic-cli/blob/62a5b6528c1cb8adecda4942f20003fc76b1edba/action/main.ts#L26-L52

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199921881886840/1200607016213437) by [Unito](https://www.unito.io)

**Comment by theKashey** [comment]
Yeah, we are generating only "changed" stories and need this escape hatch to be able run full tests when such comparison is not working by any reason.
