### ISSUE TITLE
Storybook upload does not work properly from windows

### ISSUE THREAD

**Issue by tmeasday** [chromaui/chromatic-cli#31]
![image](https://user-images.githubusercontent.com/132554/62741109-1b1bdd00-ba7d-11e9-8a35-22153ed0e22e.png)

I think what is happening here is the path we get for the assets uses the windows separator (which is correct on the client side) but we need to convert it to `/` when talking to AWS

**Comment by ndelangen** [comment]
PR is open, with a fix!
