### ISSUE TITLE
Dependabot can't find project token 

### ISSUE THREAD

**Issue by JackHowa** [chromaui/chromatic-cli#314]
Seeing an odd issue where chromatic cannot find the project token for a dependabot branch but can find the token for a normal contributor branch. Do you have any info for this? I couldn't find this in the chromatic ui action docs

https://github.com/WPMedia/engine-theme-sdk/blob/canary/.github/workflows/storybook-validate.yml github action 

https://github.com/WPMedia/engine-theme-sdk/pull/262/checks?check_run_id=2219670933 - failed run 

working in other branches as expected. Manually re-running this works surprisingly

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199921881886840/1200139815670796) by [Unito](https://www.unito.io)

**Comment by JackHowa** [comment]
<img width="1295" alt="Screen Shot 2021-04-12 at 15 32 01" src="https://user-images.githubusercontent.com/5950956/114457948-39b46e80-9ba4-11eb-9eb7-e459f09314ce.png">

may need to update token access here in new github setting

**Comment by JackHowa** [comment]
sorry for this, figured it out with new secrets tab for dependabot with chromatic. Not sure if this warrants documentation

**Comment by ndelangen** [comment]
@JackHowa How exactly did you fix this? Some configuration in dependabot?

**Comment by JackHowa** [comment]
Hey Norbert! sorry, I haven't fixed this yet. strange interplay between dependabot and chromatic? wonder if others have experienced this. 

I saw some documentation for not running chromatic with dependabot but wasn't sure if there was examples of this working or changing since github actions environments changing to have more scoped secrets.

**Comment by ndelangen** [comment]
I'm looking at https://github.com/WPMedia/engine-theme-sdk/pull/262/checks?check_run_id=2219670933 - failed run

But this seems to have run succesfully?

Am I looking at the wrong thing?

**Comment by JackHowa** [comment]
that run was re-ran manually. here's an example where I haven't manually triggered the github action https://github.com/WPMedia/engine-theme-sdk/pull/312

**Comment by ndelangen** [comment]
I see a difference in permissions between the 2 runs:

<details>
<img width="1360" alt="Screenshot 2021-04-22 at 16 42 59" src="https://user-images.githubusercontent.com/3070389/115734287-e0112880-a389-11eb-8686-8996c868cf19.png">
<img width="1181" alt="Screenshot 2021-04-22 at 16 43 03" src="https://user-images.githubusercontent.com/3070389/115734306-e30c1900-a389-11eb-964b-c39956949607.png">
</details>

Looks like the run by dependabot, might not have the proper access rights to read secrets?

I know GitHub doesn't share secret with forks, or untrusted actions... But I'd assume dependabot to be a trusted action, given how they are now part of github themselves.

https://github.community/t/allow-secrets-to-be-shared-with-forks-from-trusted-actions/16525
https://dependabot.com/blog/hello-github/

https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization#about-github-actions-permissions-for-your-organization

---

I think this might be where the solution lies:
https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization#enabling-workflows-for-private-repository-forks

Or maybe you have different 'environments' with different secrets defined?

https://colinwilson.uk/2021/01/03/environment-specific-secrets-in-github-workflows/

**Comment by JackHowa** [comment]
Ok thanks, I can look into this -- appreciate it!

**Comment by JackHowa** [comment]
haven't successfully found issues with our organization and enabling private forks. but did see this related dependabot issue https://github.com/dependabot/dependabot-core/issues/3253

**Comment by penx** [comment]
> Starting March 1st, 2021 workflow runs that are triggered by Dependabot from push, pull_request, pull_request_review, or pull_request_review_comment events will be treated as if they were opened from a repository fork. This means they will receive a read-only GITHUB_TOKEN and will not have access to any secrets available in the repository. 

https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/

**Comment by penx** [comment]
Perhaps there is another way for the Chomatic API to verify that the request came from a specific GitHub repository other than passing the key via a secret.

e.g. a read only GITHUB_TOKEN is available, if this token could be verified to ensure it came from a PR against the repository, perhaps this could be exchanged for the key or a temporary token.

Perhaps this article may be of some use

https://www.nearform.com/blog/github-dependabot-automation/

**Comment by ndelangen** [comment]
Looks like this is possible now:
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/managing-encrypted-secrets-for-dependabot

**Comment by penx** [comment]
@ndelangen I am told that adding them as dependabot secrets doesn't fix this, they're only accessible by the dependabot.yml, not by PRs created by dependabot.

Perhaps this has been resolved now but would be good to confirm first.

I should be able to take a look in the coming weeks.

**Comment by ndelangen** [comment]
The only other option I see, would be to not hide the project token in a secret, or not run chromatic on Dependabot PRs.

**Comment by lapa182** [comment]
We tried to use the solution proposed by the Dependabot team, but it doesn't seem like we can use `workflow_run` with Chromatic :(.

**Comment by ndelangen** [comment]
@ghengeveld Did you recently make a change to allow `workflow_run`?

**Comment by lapa182** [comment]
@ndelangen @ghengeveld do we have an update around `workflow_run`?

**Comment by divyakumarjain** [comment]
> @ndelangen I am told that adding them as dependabot secrets doesn't fix this, they're only accessible by the dependabot.yml, not in workflows initiated from PRs created by dependabot.
> 
> Perhaps this has been resolved now but would be good to confirm first.
> 
> I should be able to take a look in the coming weeks.

I agree dependabot secrets doesn't fix this, they're only accessible by the dependabot.yml, not in workflows initiated from PRs created by dependabot.

Also splitting the workflow and using workflow_run event does not help as workflow_run is not supported by chromaui.

Would suggest we reopen this issue.

**Comment by JackHowa** [comment]
we've disabled testing this for our workflow and ignored dependabot branches

**Comment by lapa182** [comment]
I would suggest reopening the issue since other customers have the same problem.

**Comment by tmeasday** [comment]
=>

**Comment by jeromecovington** [comment]
Yes I am also having this exact issue.
