### ISSUE TITLE
Cannot run a build with no stories

### ISSUE THREAD

**Issue by adrianiy** [chromaui/chromatic-cli#315]
**Problem**
Hi! i'm getting a error after publishing that says *cannot run a build with no stories*. But the storybook is published ok and it is visible in the preview url, the only thing that i see not working is the `isolatorUrl`.

I've checked the build log and everything seems to works ok.

**Context**
My project is a lerna monorepo with different frameworks (stencil, react, angular...) so i'm trying to workaround the publication by compiling all storybooks in subfolders of root storybook (html).

So it looks like this:
![image](https://user-images.githubusercontent.com/57523779/113033928-d6811000-9191-11eb-9c28-653dc57ec541.png)

so `angular` and `web-components` have their own built storybook files referenced in main.js like:
```javascript
    refs: (config, { configType }) => {

        return {
            webComponents: {
                title: 'Web Components',
                url: '/web-components',
            },
            angular: {
                title: 'Angular',
                url: '/angular',
            },
        };
    },

```

everything works ok with `npx http-server storybook-static` .... i'm very lost, would appreciate any kind of help 😃

**FYI**
with `npx http-server storybook-static` if i go to *http://127.0.0.1:8080/iframe.html* i get:
![image](https://user-images.githubusercontent.com/57523779/113036168-3c6e9700-9194-11eb-826d-f4b89b496147.png)

**Comment by kylesuss** [comment]
Hi @adrianiy  -- can you please email support@chromatic.com with your account ID so that we can take a look at your specific setup in detail?

**Comment by paulelliott** [comment]
Closed due to age. Please reopen if you feel this is still relevant for you.
