### ISSUE TITLE
Vague publish error

### ISSUE THREAD

**Issue by dudedigital** [chromaui/chromatic-cli#316]
Everything has been working fine but I recently tried to publish and I got an error. It's really hard to find info on such matters searching online for chromatic. I did see someone comment about the "build" term being misleading. I can't figure out what the error is... When I do a `build-storybook --log-level error` it seems to build without issue. Does this have something to do with snapshots or something else? I need some guidance.

```
× Encountered 1 build error: failing with exit code 2
Pass --allow-console-errors to succeed this command regardless of runtime build errors.
Build 7 failed after 13 seconds
    → Found 1 error (54 components, 88 stories, 88 snapshots); exiting with status code 2
```

Chromatic shows the build published and accessing it online works. But the Circle icon shows "!" Errored.

**Comment by tmeasday** [comment]
Hi @dudedigital -- it looks like one of your stories has an error -- have you tried looking at the build?

**Comment by dudedigital** [comment]
Hello @tmeasday, thank you for replying. I didn't see any errors when doing `npm run storybook` or `storybook-build`, I found the error by manually going through the stories eh.

**Comment by tmeasday** [comment]
Those errors won't show up until you actually render the story @dudedigital
