### ISSUE TITLE
Support prebuilt Storybook package

### ISSUE THREAD

**Issue by ghengeveld** [chromaui/chromatic-cli#317]
Reported [here](https://app.intercom.com/a/apps/zj7sn9j1/inbox/inbox/all/conversations/27253915916).

Modern Web's [Dev Server Storybook](https://github.com/modernweb-dev/web/tree/master/packages/dev-server-storybook) uses a prebuilt Storybook manager UI and doesn't require installing `@storybook/web-components`. Their [guide](https://modern-web.dev/guides/dev-server/storybook/) also doesn't suggest installing it.

This is problematic because the Chromatic CLI will look for a supported view layer package and not find any. It can be resolved by installing `@storybook/web-components` manually, but we should just support this use case out of the box.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199921881886840/1200198737996367) by [Unito](https://www.unito.io/learn-more)

**Comment by tmeasday** [comment]
@ghengeveld is this the fix? https://github.com/chromaui/chromatic-cli/pull/319

**Comment by ghengeveld** [comment]
@tmeasday It didn't at first, but I added explicit support for `@web/dev-server-storybook` now.
