### ISSUE TITLE
Issue uploading assets with spaces in the file name

### ISSUE THREAD

**Issue by tmeasday** [chromaui/chromatic-cli#32]
Unconfirmed (could be a SB bug?): it seems assets with a space in the filename are not uploaded properly.

**Comment by ndelangen** [comment]
Doesn't look like it's a storybook bug, it works when running storybook normally

**Comment by ndelangen** [comment]
Works when building a static version too

**Comment by ndelangen** [comment]
I cannot reproduce this bug

**Comment by tmeasday** [comment]
OK, thanks for investigating.
