### ISSUE TITLE
Unwanted DOM diffing is breaking CI

### ISSUE THREAD

**Issue by shamilovtim** [chromaui/chromatic-cli#329]
We use styled-components and randomly generated / compiled DOM. We only want Chromatic for visual diffing, not DOM diffing. It seems every single PR has a DOM diff and thus is flagged as "needing review." How do we turn off DOM diffing?

<img width="1788" alt="Screen Shot 2021-04-29 at 10 57 01 AM" src="https://user-images.githubusercontent.com/3495974/116572433-f6fbd180-a8d9-11eb-8493-0299363f86c2.png">

**Comment by ghengeveld** [comment]
Chromatic does not look at the DOM diff to flag changes, it only looks at changed pixels. The DOM diff is there only to help you determine why a visual change occurred.

**Comment by shamilovtim** [comment]
Sorry, to be clear, these components have not changed. The diff comes purely from the DOM. There is no visual diff. Every single component is flagged for review despite not having any visual diffs. Are you able to login to our account to see what I'm talking about?

**Comment by domyen** [comment]
As Gert mentioned, the DOM diff is there to help you identify visual changes (pixels). 

In your case, something else is happening which is unrelated. Will follow up with you in Intercom.
