### ISSUE TITLE
Issue with CLI and Vue 3

### ISSUE THREAD

**Issue by jonniebigodes** [chromaui/chromatic-cli#330]
While working on the updates for the Intro to Storybook tutorial, more specifically for Vue3 and Storybook 6.2, it seems that there's an issue with the deployment chapter of the tutorial. When the reader gets to that point we'll get an error while deploying his/her Storybook to Chromatic. Here's what I've done to confirm the issue:

- Added Chromatic with `yarn add -D chromatic`.
- Setup a new project in Chromatic as usual.
- Ran `yarn chromatic --project-token=my-project-token` and faced an error with the build.
- As a safeguard ran `npx chromatic --project-token=my-project-token` same error.
- Tried to generate a build with `yarn build-storybook && npx http-server storybook-static` to preview the local build. Same error.
- Purged my `node_modules` folder and `yarn.lock` and installed the dependencies once again, by running `yarn`.
- Ran the combination of commands above to generate and preview the production build and it worked.
- Ran `npx chromatic --project-token=my-project-token` it went through.
- Created the GitHub Workflow as documented in the tutorial and pushed it to the repo.
- Checked the Actions, to monitor the workflow execution and I was hit with the same exact error I ran into locally

For reference, the repo is [here](https://github.com/jonniebigodes/intro-storybook-vue-3), and the error [here](https://github.com/jonniebigodes/intro-storybook-vue-3/runs/2467507561?check_suite_focus=true).

Node version: v14.15.1
Npm version: 6.14.8
Yarn version: 1.22.10

Feel free to provide feedback

**Comment by tmeasday** [comment]
> Tried to generate a build with yarn build-storybook && npx http-server storybook-static to preview the local build. Same error.

@jonniebigodes can you give a bit more detail here? Are you saying the `yarn build-storybook` step failed? Or that it worked but then chromatic failed when you passed the built storybook with `--storybook-build-dir`?

**Comment by tmeasday** [comment]
It sounds like this is an issue with SB/`yarn`/`vue3` and Chromatic/GH isn't really involved.

It seems like the issue is that `vue-template-compiler` isn't installed in `node_modules`.

If you try locally installing with `yarn` is that the case? If you separate install with `npm` locally, is it installed in `node_modules`?

**Comment by jonniebigodes** [comment]
Closing this as it was reported in the Storybook issue tracker and is being looked at. Thanks for the help @tmeasday
