### ISSUE TITLE
Add a (hidden) flag to skip squash/rebase merge PR check.

### ISSUE THREAD

**Issue by kylesuss** [chromaui/chromatic-cli#332]
I have a customer reporting that they can consistently produce this error using the `--ci` flag on version 5.6.2 of the CLI:

```json
✖ Failed to retrieve git information
HTTPClient Failed to fetch https://api.github.com/repositories/<id>/pulls?base=nre-storybook&direction=desc&per_page=10&sort=updated&state=closed, got 502/Bad Gateway

If you need help, please chat with us at https://www.chromatic.com/docs/cli for the fastest response.
You can also email the team at support@chromatic.com if chat is not an option.

Please provide us with the above CLI output and the following info:
{
  "timestamp": "2021-04-30T18:11:43.175Z",
  "sessionId": "5f1765f9-5e1c-46d0-800c-2d00bf8a9c9e",
  "gitVersion": "2.20.1",
  "nodePlatform": "linux",
  "nodeVersion": "14.16.1",
  "packageName": "chromatic",
  "packageVersion": "5.6.2",
  "flags": {
    "interactive": true,
    "projectToken": "************",
    "ignoreLastBuildOnBranch": "nre-storybook",
    "preserveMissing": true,
    "exitOnceUploaded": ""
  },
  "buildScript": "./.storybook/build-storybook.sh",
  "errorType": "GraphQLError",
  "errorMessage": "✖ Failed to retrieve git information"
}
```

See https://app.intercom.com/a/apps/zj7sn9j1/inbox/inbox/all/conversations/27253920694 for full GitHub url.

Upon asking them to upgrade to `5.8.0`, they said that the issue happens intermittently & that the `--ci` flag has no effect on the outcome.

It looks like an issue with the GitHub API, but the fact that it is consistent is odd. Any ideas on what could be going on?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199921881886840/1200545736822755) by [Unito](https://www.unito.io)

**Comment by nigel-codaio** [comment]
Hi folks, this was filed on my behalf.  I can reproduce this within or outside of CircleCI so the `--ci` flag makes no difference.    

From what I see, it's an intermittent infrastructure issue.    Here's the result of two runs -- the first succeeds, the second fails.

### Success
```
root@ffb175f64801:~/project# ./node_modules/.bin/chromatic --project-token=********bb1d --junit-report /tmp/report/report.xml --debug

Chromatic CLI v5.8.0
https://www.chromatic.com/docs/cli

Authenticating with Chromatic
    → Connecting to https://index.chromatic.com
Authenticated with Chromatic
    → Using project token '********bb1d'
Retrieving git information
git info: {"commit":"cb53efd74af8892e32d93666b7adb3ae9f93c3b9","committedAt":1619812022000,"committerEmail":"nigel@coda.io","committerName":"Nigel Ellis","branch":"nre-storybook","slug":"coda-hq/coda","isTravisPrBuild":false,"fromCI":true,"ciService":"circleci"}
App firstBuild: '{"committedAt":1619041582000}', lastBuild: '{"commit":"cb53efd74af8892e32d93666b7adb3ae9f93c3b9","committedAt":1619812022000}', pullRequest: 'null'
Adding last branch build commit cb53efd74af8892e32d93666b7adb3ae9f93c3b9 to commits with builds
step: checking 20 up to 1619041582
step: commitsWithBuilds: cb53efd74af8892e32d93666b7adb3ae9f93c3b9
step: commitsWithoutBuilds:
running git rev-list HEAD       --since 1619041582       -n 20 --not cb53efd74af8892e32d93666b7adb3ae9f93c3b9
command output:
step: candidateCommits:
step: no candidateCommits; we are done
Final commitsWithBuilds: cb53efd74af8892e32d93666b7adb3ae9f93c3b9
running git rev-list cb53efd74af8892e32d93666b7adb3ae9f93c3b9 --not "cb53efd74af8892e32d93666b7adb3ae9f93c3b9^@"
command output: cb53efd74af8892e32d93666b7adb3ae9f93c3b9
Found parentCommits: cb53efd74af8892e32d93666b7adb3ae9f93c3b9
Retrieved git information
    → Commit 'cb53efd' on branch 'nre-storybook'; found 1 parent commit
Collecting Storybook metadata
```

### Fail
```
oot@ffb175f64801:~/project# ./node_modules/.bin/chromatic --project-token=********bb1d --junit-report /tmp/report/report.xml --debug

Chromatic CLI v5.8.0
https://www.chromatic.com/docs/cli

Authenticating with Chromatic
    → Connecting to https://index.chromatic.com
Authenticated with Chromatic
    → Using project token '********bb1d'
Retrieving git information
git info: {"commit":"cb53efd74af8892e32d93666b7adb3ae9f93c3b9","committedAt":1619812022000,"committerEmail":"nigel@coda.io","committerName":"Nigel Ellis","branch":"nre-storybook","slug":"coda-hq/coda","isTravisPrBuild":false,"fromCI":true,"ciService":"circleci"}
    → HTTPClient Failed to fetch https://api.github.com/repositories/20423253/pulls?base=nre-storybook&direction=desc&per_page=10&sort=updated&state=closed, got 502/Bad Gateway

✖ Failed to retrieve git information
HTTPClient Failed to fetch https://api.github.com/repositories/20423253/pulls?base=nre-storybook&direction=desc&per_page=10&sort=updated&state=closed, got 502/Bad Gateway
```

**Comment by tmeasday** [comment]
Thanks for the detail @nigel-codaio. This is actually an error coming from our backend (as it makes a request to GitHub). We have a planned improvement to better handle 5xx errors from our upstream providers; we'll bump the priority of that based on this info.

Are you seeing it consitently still or was it a temporary thing? We've not experience consistent 5xx errors from GH in the past, but things change I suppose ;)

**Comment by nigel-codaio** [comment]
@tmeasday I can repro this at will which completely blocks my pilot project to evaluate Chromatic.   Is there any kind of workaround or retry logic I can enable?

```
Please provide us with the above CLI output and the following info:
{
  "timestamp": "2021-05-03T20:56:45.943Z",
  "sessionId": "ccee2405-78b0-4d6e-98af-8902d22b658d",
  "gitVersion": "2.20.1",
  "nodePlatform": "linux",
  "nodeVersion": "14.16.1",
  "packageName": "chromatic",
  "packageVersion": "5.8.0",
  "flags": {
    "interactive": true,
    "projectToken": [
      "************"
    ],
    "junitReport": "./reports/results/storybook-results.xml",
    "ignoreLastBuildOnBranch": "nre-storybook",
    "preserveMissing": true,
    "appCode": []
  },
  "buildScript": "./.storybook/build-storybook.sh",
  "errorType": "GraphQLError",
  "errorMessage": "✖ Failed to retrieve git information"
}
```

**Comment by nigel-codaio** [comment]
FYI -- I nuked the whole Chromatic project and re-added it.  I can still reproduce the issue - some calls work but most of them fail.

Here are some example failing session ids:
- 7e0e778a-d2a4-4212-94b2-ce338197464a
- 3c27f6e8-804d-4cc0-9651-119dd5816913"

I ended up wrapping this with a retry script which is pretty ugly.    Any ETA on when this might get fixed?   Thank you.

**Comment by tmeasday** [comment]
OK, thanks. I can confirm making requests for a list of PRs with a certain `base` branch (even a random string) take >10s and return 502s consistently for your repository. 

Seems like an issue at GH's end for sure.

We'll put out a hotfix so this doesn't block your builds and seek clarification from GitHub.

**Comment by nigel-codaio** [comment]
Thanks @tmeasday -- any ETA on when this might get deployed?   Even with retries, it's consistently failing for me.   For context our main branch currently has over 100 open pull requests.

**Comment by tmeasday** [comment]
Hi @nigel-codaio we are still working on a proper solution to this problem but in the meantime I've created a version of our CLI that doesn't do the PR check[1]. You can use it with `npx -p chromaui/chromatic-cli#disable-squash-merge-check chromatic -t ...`

We'll let you know how we go with GH etc.

**Comment by nigel-codaio** [comment]
Hi @tmeasday -- thanks for the patch build.  The update seems to be working well and I'm now unblocked.    

Thanks.

**Comment by tmeasday** [comment]
I'm guessing you'll also have problem with the PRs screen inside Chromatic! GH are working on the problem at their end.

**Comment by nigel-codaio** [comment]
Hi @tmeasday -- any update on this issue? Thanks.

**Comment by tmeasday** [comment]
Haven't heard back from GH yet @nigel-codaio

**Comment by nigel-codaio** [comment]
Hi @tmeasday any news from GITHUB or anything I can do on my side to mitigate?  I'm still running on the private feature branch (#disable-squash-merge-check).  Concerned that as I start to ramp more usage we're going to be stuck on this branch.  Thanks.

**Comment by tmeasday** [comment]
Sure, I've reopened. I got this back from GitHub yesterday:

> This issue is still being investigated by Engineering and looks like it may require a longer period of investigation to arrive at a potential solution.

I'm not really sure what that means, sorry!

Would you like me to rebase the branch onto latest `master` (i.e. "update" to the latest chromatic CLI?). I'll also discuss adding this as a permanent flag to the CLI.

**Comment by nigel-codaio** [comment]
Hi @tmeasday yes, would be great to have this as a shipped feature until the underlying issue is resolved.  Thanks.

**Comment by tmeasday** [comment]
@nigel-codaio we resolved the underlying issue, can you let us know if it is still a problem for you?

**Comment by nigel-codaio** [comment]
Thanks, I’ll try this out and let you know.

[image: Coda logo] <https://coda.io/>
Nigel Ellis
Engineering: DevOps & SRE | he/him | Coda
***@***.***
What's Coda <https://www.youtube.com/watch?v=oLYZv68M3Kg>? | We're hiring
<https://coda.io/jobs?utm_source=emailsignature>!

**Comment by nigel-codaio** [comment]
I moved to the latest version and no longer see any issues.  Thank you.

**Comment by tmeasday** [comment]
Great! Thanks for getting back to me @nigel-codaio
