### ISSUE TITLE
Mock service worker addon not working on CI/CD github actions

### ISSUE THREAD

**Issue by FulanoD3Tal** [chromaui/chromatic-cli#333]
I am open the issue here because there no way to open one in the wrapper github actions for the cli.

The Mock Service Worker Addon is working perfectly when using the CLI and a mocked storybook is created, but when the build is made by the github actions the build is made but the addon is not working making that build hit the api.

The actions is used as the README of the action said, there was no extra params, the same for the cli

There is something I missed or this kind of configuration is not ready for the action

**Comment by tmeasday** [comment]
Hi @FulanoD3Tal - have you tried building a storybook locally? I'm not quite sure what the situation is but I recall there was some difficulty with service workers and static builds generally. The issue may not be specific to GH actions/Chromatic.

**Comment by FulanoD3Tal** [comment]
Hi again @tmeasday , sorry for the late response

Let me give you the big picture

I'm using the **create-react-app** builder with **Typescript** 

I have **storybook** and **chromatic** dev dependencies

My actual workflow is actually working

I make new UI changes in the application push the changes create the pull request and then use the CLI to make a build

```bash
npx chromatic --token TOKEN
```

When I follow that steps the build is correctly upload and the msw is actually mocking all the request

If I try to use the github actions, the build doesn't mock the request, but I think maybe I have found the problem

The **Mock Service Worker** is actually running in the github actions build. But is seems to not expose env variables, because I can see in the dev console the actually url resquest and look like is not getting the **REACT_APP_API_URL** variable

I actually try to add the variable in the yaml file of the github actions, but it doesn't work

Like I said in the begging, there is actually not problem beside my laziness for skipping the chromatic build step from my workflow

But good news the **Mock Service Worker** addon is actually working in local as in the github actions wrapper

So make the issue should be about make a chromatic build with env variables with github actions

**Comment by tmeasday** [comment]
Sounds like maybe you need to configure GH actions a little bit differently? Are you sure the env var is available there?

**Comment by paulelliott** [comment]
Closed due to age. Please reopen if you feel this is still relevant for you.
