### ISSUE TITLE
Add support for other Addons parameters, not just viewport

### ISSUE THREAD

**Issue by andreibarabas** [chromaui/chromatic-cli#341]
For example, our design system has a dark / light theme, and the colours obviously differ, so we would like to snapshot / UI Test them at scale, to make sure there is no regression.

The api could be something simple, like this

```
const metadata = {
  title: 'Design System/actions/Button',
  component: Button,
  parameters: {
    chromatic: {viewports: [320, 1200], backgrounds: ['light', 'dark']},
  },
};
```

**Comment by tmeasday** [comment]
Thanks for the feature request @andreibarabas. We get asked about this a bit, and it is definitely something we'd like to add.

If you write into support with your feature requests we can make sure we contact you as a feature is rolled out / if we have a beta program, etc.
