### ISSUE TITLE
Set --modern flag based on enabled browsers

### ISSUE THREAD

**Issue by ghengeveld** [chromaui/chromatic-cli#343]
If IE11 is enabled, remove the `--modern` flag if present in the `build-storybook` command when building the Storybook.

If IE11 is not enabled, add the `--modern` flag in case it's not yet present.

Only do this for Storybook versions that support this flag.

**Comment by tmeasday** [comment]
I don't think this is right. The `--modern` flag is not necessarily going to be something you can just switch on and off in any particular storybook without consequence. 

Possibly we could give feedback if the `--modern` flag is switched on an they are using IE though?

**Comment by tmeasday** [comment]
Let's just do this and call it a day: https://github.com/chromaui/chromatic/issues/4904
