### ISSUE TITLE
When using `--skip`, also report github status `UI Review` with `UI Tests`

### ISSUE THREAD

**Issue by nigel-codaio** [chromaui/chromatic-cli#351]
We make use of the `--skip` to skip running Chromatic in our mono-repo when there are no UI changes.   This follows the recommendation in [monorepos#only-run-chromatic-when-changes-occur-in-a-subproject](https://www.chromatic.com/docs/monorepos#only-run-chromatic-when-changes-occur-in-a-subproject).

We'd like to enable github checks to enforce UX validation and review as a required github check on our main branch.   I tried doing that by requiring both "UI Tests" and "UI Review":
![Screen Shot 2021-05-26 at 5 57 16 PM](https://user-images.githubusercontent.com/12142109/119749382-db89d500-be4b-11eb-8f19-35a0ae1613ea.png)

Unfortunately when skipped, Chromatic only reports `UI Tests`.   The PR will wait endlessly for `UI Review` which is never reported.

**Ask:** when using `--skip` report both `UI Review` and `UI Tests` with status "_Skipped build._".

**Comment by tmeasday** [comment]
Thanks @nigel-codaio. We've created a ticket on our backend to add this.

**Comment by tmeasday** [comment]
Hey @nigel-codaio -- this was just merged, FYI

**Comment by radfahrer** [comment]
@tmeasday any timeline on when this fix will go out, or if we need to change anything to get it to work? We are still running into this issue.

**Comment by tmeasday** [comment]
@radfahrer By merged above I meant released. What behaviour are you seeing? Do you have an example you can share (may be better to write into support)

**Comment by gbettencourt** [comment]
@tmeasday we're passing skip=true using the chromatic GH action (looks like it's using cli v 6.2.0), we get back a "UI Tests" status but no "UI Review":
![image](https://user-images.githubusercontent.com/33299088/145467760-a55a83bf-28aa-4464-82d9-34542b8e6287.png)

**Comment by tmeasday** [comment]
@gbettencourt can you send me a commit sha and the app id involved here? You can use intercom chat to send it privately if you like.

**Comment by gbettencourt** [comment]
> @gbettencourt can you send me a commit sha and the app id involved here? You can use intercom chat to send it privately if you like.

@tmeasday  Sent in intercom

**Comment by tmeasday** [comment]
OK! Sorry for the delays here folks, if you were following along it was kind of a journey :) But I think we got there in the end!

**Comment by radfahrer** [comment]
Thank you @tmeasday!
