### ISSUE TITLE
CLI runs slowly as it gets stuck in retrieving git information + authenticating with chromatic

### ISSUE THREAD

**Issue by yannbf** [chromaui/chromatic-cli#356]
In version `5.8.3`, the when running `chromatic --project-token $CHROMATIC_PROJECT_TOKEN --exit-zero-on-changes`, it somehow gets stuck in the "Retrieved git information + Authenticated with Chromatic" step, it happens about 30-40 times and then it proceeds normally:

![image](https://user-images.githubusercontent.com/1671563/120241549-43cd2200-c263-11eb-9cf2-cd672ba887b4.png)

**Comment by tmeasday** [comment]
@yannbf do you have a reproduction we can look at? I don't think this is a widespread issue.. does it occur reguarly for you?

**Comment by ghengeveld** [comment]
@yannbf FYI you can omit the `--project-token` flag. It looks for `CHROMATIC_PROJECT_TOKEN` automatically.
If you can reproduce this issue, can you maybe set `LOG_LEVEL=debug` and share what you find?

**Comment by yannbf** [comment]
> @yannbf FYI you can omit the `--project-token` flag. It looks for `CHROMATIC_PROJECT_TOKEN` automatically.
> If you can reproduce this issue, can you maybe set `LOG_LEVEL=debug` and share what you find?

Hey @ghengeveld good tip! I haven't had this issue for quite some time. If I happen to have I'll definitely let you know.

Thanks guys!
