### ISSUE TITLE
Handle absolute paths in webpack stats

### ISSUE THREAD

**Issue by tmeasday** [chromaui/chromatic-cli#360]
(I think) when the stories files are outside of the main webpack directory, webpack ends up putting full absolute paths into the stats file. Our code currently looks for matching relative filenames (e.g. `'./src/components/Button.js'`).

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199921881886840/1200451030764652) by [Unito](https://www.unito.io)

**Comment by ghengeveld** [comment]
Done in https://github.com/chromaui/chromatic-cli/pull/366

**Comment by Aldredcz** [comment]
Great! 🎉  I am waiting for this fix, any idea when it's gonna be published to npm? 🙏🙂

**Comment by tmeasday** [comment]
@Aldredcz it is out in 5.9.2

**Comment by ghengeveld** [comment]
Reopening, because #366 only addressed a mismatch between the git root and webpack root, not absolute paths.
