### ISSUE TITLE
Feature request: Read project token from .env.local

### ISSUE THREAD

**Issue by bodograumann** [chromaui/chromatic-cli#361]
We don’t want to commit any secrets to the git repo, so defining the chromatic project token in the `.env` file or directly on a script in `package.json` is not an option.
Still it would be nice to not have to explicitely give it on the command line every time we want to run chromatic.
Usually this is done by using the `.env.local` file. It is `.gitignore`d and overrides any settigns in `.env`.

**Comment by ghengeveld** [comment]
That's a fair use case. @tmeasday Do you think this is a reasonable solution?

**Comment by tmeasday** [comment]
Don't take this the wrong way @bodograumann, I have no opinions ( 😄 ), but I'll not, from the [`dotenv` docs](https://www.npmjs.com/package/dotenv#faq):

> > Should I commit my .env file?
> No. We *strongly* recommend against committing your .env file to version control. 

> > Should I have multiple .env files?
> No. We *strongly* recommend against having a "main" .env file and an "environment" .env file like .env.test.

Emphasis theirs.

So I guess my feeling was that you should probably need to opt into something non-standard like this. We have this ticket for that: https://github.com/chromaui/chromatic-cli/issues/352

**Comment by bodograumann** [comment]
Ah, I see. Then this is definitely a duplicate.

Personally I don’t have an opinion either. Similar to nextjs, this is just how vue-cli integrates dotenv. :laughing:
