### ISSUE TITLE
Allow running in a non-git environment by passing a generated git history

### ISSUE THREAD

**Issue by tmeasday** [chromaui/chromatic-cli#362]
For security purposes, some customers do not want to run Chromatic in a full git repository.

One possibility is for those customers to run a simple git command to generate a history, perhaps `git log --format="%H %P %ct" -n $N` and to provide the output to our CLI.

At that point there are two potential ways we could implement our [`getParentCommits`](https://github.com/chromaui/chromatic-cli/blob/d9026f4178c3837ea6defbceac58cbe4139a0fb9/bin/git/git.js#L247) algorithm:

1. Try and reproduce the repository format using the input files (by creating git commits), and then running the existing code. This will be tricky for two reasons:
   (a) it might be tricky to create the tree structure, and 
   (b) the commit hashes wouldn't match so we'd have to tweak the code to take this into account.

2. Reproduce the `git rev-list` behaviour we need via iterating over the data we have. This will be a challenge but should be fundamentally possible.

**Comment by adikari** [comment]
I am using Buildkite for CI and this will be useful.

**Comment by paulelliott** [comment]
Closed due to age. Please reopen if you feel this is still relevant for you.
