### ISSUE TITLE
Error: Failed to publish your built Storybook

### ISSUE THREAD

**Issue by Grienauer** [chromaui/chromatic-cli#364]
I wanted to try chromatic.

after running "npm install --save-dev chromatic" (nor errors) I ran

```
npx chromatic --project-token=XXXXXXXX
```
XXXXXXX was my token from the setup page info.

I get always the error:
```
Error: ✖ Failed to publish your built Storybook
HTTPClient failed to fetch https://index.chromatic.com/graphql, got 503/Service Unavailable
```

but on the status page everything looks good/running.
also the URL fetch URL seems to work…

any clue?
thx!

**Comment by tmeasday** [comment]
Hi @Grienauer -- could you please contact Chromatic support (support @ chromatic.com or using the chat box) and provide the full log of the error?

Usually these issues are triggered by something unusual about your Storybook, but we need more information to see what.
