### ISSUE TITLE
Look further back for git changes if the baseline build is not in the git repo (`--only-changed`)

### ISSUE THREAD

**Issue by tmeasday** [chromaui/chromatic-cli#368]
There are a variety of reasons why a commit can no longer exist in a repository.

Currently when this happens, we bail out of `--only-changed` as we cannot calculate git differences.

However, we *could* look further back than the baseline for the "build to copy". It introduces some extra complexities and work in our backend (we no longer know the diff status of the copied snapshots because they don't come from the baseline, so we would at least have to diff every story).

**Comment by paulelliott** [comment]
Closed due to age. Please reopen if you feel this is still relevant for you.

**Comment by tmeasday** [comment]
We actually ended up implementing this ("replacement builds")
