### ISSUE TITLE
CLI logs no longer being sent to loggly

### ISSUE THREAD

**Issue by tmeasday** [chromaui/chromatic-cli#369]
Let's consider proxying them via the index.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199921881886840/1200545794681760) by [Unito](https://www.unito.io)

**Comment by codykaup** [comment]
Removed in https://github.com/chromaui/chromatic-cli/pull/819

We decided to no longer write these logs externally for the time being!
