### ISSUE TITLE
Skipped tests do not have a viewport

### ISSUE THREAD

**Issue by tmeasday** [chromaui/chromatic-cli#372]
```
{
  test(id:"5fe0f4007e399a0021d0584c") {
    status
    result
    # parameters {
    #   viewport
    # }
  }
}
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199921881886840/1200526166655251) by [Unito](https://www.unito.io)

**Comment by ghengeveld** [comment]
Backend issue. Closing.
