### ISSUE TITLE
Include URLs in junit output

### ISSUE THREAD

**Issue by tmeasday** [chromaui/chromatic-cli#373]
![image](https://user-images.githubusercontent.com/132554/123533789-a975d680-d75b-11eb-8572-66b59b2a5ee8.png)

Would be handly if you could at least cut and paste this URL

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199921881886840/1200545798860745) by [Unito](https://www.unito.io)

**Comment by paulelliott** [comment]
Closed due to age. Please reopen if you feel this is still relevant for you.
