### ISSUE TITLE
Please document DISABLE_LOGGING

### ISSUE THREAD

**Issue by dan-kez** [chromaui/chromatic-cli#377]
My team and I are in the process of evaluating chromatic for use in our CI pipeline. We received an escalation from our security team about the logging calls to loggly that chromatic is making.

Please make telemetry opt in or document the ability to opt out in your help message.

**Comment by tmeasday** [comment]
Thanks @dan-kez.

Out of interest, is the issue the fact that we are sending telemetry or that we are connecting to a third party to do so?

We plan to proxy this logging telemetry via our own servers in the near future; would this ease the concerns or would opt-ing out of logging still be important for your security team?

**Comment by codykaup** [comment]
External logging was removed via [#819](https://github.com/chromaui/chromatic-cli/pull/819)!
