### ISSUE TITLE
ReferenceError: window is not defined (isChromatic SSR)

### ISSUE THREAD

**Issue by AndrewLeedham** [chromaui/chromatic-cli#379]
When using `isChromatic` in SSR it throws `ReferenceError: window is not defined`. I would expect it to just return `false` if we are not in a browser context. Seems like a simple `typeof window !== 'undefined'` would resolve the issue.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199921881886840/1200585399631923) by [Unito](https://www.unito.io)

**Comment by zol** [comment]
Thanks @AndrewLeedham! @ghengeveld we should merge and release this asap cc @amartinez62
