### ISSUE TITLE
Add the opposite of `--externals` -- files that should be ignored no matter what

### ISSUE THREAD

**Issue by tmeasday** [chromaui/chromatic-cli#383]
For instance a `package.json` in a non-frontend project in a monorepo that isn't using yarn workspaces, etc.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199921881886840/1200639784566739) by [Unito](https://www.unito.io)

**Comment by paulelliott** [comment]
Closed due to age. Please reopen if you feel this is still relevant for you.

**Comment by tmeasday** [comment]
This is implemented via the `--untraced` flag
