### ISSUE TITLE
Stable release tag

### ISSUE THREAD

**Issue by brainrepo** [chromaui/chromatic-cli#386]
Actually, the latest version is a canary version:
It is possible to tag the last stable version 5.9.2 as stable?

thank you

**Comment by memark** [comment]
Yes, this can't be right!

![image](https://user-images.githubusercontent.com/318504/128901985-21688830-c787-41ec-a815-f1a18886638c.png)

Do we really want the world to use this version?

**Comment by ghengeveld** [comment]
Honest mistake on my part. `npm publish` defaults to the `latest` tag, even when the version you're releasing is a prerelease. All it takes is to forget the `--tag` flag. Obviously we should be using `auto` like we are in other places.

I've fixed `latest` to point to `5.9.2` again. Will probably promote the latest canary soon.

**Comment by brainrepo** [comment]
@ghengeveld ty
