### ISSUE TITLE
Chromatic Builds Failing: ERR! EEXIST: file already exists

### ISSUE THREAD

**Issue by brad-mccormick** [chromaui/chromatic-cli#387]
I'm suddenly running into the following Chromatic build issue and not sure the source. Running `npm run --silent build-storybook -- --output-dir /tmp/chromatic--1618-7tuQgtSXKtwX` locally works fine. It only fails in my GitHub action that uses `chromaui/action@v1`

```
info @storybook/web-components v6.3.4
info 
info => Cleaning outputDir: /tmp/chromatic--1618-7tuQgtSXKtwX
info => Copying static files: ./.storybook/public => ./
info => Copying static files: ./node_modules/@design-system/core/icons => ./icons
ERR! EEXIST: file already exists, mkdir '/tmp/chromatic--1618-7tuQgtSXKtwX/icons'
    → Command failed: npm run --silent build-storybook -- --output-dir /tmp/chromatic--1618-7tuQgtSXKtwX
```

**Comment by coderkevin** [comment]
Hi Brad, it looks like your message fell through the cracks, as we typically field support requests through our live chat application on our site. See here: https://www.chromatic.com/docs/support#support

Anyway, are you still having issues here? Or did you get it figured out?

**Comment by brad-mccormick** [comment]
Hi Kevin,

It just started working again at one point and we're in good shape now. Not
really sure what happened. Maybe a GitHub outage? Thanks for following up
and I'll be sure to channel support needs there going forward.

Thanks!
Brad

**Comment by coderkevin** [comment]
Glad you got it figured out! Feel free to reach out to support if you need further help. Thanks!
