### ISSUE TITLE
Use of `--auto-accept-changes` and squash-merges on `main` branches

### ISSUE THREAD

**Issue by nigel-codaio** [chromaui/chromatic-cli#389]
Hi,

We're currently using Chromatic with flags `--auto-accept-changes` on our main branch per recommendation in https://www.chromatic.com/docs/custom-ci-provider#squashrebase-merge-and-the-main-branch.  

Is there any planned support to remove the need for this flag on main?   For example, I can imagine a case where two pull-requests make UX changes to a common shared file:
1. Each PR independently reviews the UX changes caused by their changes and approves them.  At this point, neither reviewer has seen the others change
2. Each PR merges
3. Final main branch runs with merged changes from PR1 and PR2.   This ends up generating UX changes that are different than those seen on PR1 or PR2.   Ideally, this would cause test failure and need human review.

Thanks,
Nigel.

**Comment by tmeasday** [comment]
Hi @nigel-codaio -- it shouldn't be necessary to add this flag now we can detect squash-merged PRs on your `main` branch.

If we cannot auto-detect them, then unfortunately this technique is the only reliable way forward. However hopefully we can?

**Comment by tmeasday** [comment]
Hi @nigel-codaio,

It may make more sense to talk this conversation to support (support@chromatic.com) or chat box on the website.

Can I ask when the PR was merged vs the build #9040 ran?

Was the commit https://github.com/coda/coda/commit/02762a6499ff6dfa3730933534eff81f586ae683 the squash merge commit for the PR?

In your case, our code pulls down the last 100 most recently updated PRs, then searches for one that has the "merge commit" being equal to the commit in question (02762a6 etc).

**Comment by nigel-codaio** [comment]
Hi Tom,

The PR was merged on 2021-08-16-T12:51:51-0700:
```
commit 02762a6499ff6dfa3730933534eff81f586ae683
Date:   Mon Aug 16 12:51:51 2021 -0700
    [storybook] Exclude global styles that prevent scroll, instead of pulling in global styles piecemeal (#60174)
```

`02762a64` was the merge-commit for the PR, and `41bc909` was the commit SHA for the PR branch 
`ag-storybook-globalstyles`.   Looks like the Storybook run for that PR ran on Friday, 8/13 (3 days prior).    

We run a large mono-repro that's quite active.   Github weekly stats for the repo (excluding merges):
- 247 commits to main and 505 commits to other branches
- 323 active PRs 

I'm wondering if the issue is that given we have so many active PRs, was it possible you failed to find the merge commit SHA when looking through the least 100 active PRs?    How are you querying GH for the PRs?  Are you using the REST API or graphQL?  Is there anyway to verify that in your logs?    Happy to open this as a ticket with support too if you'd prefer that.

Thanks,
Nigel.

**Comment by tmeasday** [comment]
Hi Nigel.

So what we currently do to detect a squash merge into commit `C` on branch `B`:

1. First try and fetch the last 10 recently updated merged PRs that were merged into branch `B`.
2. If that call fails, fall back to fetching the last 100 most recently updated PRs (open or closed on any branch).

Once we have a list, we search through it for one with `merge_commit_sha === C`

We use the v3 `/pulls` API for both requests.

The reason we do two steps, is we have seen for yourselves (and others) that the first API call with `state=closed&base=$B` will fail consistently for large repos with a very large number of PRs (or at least I think that's the reason). We have a long standing open ticket with GH support about this but unfortunately it hasn't really progressed, despite some attempts at our end to get them to work on it :/

In theory, if the PR was just merged, and Chromatic runs right away or near to it, it should be listed in the 100 most recently updated PRs, even in a *very* active project, so the call in (2) should be fine. In practice that doesn't seem to be happening.

It is a little bit hard to investigate as by the time you tell me about it the PR is going to be much further down the list of active PRs. I'll go ahead an add some logging in our fallback case and see if I can glean any more information, but if you want to try something at your end, you could try making the API call with a personal access token that has sufficient permission. The call is:

```
curl -v https://api.github.com/repositories/${$REPO_ID}/pulls?sort=sort&direction=desc&per_page=100 -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $TOKEN"
```

It would be interesting to see what that call says immediate after merging a PR, or approximately however long after a PR is merged when the chromatic CI job runs.

The `$REPO_ID` is the v3 "database" id of the repository, a number. I am not sure of the best way to get it, I can look it up for you if you want (send me a support message I guess).

**Comment by nigel-codaio** [comment]
Thanks, I'll followup.

**Comment by nigel-codaio** [comment]
Hi Tom, I added some logging on our side and have sent email to support with more details.  Thanks.

I'm using `https://api.github.com/repos/coda/coda/pulls?state=all&sort=updated&direction=desc&per_page=100` -- this seems to find the update PR in the first few entries.

**Comment by nigel-codaio** [comment]
Had a followup from @tmeasday -- he's confident the issue has been isolated and he's applied a fix.   I've removed the use of --auto-accept-changes but left the GH API logs in place on our mainline branch.   I'm going to keep the logging in place for a week or so in case we see the issue again.  

I think we can close this issue -- I'll report back to support if I see the issue again.  Thank you!

**Comment by tmeasday** [comment]
Thanks again @nigel-codaio
