### ISSUE TITLE
CLI throws an error on a transitive dependency with node:lts (v14.17.6)

### ISSUE THREAD

**Issue by kairos2109** [chromaui/chromatic-cli#400]
## Description
CLI throws an error on a transitive dependency with the current [node:lts (v14.17.6)](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#2021-08-31-version-14176-fermium-lts-mylesborins) released on 2021-08-31. It used to work with previous versions of node.

![chromatic](https://user-images.githubusercontent.com/6153682/133683283-0be2bf7f-77c4-4f98-a535-77202759ffbf.png)

Chromatic version: 
`
"chromatic": "^5.9.2"
`

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199921881886840/1201035781111173) by [Unito](https://www.unito.io)

**Comment by smithambera** [comment]
https://app.intercom.com/a/apps/zj7sn9j1/inbox/inbox/unassigned/conversations/27253960266

**Comment by ndelangen** [comment]
going to tackle this here:
https://github.com/chromaui/chromatic-cli/pull/393

**Comment by ndelangen** [comment]
This should be fixed in `v6.0.2`, which I released just now.
