### ISSUE TITLE
[TurboSnap] Add a flag to skip builds with the same commit, rather than rebuild entirely.

### ISSUE THREAD

**Issue by tmeasday** [chromaui/chromatic-cli#402]
Some use cases lead to repeated builds on the same commit for CI-related reasons, rather than user-initiated rebuilds.

It is useful in such cases to treat the build as a skipped build rather than do a full rebuild.

**Comment by tmeasday** [comment]
@ghengeveld have we already sorted this out?

**Comment by ghengeveld** [comment]
I don't think so

**Comment by thafryer** [comment]
@tmeasday Closing this!  I think we already have this behavior without needing to add a flag. Feel free to re-open if so!
