### ISSUE TITLE
Incompatible options: --storybook-build-dir (-d), --only-changed

### ISSUE THREAD

**Issue by anilanar** [chromaui/chromatic-cli#403]
We get this error from the Github action.

Sounds like a bug to me, why would those options be incompatible?

**Comment by adam-h** [comment]
This is happening for us to, only in the last couple of days. May be related to 5.10.0

**Comment by adam-h** [comment]
Looks like this was changed in 5.10.0 via https://github.com/chromaui/chromatic-cli/pull/392

We had this setup and working, per the docs for [static storybook builds](https://www.chromatic.com/docs/turbosnap.html#static-storybook-builds). Is this new requirement intentional?

**Comment by mchill** [comment]
> Even though a prebuilt Storybook might contain a `preview-stats.json` (by passing the `--webpack-stats-json` flag to build-storybook), file paths in that stats file might not "line up" with the current working directory wherein `chromatic` runs

I'm guessing a pretty common use case for using the two arguments together is in a CI environment, where the Storybook documentation is built in an earlier stage, and Chromatic uses that artifact in a later stage. At least, that's what our team is doing. Having Chromatic build the documentation again would make the pipeline run longer than necessary.

In that scenario, absolute file paths shouldn't really be a problem. Many CI environments keep the working directory consistent across pipelines.

**Comment by anilanar** [comment]
I'm actually fine with running storybook build twice and I'd say fixing this should have less priority than existing more important TurboSnap issues that are more annoying than a ci job taking a little longer.

**Comment by tmeasday** [comment]
@ghengeveld can we just pass the path information as a separate flag and require you do that if you want to use both `-d` and `--only-changed`?

**Comment by ghengeveld** [comment]
To confirm, we are going to revert that decision to not support the combination of `-d` and `--only-changed`. It's not a trivial change though.

**Comment by tmeasday** [comment]
To do this we need to add a flag to allow the SB working directory to be different from the git base dir. 

One worry is if folks forget to set it they may not realise. Maybe we can add a check to see if a file in the webpack stats file cannot be found relative to the git dir and warn or even error if not.
