### ISSUE TITLE
GitHub action output `storybookUrl` includes iframe.html

### ISSUE THREAD

**Issue by jgoz** [chromaui/chromatic-cli#409]
I'm setting up a PR workflow that publishes to Chromatic and then adds a Deployment using the `storybookUrl` output. But it looks like as of 5.10.0, that URL includes `/iframe.html`, which leads to the isolated view with no parameters.

IMO, it should just point to the root URL for the storybook deployment.

**Comment by tmeasday** [comment]
That makes sense to me. @ghengeveld does that make sense to you?

**Comment by ndelangen** [comment]
It makes sense to me, should be fairly straight forward to strip it off in the CLI.

**Comment by beckerei** [comment]
What's the current status of this? We also stumbled upon this.

**Comment by ndelangen** [comment]
I'll try and get this done, this cycle! Thanks for the ping!
