### ISSUE TITLE
Git <2.x not supported

### ISSUE THREAD

**Issue by JessBergs** [chromaui/chromatic-cli#41]
Chromatic fails when we run it with git version 1.7.1
This is due to an equal sign missing in the `--since` flag in the `git rev-list HEAD` command in https://github.com/chromaui/chromatic-cli/blob/42b836ad95ef5705ebbe0039b7afa00a588e03a2/bin/git/git.js#L117
The missing equal sign in only supported in versions >2.x.

We'd therefore need the command to read  `git rev-list HEAD ${firstCommittedAtSeconds ? `--since**=**${firstCommittedAtSeconds}` : ''}`

Could this be changed?

**Comment by tmeasday** [comment]
I guess it could @JessBergs -- not sure if there'd be other problems with git v1, given we haven't tested it with it, but it's worth a go. 

Perhaps you could send a PR?

**Comment by JessicaBergsBBC** [comment]
Hi @tmeasday , tried that but seems you need permissions set to push your PR branch.

**Comment by tmeasday** [comment]
Hi @JessicaBergsBBC - perhaps you need to fork this repository?

**Comment by thafryer** [comment]
Hi @jess-bergs! I'm closing this issue. I believe most people are now on a version of Git > 2.x. If you would still like to make a contribution to support Git <2.x feel free to fork this repository and submit a PR. Thanks!
