### ISSUE TITLE
Errors are ignored

### ISSUE THREAD

**Issue by bodograumann** [chromaui/chromatic-cli#410]
I just upgraded to chromatic-cli to 5.10.1.
My latest run did contain changes (which are shown in the web interface).
But the chromatic-cli command did not fail with an exit code.

Output:

```
> chromatic -d storybook-static


Chromatic CLI v5.10.1
https://www.chromatic.com/docs/cli

Authenticating with Chromatic
    → Connecting to https://index.chromatic.com
Authenticated with Chromatic
    → Using project token '********a973'
Retrieving git information
Retrieved git information
    → Commit '128e56e' on branch 'feature-2150'; found 1 parent commit
Collecting Storybook metadata
Collected Storybook metadata
    → Storybook v^6.3.7 for Vue3; supported addons found: Actions, Docs, Links
Publish your built Storybook
    → Validating Storybook files
Publishing your built Storybook
    → Retrieving target location
    → Starting publish
Publish complete in 5 seconds
    → View your Storybook at https://60a50dc3c807cc0039de4063-mnmusfunjp.chromatic.com
Verifying your Storybook
    → This may take a few minutes
Started build 206
    → View build details at https://www.chromatic.com/build?appId=60a50dc3c807cc0039de4063&number=206
Running 124 tests
    → This may take a few minutes
ℹ Speed up Continuous Integration
Your project is linked to Bitbucket so Chromatic will report results there.
This means you can pass the --exit-once-uploaded flag to skip waiting for build results.
Read more here: https://www.chromatic.com/docs/cli#chromatic-options
```

**Comment by tmeasday** [comment]
Hi @bodograumann it looks like maybe the CLI never exited there? I have just noticed a similar thing happen in an internal job here and am looking into it, although it is a difficult one to debug.

**Comment by bodograumann** [comment]
I‘m not sure what you mean by that. We are using chromatic as check in the CI like this for some time now and it has reported changes correctly before.
The only change I made, was to update chromatic-cli from 5.9.2 to 5.10.1 and remove the `no_proxy=""` workaround wrt. #359.

**Comment by tmeasday** [comment]
@bodograumann I guess what I mean is the logs you posted above don't look complete. If the build completed and the CLI thought it succeeded it should have logged a message saying so.

Did the process exit and the CI job complete successfully? In a similar case I saw internally the CI job timed out after 10 minutes.

**Comment by bodograumann** [comment]
Yes, the process exited with 0 and the pipeline job thus succeeded. There was some log from the azure devops task runner around it, which I did not post. I think it didn’t have any usefull information, but I can go back and have another look on monday.

**Comment by tmeasday** [comment]
@bodograumann was this just a once off, or is it happening regularly? It seems very unusual, I am not quite sure what to make of it.

**Comment by bodograumann** [comment]
We don’t have changes that frequently, so it is a little hard to say.
From what I have seen until now it seems to be only the one occurence. :shrug: 

Will close the issue until I have more data and can maybe reproduce it.
