### ISSUE TITLE
Does chromatic capture responsive UI changes of an component  

### ISSUE THREAD

**Issue by Mrinmoy13** [chromaui/chromatic-cli#413]
I am currently trying to set up a design ecosystem that consists of storybook and chromatic. Using this setup I wish to completely govern my UI components. however, the adaptive/responsive changes of a component aren't being captured through chromatic UI snapshot (difference from the previous build). Does chromatic as a visual regression tests tool supports adaptive/responsive changes of a component (Since we have components that do change its UI behavior on layout changes), apparently i am not able to view or capture those sets of UI changes through chromatic, a timely help/ support will be much appreciated.     

1. The first screenshot refers to a Tab component that is non-responsive on a mobile screen and its content overflows with horizontal scroll. 
![tabComponentNonAdaptive](https://user-images.githubusercontent.com/90275825/134764491-29f8c24c-d56c-459d-b1e6-48df15855715.png)

2. The second screenshot refers to the same Tab component which is responsive on a mobile screen and its overflowing tabs gets added on a dropdown. 
![tabComponentAdaptive](https://user-images.githubusercontent.com/90275825/134764499-c9dcf1a5-b5aa-4ba5-897d-f515e1172592.png)

My requirement is to capture the UI difference that's has taken place from a non-responsive component to responsive components.

**Comment by ndelangen** [comment]
Hello @Mrinmoy13 chromatic supports running your story in multiple viewports! You can read about it here:
https://www.chromatic.com/docs/viewports.html#viewports-for-responsive-uis

Does this answer your question?

**Comment by Mrinmoy13** [comment]
> Hello @Mrinmoy13 chromatic supports running your story in multiple viewports! You can read about it here: https://www.chromatic.com/docs/viewports.html#viewports-for-responsive-uis
> 
> Does this answer your question?

Yes, @ndelangen I do agree with you in this regard and I have been able to successfully configure multiple viewports views as well. But the concern which I have is, does the responsive changes of component is being captured among the builds, for example, I have generated build 1 which is a non-responsive Tab component  (Tab will be overflowing horizontally in mobile view), and build 2 is with responsive Tab features (Overflowing Tab will be under dropdown "..." ). Now, this is a visual change that I am expecting to be captured when I am generating a build from build 1 to build 2. But it's not capturing any UI differences.

**Comment by ndelangen** [comment]
Do you have a link to these builds?

**Comment by Mrinmoy13** [comment]
Yes @ndelangen, the build which I generated last week wasn't capturing the UI changes. Build no. 45 has Tab component without responsive behavior whereas build no.46 has responsive/adaptive behavior added to it. you can identify the changes in the storybook. I subsequently cross verified with multiple such builds, but the UI difference wasn't capturing. 

https://www.chromatic.com/build?appId=6131267034611f003a0f246e&number=45
https://www.chromatic.com/build?appId=6131267034611f003a0f246e&number=46


However, today when I regenerated the build today I am able to identify the UI difference, and it's being captured between build no. 53 and 54, now the question I have here, is it consistently capturing the difference, or is it just a miss from my end to identify the UI difference in the earlier builds. Kindly let me know your toughs towards the same.   

https://www.chromatic.com/build?appId=6131267034611f003a0f246e&number=53
https://www.chromatic.com/build?appId=6131267034611f003a0f246e&number=54


![image](https://user-images.githubusercontent.com/90275825/135315621-8a6a0e63-3599-4c21-8277-1238cff72d86.png)

**Comment by Mrinmoy13** [comment]
Yes @ndelangen, the build which I generated last week wasn't capturing the UI changes. Build no. 45 has Tab component without responsive behavior whereas build no.46 has responsive/adaptive behavior added to it. you can identify the changes in the storybook. I subsequently cross verified with multiple such builds, but the UI difference wasn't capturing. 

https://www.chromatic.com/build?appId=6131267034611f003a0f246e&number=45
https://www.chromatic.com/build?appId=6131267034611f003a0f246e&number=46


However, today when I regenerated the build today I am able to identify the UI difference, and it's being captured between build no. 53 and 54, now the question I have here, is it consistently capturing the difference, or is it just a miss from my end to identify the UI difference in the earlier builds. Kindly let me know your toughs towards the same.   

https://www.chromatic.com/build?appId=6131267034611f003a0f246e&number=53
https://www.chromatic.com/build?appId=6131267034611f003a0f246e&number=54


![image](https://user-images.githubusercontent.com/90275825/135315621-8a6a0e63-3599-4c21-8277-1238cff72d86.png)

**Comment by ndelangen** [comment]
@Mrinmoy13 It may be your components re-renders a few times, before falling into the stable state.. Chromatic might not be waiting long enough. Could you try adding a delay?
