### ISSUE TITLE
GitHub action failing with "Storybook package not installed"

### ISSUE THREAD

**Issue by PilotConway** [chromaui/chromatic-cli#416]
With the release of Chromatic CLI v6.0.0 all our GitHub actions using the `chromaui/action@v1` are now failing with the following error: 

```
Chromatic CLI v6.0.0
https://www.chromatic.com/docs/cli

Authenticating with Chromatic
    → Connecting to https://index.chromatic.com
Could not retrieve package info from registry; skipping update check
Authenticated with Chromatic
    → Using project token '*'
Retrieving git information
Retrieved git information
    → Commit '*******' on branch 'main'; found 2 parent commits
Collecting Storybook metadata
    → ✖ Storybook package not installed
Could not find @storybook/react in node_modules.
Most likely, you forgot to run npm install or yarn before running Chromatic.

✖ Failed to collect Storybook metadata
✖ Storybook package not installed
Could not find @storybook/react in node_modules.
Most likely, you forgot to run npm install or yarn before running Chromatic.
→ View the full stacktrace below

If you need help, please chat with us at https://www.chromatic.com/docs/cli for the fastest response.
You can also email the team at support@chromatic.com if chat is not an option.

Please provide us with the above CLI output and the following info:
{
  "timestamp": "2021-09-30T13:35:28.504Z",
  "sessionId": "102360cb-5060-471a-82bd-1600fb5a5512",
  "gitVersion": "2.33.0",
  "nodePlatform": "linux",
  "nodeVersion": "12.13.1",
  "packageName": "chromatic",
  "packageVersion": "6.0.0",
  "flags": {
    "projectToken": "***",
    "workingDir": "packages/console-frontend",
    "fromCI": true,
    "interactive": false,
    "exitZeroOnChanges": true,
    "exitOnceUploaded": true,
    "allowConsoleErrors": false
  },
  "buildScript": "build-storybook -s public",
  "errorType": "Error",
  "errorMessage": "✖ Failed to collect Storybook metadata"
}
```

This is happening across all our builds now with no code changes to the action/package.json/or lock file in our code so appears to be completely isolated to the action itself.

**Comment by tobilen** [comment]
For whatever its worth, there is this line in the code https://github.com/chromaui/chromatic-cli/pull/393/commits/8208d097f1960ac781ab9b2d23a04897256e09c8#diff-f850740b616025cc44b71bd0b7fcf64cc54845bad9a10c117de701156c454a92R7

When i try to run that with yarn 3, i get the error `Couldn't find a script named "list"`:
![image](https://user-images.githubusercontent.com/8217788/135476925-f56cb4ba-e592-4a29-adcc-8ca830333d9a.png)

**Comment by gisouzap** [comment]
I'm facing the same problem

**Comment by chris-h-barrett** [comment]
I'm also seeing this. We are using yarn 2 with zero install.

**Comment by ndelangen** [comment]
I'm investigating this, does anyone have a public repository where this occurs?

**Comment by Breadkenty** [comment]
Seems like something happened on the recent release, try using the previous version, `npx chromatic@5.10.1` worked for us.

**Comment by PilotConway** [comment]
@ndelangen Our projects are all private, but I just tried to add the chromatic workflow to an old public repo I had and it worked. I wonder if the issue likes in the fact that our repo is a monorepo, and we are using the working dir option on the workflow.

**Comment by ndelangen** [comment]
Not every customer reporting this seems to be using a monorepo.

I've tested the v6 and the action on multiple repositories before publishing, I'm really sorry this is causing a disruption.

**Comment by IanVS** [comment]
Based on the code that @tobilen shared, is it possible that this fails on non-yarn projects?  I'm using npm, but do have yarn installed.  When I run `yarn list --pattern @storybook/ --json`, I get:

```
{"type":"error","data":"No lockfile in this directory. Run `yarn install` to generate one."}
{"type":"info","data":"Visit \u001b[1mhttps://yarnpkg.com/en/docs/cli/list\u001b[22m for documentation about this command."}
```

Pinning to an older commit using chromatic 5.10.0 seems to be a valid workaround for now. 

```
uses: chromaui/action@4d0a55dcd76b4025e163af7a6530f17b82923a54
```

**Comment by PilotConway** [comment]
We are using yarn 1.22 and if I run `yarn list --pattern @storybook/ --json` I don't see any errors and if I grep for `@storybook` from that output I get this: 

```
{"type":"tree","data":{"type":"list","trees":[{"name":"@storybook/addon-actions@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/addon-essentials@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/addon-links@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/core@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/node-logger@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/preset-create-react-app@3.2.0","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/react@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/addon-backgrounds@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/addon-controls@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/addon-docs@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/addon-measure@2.0.0","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/addon-toolbars@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/addon-viewport@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/addons@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/api@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/client-api@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/client-logger@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/components@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/core-client@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/core-common@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/core-events@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/core-server@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/csf@0.0.1","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/react-docgen-typescript-plugin@1.0.2-canary.253f8c1.0","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/router@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/semver@7.3.2","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/theming@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/builder-webpack4@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/channel-postmessage@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/channels@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/csf-tools@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/manager-webpack4@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/postinstall@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/source-loader@6.3.8","children":[],"hint":null,"color":null,"depth":0},{"name":"@storybook/ui@6.3.8","children":[],"hint":null,"color":null,"depth":0}]}}
```

**Comment by ndelangen** [comment]
I've reverted the new version, your system should start functioning again without any changes on your end.We'll be investigating what happened on our end, thank you for your patience and understanding.

@PilotConway I truly appreciate any info you could provide 🙏

> Based on the code that @tobilen shared, is it possible that this fails on non-yarn projects? I'm using npm, but do have yarn installed. When I run `yarn list --pattern @storybook/ --json`, I get:
> 
> ```
> {"type":"error","data":"No lockfile in this directory. Run `yarn install` to generate one."}
> {"type":"info","data":"Visit \u001b[1mhttps://yarnpkg.com/en/docs/cli/list\u001b[22m for documentation about this command."}
> ```

Hmm, that's interesting...

**Comment by PilotConway** [comment]
Here's a slightly edited version of our workflow file in case there's something helpful in there: 
https://gist.github.com/PilotConway/63576b1be32041b87fb8febcaa7cb8c5

I'll see what else I can dig up today to send over.

**Comment by tobilen** [comment]
> I'm investigating this, does anyone have a public repository where this occurs?

https://github.com/tobilen/chromatic-repro

checkout
run yarn
run `npx chromatic -t xxx`

tell me if you need the project token,  i'll send it via chromatics intercom
