### ISSUE TITLE
Allow isChromatic to take an optional window arg

### ISSUE THREAD

**Issue by anilanar** [chromaui/chromatic-cli#430]
There are cases where javascript is ran in a non-top level JS context such as in iframes. In such cases, `isChromatic` check fails because it uses the wrong `window` object. Allowing an optional `window` arg for `isChromatic` would solve such use cases.

**Comment by tmeasday** [comment]
Hi @anilanar -- can you explain the use case a little more? I don't quite understand this situation

**Comment by anilanar** [comment]
@tmeasday At userlike, we develop a messenger software that is embedable in other websites, very similar to Intercom you are using at Chromatic. To avoid being subject to prototype pollution, polyfilled promises etc, we load our code into a fresh new js context by creating an iframe and loading code into it.

This comes with a cost: libraries directly accessing `window` may not work anymore. In such cases, we report the problem or contribute with a PR and along the way, we have met many others who do the exact same thing, Intercom being one of them.

**Comment by tmeasday** [comment]
Oh, I see, so you are running `isChromatic` for code inside the iframe and you would pass it `window.parent`?

That make sense. Would you like to send a PR?
