### ISSUE TITLE
improve error message when action event is not supported

### ISSUE THREAD

**Issue by ndelangen** [chromaui/chromatic-cli#431]
from a customer:
>  suggestion! As a GitHub actions noob, I was confused whether the error message came from the action or from GitHub or what, so It could be made even more clear by saying something like: "The event ${event} is not supported by the Chromatic action. Currently supported events are: push, pull_request. Read more at ${url}."

**Comment by paulelliott** [comment]
Closed due to age. Please reopen if you feel this is still relevant for you.
