### ISSUE TITLE
Why map a story to a spec

### ISSUE THREAD

**Issue by ndelangen** [chromaui/chromatic-cli#44]
@tmeasday In this code:
https://github.com/chromaui/chromatic-cli/blob/master/bin/storybook/extract.js#L10-L26

We're mapping a storyObject to a specObject.
Why though?

This means chromatic is missing out on a ton of information storybook knows, and it's locked out of any future data that is added to storybook.

**Comment by tmeasday** [comment]
As discussed on a call:

I can see your point but there is a *lot* of data. Storybook already denormalizes a bunch of stuff onto the story parameters that's global and needlessly repeated for each story. Plus the user could put an arbitrary amount of data onto each story's parameters.

Given that users can have 2000+ stories in their storybook's that maps to a *lot* of data to send to our servers on each build. Note that we are also uploading their storybook so in theory we could always run the storybook again to extract whatever parameters we were interested in.

So this leads me to think a whitelist is a good idea. We can probably expand that whitelist however.
