### ISSUE TITLE
`spawn npm` is often broken on Windows

### ISSUE THREAD

**Issue by ghengeveld** [chromaui/chromatic-cli#45]
We should be using [cross-spawn](https://www.npmjs.com/package/cross-spawn).

**Comment by domyen** [comment]
The symptom Windows users encounter is this error `chromatic ERR! Error: spawn npm ENOENT`

**Comment by ndelangen** [comment]
I have switched to using cross-spawn, this issue should be resolved now. Please let us know if it's still a problem.

**Comment by ghengeveld** [comment]
For future consideration, `execa` provides some more robustness and ease of use around spawning child processes, and supports Windows too. 

https://github.com/sindresorhus/execa/blob/master/readme.md
