### ISSUE TITLE
Don't bail out of TurboSnap if `getDependentStoryFiles` throws

### ISSUE THREAD

**Issue by tmeasday** [chromaui/chromatic-cli#450]
We recently saw a problem where due to changes in webpack's JSON format, every build would hit an error, and end up bailing out of TS (i.e. running a full build). This is a problem because (by design) it isn't very obvious when TS is or isn't running in Chromatic's UI.

Instead we should fail the build and make it obvious to the user.

While we are at it, let's check the logging level of basic TurboSnap messages and make sure they aren't at the debug level -- if TurboSnap bails or doesn't find matching story files it seems like important information to log in CI, not debugging info.

**Comment by paulelliott** [comment]
Closed due to age. Please reopen if you feel this is still relevant for you.
