### ISSUE TITLE
Github Action Feature Request: support yarn and/or workspaces for monorepos

### ISSUE THREAD

**Issue by mkusold** [chromaui/chromatic-cli#453]
I have a project using `lerna` and `yarn workspaces`. My storybook stories should ideally link to my other package in the repo via workspaces. I would like to be able to have the Chromatic Github Action run `yarn workspace my-storybook-package storybook:build`

Right now, the github action for chromatic only supports `npm` which disqualifies me from using `yarn`. (My first request is humbly: can I request that `yarn` is supported?)
 
However, I am willing to do an on-the-fly conversion using [synp](https://github.com/imsnif/synp) to convert my yarn.lock to a package-lock.json and use `npm` instead. However, the `buildScriptName` option for the action still doesn't work since the npm equivalent for this script would be `npm run storybook:build --workspace=my-storybook-package` and the `buildScriptName` option doesn't seem to want to take in any flags. (So my second request is: can we pass flags or even just specify a workspace?)

In the meantime for others that run into this, I'm thinking I'll manually have to link the libraries I need that workspaces normally handle for me.

**Comment by paulelliott** [comment]
Closed due to age. Please reopen if you feel this is still relevant for you.
