### ISSUE TITLE
Remove duplicated deprecated code

### ISSUE THREAD

**Issue by tmeasday** [chromaui/chromatic-cli#47]
These lines https://github.com/chromaui/chromatic-cli/blob/21a4d76c1b6454094734bca48912e3082679c0a6/src/storybook-addon.js#L70-L141

Are duplicative of what's in `bin/storybook/extract.js`. I don't think we need to insert that code into the user's storybook any more and it will simplify things if all users go through the same code path.

**Comment by ndelangen** [comment]
@tmeasday was your idea to remove this code entirely?

Cause i was hoping of doing that some day, but it'd require a major version bump.

If the goal is to simplify things for ourselves, and we're ok with releasing a major version we should just delete this code.

**Comment by tmeasday** [comment]
Maybe we should save the major version bump to around Chromatic 2.0.

I was thinking that given `extract.js` runs the exact same code it shouldn't require a major version, it's sort of a transparent refactor from the perspective of users. We just make `import 'storybook-chromatic'` do nothing apart from output a deprecation warning.

**Comment by ndelangen** [comment]
I don't think it's super easy because:

1 part runs in node (bin) other runs in the browser (src). This would be the first bit of code shared, so I'm not sure where to place it, make sure it's transpiled for the browser, but not for node.

**Comment by ndelangen** [comment]
So since this is not urgent, and we're planning on removing it anyway, it's a waste to spend time on addressing the code-sharing problem, if we're not going to have any code to share in the future..

**Comment by tmeasday** [comment]
I'm not suggesting we share code, just that:

1. If you don't `import 'storybook-chromatic'` this code never runs, but everything works fine (because the same code runs in other places, once via insertion into JSDOM, the other via insertion from our capture code).

2. If you do, this code is added and you get a deprecation warning. But everything works fine.

I would suggest that we get rid of the "this code is added" but from 2. and users should notice no difference.
