### ISSUE TITLE
Broken IntlDateTimeFormatMock

### ISSUE THREAD

**Issue by ghengeveld** [chromaui/chromatic-cli#48]
Running `react-intl` through the CLI yields:

```
Error: Uncaught [TypeError: Class constructor IntlDateTimeFormatMock cannot be invoked without 'new']
```

This is because we've [mocked `Intl.DateTimeFormat`](https://github.com/chromaui/chromatic-cli/blob/21a4d76c1b6454094734bca48912e3082679c0a6/bin/lib/jsdom-shims.js#L147) using an ES6 `class`, but it's also valid to call it as a function, which ES6 classes don't allow. The fix is to use a function instead:

```js
function IntlDateTimeFormatMock(...args) {
  if (!(this instanceof IntlDateTimeFormatMock)) return new IntlDateTimeFormatMock(...args);
  // ...
}
```

This applies to:
- [Intl.Collator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Collator)
- [Intl.DateTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat)
- [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat)

Interestingly, it does not apply to:
- Intl.ListFormat
- Intl.PluralRules
- Intl.RelativeTimeFormat

**Comment by ndelangen** [comment]
Ok, thanks for the detailed report!

**Comment by tmeasday** [comment]
No longer relevant!
