### ISSUE TITLE
We don't surface user input errors properly

### ISSUE THREAD

**Issue by zol** [chromaui/chromatic-cli#49]
A user set a viewport that was too large. We had to dig through the logs in Loggly to find the root cause. This should have been surfaced to the user on the CLI.

See intercom: https://app.intercom.io/a/apps/zj7sn9j1/inbox/inbox/1025791/conversations/24225672941
Loggly: https://hichroma.loggly.com/search#terms=%222cc6f0be-11b7-4f5d-9891-336695409374%22&from=2019-10-22T18:19:21.041Z&until=2019-10-23T18:19:21.041Z&source_group=&event=4cf74e16-f58a-11e9-805b-0683a0f56bee,1571830995415,137911237957078550

**Comment by ndelangen** [comment]
I'm not able to exactly reproduce this:
https://www.chromaticqa.com/build?appId=5ccbc373887ca40020446347&number=315

I added a 1800 viewport to a story, it doesn't throw an error.

**Comment by ndelangen** [comment]
Never mind, I made the number bigger and can reproduce now.
