### ISSUE TITLE
Passign down Storybook argument values

### ISSUE THREAD

**Issue by idumancic** [chromaui/chromatic-cli#494]
Is there a way to pass down argument values to Chromatic for some specific story argument? Similar to viewports in Chromatic configuration. In my use case I would like to tell Chromatic to execute Storybook stories for some component in light and then in dark mode so that I can see visual differences when there is different theme provided.

**Comment by ghengeveld** [comment]
Hi Ivan,

Beyond viewports, we do not support taking additional snapshots for certain configurations of a story. You can achieve the desired result by creating separate stories. Using [story args](https://storybook.js.org/docs/react/writing-stories/args#story-args) you can easily reuse a story by spreading one story's args into another and overriding just the theme for that story. The downside is that you will have an extra story in your sidebar though. In the future you may be able to [hide](https://github.com/storybookjs/storybook/issues/9209) it but that's not possible yet.

Alternatively, you could setup a decorator to render the same component twice in a single story. Storybook's own Storybook does that and [uses the "stacked" layout in Chromatic](https://github.com/storybookjs/storybook/blob/21718982fdbefae09bf9e94b4e3c150fc42b82e7/examples/official-storybook/preview.js#L91). A benefit is that you won't be taking twice as many snapshots.

**Comment by AndreyYevtukhov** [comment]
@idumancic Hey! Did you manage to take snapshots in dark mode somehow?
