### ISSUE TITLE
Storybook metadata missing

### ISSUE THREAD

**Issue by ghengeveld** [chromaui/chromatic-cli#509]
Storybook info isn't being reported properly:

<img width="844" alt="Screenshot 2022-01-25 at 15 50 39" src="https://user-images.githubusercontent.com/321738/150999725-a0e393d5-714c-45e4-ac7c-9b04378be6dc.png">

This works in v5.10.2 and is broken in v6.4.1.

[Tracked in Linear here](https://linear.app/chromaui/issue/CH-1542/storybook-metadata-missing-regression)

**Comment by domyen** [comment]
Customer reported that the Docs tab (a symptom of this root issue) works in 6.3.4, that suggests the regression was introduced somewhere between 6.3.4 and 6.4.1.

**Comment by tmeasday** [comment]
This was fixed.
