### ISSUE TITLE
Feature Request: Custom npm registry support

### ISSUE THREAD

**Issue by JBallin** [chromaui/chromatic-cli#512]
The company I work for disables access to the public registry, so that we're forced to use our internal registry instead - which includes a mirror of the public registry.

This causes [checkForUpdates](https://github.com/chromaui/chromatic-cli/blob/main/bin-src/lib/checkForUpdates.ts) to fail with the following message:

> Could not retrieve package info from registry; skipping update check

Ideally chromatic would automatically use the `registry` in my closest `.npmrc`. Alternatively this could be set with a CLI flag and/or env var.

**Comment by ghengeveld** [comment]
Good call. I think we should just get the registry url by running `npm config get registry` using execa and use that [here](https://github.com/chromaui/chromatic-cli/blob/c9e6479bfe205d8349f42a5f8c8d6c47af6905b8/bin-src/lib/checkForUpdates.ts#L21).

**Comment by ghengeveld** [comment]
I've opened a PR to address this, it's in review.

**Comment by JBallin** [comment]
Amazing - thank you! Are you willing to cut a release for this?
