### ISSUE TITLE
Read slug from `REPO_NAME` environment variable also

### ISSUE THREAD

**Issue by tmeasday** [chromaui/chromatic-cli#515]
We currently read the git slug from either:
 - The git `origin` remote: https://github.com/chromaui/chromatic-cli/blob/9bc336c58ee52c6d7d19c82b800daa331ae02942/bin-src/git/git.ts#L124
 - The `CHROMATIC_SLUG` env var, but only if `CHROMATIC_BRANCH` and `CHROMATIC_SHA` are set.

It seems (on Jenkins at least), the remote isn't always set, but the `REPO_NAME` environment variable contains the same information. Perhaps we should try reading that if we don't find the remote?

**Comment by acc-nicholas** [comment]
I finally found where this is set, and its in our pipeline template. So i dont think this would be useful for the larger community. Thanks again though!

**Comment by tmeasday** [comment]
Ah! Got it. Thanks @acc-nicholas. Will close.

**Comment by t1gor** [comment]
> I finally found where this is set, and its in our pipeline template. So i dont think this would be useful for the larger community. Thanks again though!

I would actually disagree. Sounds like a reasonable feature for repos doing multiple remotes. Shouldn't be really hard to implement either. Are you accepting MRs?
