### ISSUE TITLE
Running tests blocked

### ISSUE THREAD

**Issue by shijiatongxue** [chromaui/chromatic-cli#517]
running tests in local for a long time

![image](https://user-images.githubusercontent.com/26477537/153565421-17e33ce3-d2f9-4752-a230-1da497f76d58.png)

and also running tests in github action for a long time

![image](https://user-images.githubusercontent.com/26477537/153564884-1937fe3b-7d7e-4128-97ff-4ee977c95c02.png)

Chromatic build：https://www.chromatic.com/build?appId=618c866f557c10003ac4cc42&number=113
Github action：https://github.com/DouyinFE/semi-design/actions/runs/1828194018

This is the first time I have encountered this problem. Anyone can help? Thanks!

**Comment by filipw01** [comment]
It seems to be infrastructure related see https://status.chromatic.com
<img width="815" alt="Screenshot 2022-02-11 at 12 23 02" src="https://user-images.githubusercontent.com/22986859/153583305-d4d5b576-6e17-407d-8a1f-cb24524129a2.png">

I think the issue can be closed @shijiatongxue

**Comment by shijiatongxue** [comment]
> It seems to be infrastructure related see https://status.chromatic.com/incident/70345 <img alt="Screenshot 2022-02-11 at 12 23 02" width="815" src="https://user-images.githubusercontent.com/22986859/153583305-d4d5b576-6e17-407d-8a1f-cb24524129a2.png">
> 
> I think the issue can be closed @shijiatongxue

Sure, thanks for your reply.

**Comment by tmeasday** [comment]
Thanks folks. Apologies about this, things are coming back up to speed now.
