### ISSUE TITLE
Support `generated-stories-entry.cjs` with turbosnap

### ISSUE THREAD

**Issue by IanVS** [chromaui/chromatic-cli#519]
I think that after https://github.com/storybookjs/storybook/pull/17486, the turbosnap code [here](https://github.com/chromaui/chromatic-cli/blob/ae23b1cbe275716c170dce69da36746ec2a6622c/bin-src/lib/getDependentStoryFiles.ts#L79-L86) needs to be changed to also look for `generated-stories-entry.cjs`.

**Comment by kylesuss** [comment]
Thanks for reporting @IanVS !

@ghengeveld / @tmeasday -- does this make sense to you? Any other considerations?

**Comment by tmeasday** [comment]
No absolutely.
