### ISSUE TITLE
Allow passing through environment variables to build-storybook command

### ISSUE THREAD

**Issue by blimmer** [chromaui/chromatic-cli#532]
Today, when `chromatic-cli` spawns `build-storybook`, it does not pass through environment variables from the containing shell.

We are experiencing an OOM when building our storybook in CI. To work around this, we want to set `GENERATE_SOURCEMAP=false` in the environment which resolves the OOM (see https://github.com/facebook/create-react-app/issues/8413#issuecomment-1047457575). Additionally, in the past, we've passed `NODE_OPTIONS` to avoid OOMs with CI instances, which would also be ignored.

However, these environment variables are not passed through when `chromatic-cli` spawns the build step.

To work around this issue, we can do a two-step process in CI (build the storybook ourselves, then call choromatic with the static directory path), but that's a bit more work.

**Comment by paulelliott** [comment]
Closed due to age. Please reopen if you feel this is still relevant for you.
