### ISSUE TITLE
Support multiple storybooks in TypeScript monorepos

### ISSUE THREAD

**Issue by relm923** [chromaui/chromatic-cli#537]
The suggested work around for multiple Storybooks in a monorepo ([docs](https://www.chromatic.com/docs/monorepos#combine-multiple-projects-into-a-single-storybook)) does not work with Typescript as the storybooks need to be transpiled with WebPack. There is no easy way to merge multiple WebPack builds even if they are using the same configurations. 

Example Repo
```
apps/
  web-app-a/
    .storybook/
    package.json
    src/
      index.stories.tsx
    storybook-static
  web-app-b/
    .storybook/
    package.json
    src/
      index.stories.tsx
    storybook-static
  web-app-c/
    .storybook/
    package.json
    src/
      index.stories.tsx
    storybook-static
```

**Suggested Options:**
1. Chromatic to add full support for multiple Chromatic projects in a single GitHub repo with full working PR checks
2. Chromatic to add support for multiple Storybooks in a single Chromatic project

**Comment by sandeepvortexa** [comment]
Having same issue

**Comment by tibi2303** [comment]
+1

**Comment by paulvidal** [comment]
This is a must with Nx -> we have 2 apps: 1 nextjs app and one create react app with different setups and it is becoming a nightmare

**Comment by norbertdragan** [comment]
This would be very useful for us, too.

**Comment by ethriel3695** [comment]
Hi @kenfdev you are correct.
Monorepo support is now officially supported.
