### ISSUE TITLE
Chromatic suddenly started failing claiming we have an older version of storybook, but in fact do not.

### ISSUE THREAD

**Issue by airtonix** [chromaui/chromatic-cli#541]
We have a typescript monorepo which has a design system that's been happily building with chromatic for review nicely.

today it suddenly started failing: 

```
Please note the session id: 'REDACTED'
contact [support@chromatic.com](mailto:support@chromatic.com) -or- open a support ticket at https://www.chromatic.com/
 
chromatic ERR! Problems encountered: 
chromatic ERR! Chromatic requires Storybook version at least 3.4. Please update your Storybook! 
 
undefined
/opt/atlassian/pipelines/agent/build/design-system/storybook:
 ERROR  @****/balance-storybook@1.0.34 chromatic: `chromatic --project-token=$CHROMATIC_PROJECT_TOKEN --exit-zero-on-changes`
Exit status 255
 ERROR  Command failed with exit code 1.
```

in that `.../design-system/storybook/package.json#dependencies` : 

```
...

     "chromatic": "^4.0.2",
  },
  "devDependencies": {
    "@babel/core": "^7.9.6",
    "@storybook/addon-actions": "^6.2.9",
    "@storybook/addon-knobs": "6.2.9",
    "@storybook/addon-links": "^6.2.9",
    "@storybook/addon-storysource": "^5.3.18",
    "@storybook/addons": "6.2.9",
    "@storybook/react": "^6.2.9",
    "babel-loader": "^8.2.2"
  }
...
```

**Comment by DzmitrySiniakou** [comment]
I have the same issue

**Comment by tmeasday** [comment]
Hi @airtonix @DzmitrySiniakou -- perhaps you can write into Chromatic support with some more details on the error messages you are seeing? 

I would suggest upgrading to the latest version of the Chromatic CLI to start; although I suspect this issue is actually due to a problem with your Storybook build. No idea why that might have changed. How recently have you had a successful build with this project?

I would suggest writing into support with your full logs so we can dig deeper into some of your failed SB builds.

**Comment by ghengeveld** [comment]
This issue usually pops up when running an outdated version of the CLI. Please make sure you have installed the latest version of `chromatic`:

<a href="https://www.npmjs.com/package/chromatic">
  <img src="https://badgen.net/npm/v/chromatic" alt="Published on npm">
</a>

Additionally, make sure that you are **not** using [`storybook-chromatic`](https://www.npmjs.com/package/storybook-chromatic), which is an ancient version of the CLI which is no longer supported. If you have it installed, please remove it. Don't forget to check your lockfile.

If you want to automatically upgrade to the latest version of `chromatic` going forward, you can remove the dependency altogether and use `npx` when running it (`npx chromatic ...`).

**Comment by xdrlik** [comment]
Thank you @ghengeveld for the feedback... I'm using npx and tried also locally installed Chromatic CLI, in both cases the same error. Please, see attached diagnostic data from running chromatic CLI.
[chromatic-cli-diagnostics.zip](https://github.com/chromaui/chromatic-cli/files/8230165/chromatic-cli-diagnostics.zip)
.

**Comment by ghengeveld** [comment]
Thanks for the info, your diagnostics don't reveal anything out of the ordinary. I did notice something odd about your [`iframe.html`](https://5ece210d74ccd5002245e981-azocvtsvki.chromatic.com/iframe.html) which doesn't contain any HTML, just some file path. Diagnostics show it has an uploaded content length of 31 bytes, so it's not our CDN messing up. Could you check your statically built Storybook (`storybook-static`)? Maybe you have some static dirs configured and iframe.html gets overwritten?
