### ISSUE TITLE
Is it possible to take a snapshot in dark mode?

### ISSUE THREAD

**Issue by AndreyYevtukhov** [chromaui/chromatic-cli#543]
You have a cool feature to capture snapshots for different viewports - https://www.chromatic.com/docs/viewports but I didn't manage to find an option to capture a snapshot for dark mode.

The only thing that I've found is https://github.com/chromaui/chromatic-cli/issues/341 -> which is closed ~1 year ago :( 

Our components **must** support dark mode and it would be great to be able to see how they look in Chromatic.

**Comment by ghengeveld** [comment]
Hi Andrii,

We don't currently have support for "variants" other than viewports. It did recently come up in internal discussions so it's still under consideration and will likely be supported eventually. 

For the time being, you can setup a decorator which renders your components twice (e.g. stacked or side-by-side), one light and one dark. This is [what Storybook does](https://github.com/storybookjs/storybook/blob/2430fe00708be493c224e2f626b3e1dcffa292f4/examples/official-storybook/preview.js#L91).

**Comment by zyulyaev** [comment]
@ghengeveld This however is not going to work with play functions, right?

**Comment by ghengeveld** [comment]
Unless you setup your play function to take into account there's two identical UIs on the same canvas, then no. It can be done though. You could totally extract the play function's statements to a separate function that takes a canvas argument, and from your play function you invoke it twice, once with the light container as the "canvas" and again for the dark container.

**Comment by zyulyaev** [comment]
This would require adjusting all play functions throughout the codebase. The approach does not seem to work in certain cases as well, like stories on modal windows. We decided to create another storybook and deploy it to a separate chromatic project, essentially repurposing the monorepo feature: https://www.chromatic.com/docs/monorepos.

**Comment by Yofamb** [comment]
The other issue with duplicating the story is that things like htmlFor and focussing on components does not work correctly.

**Comment by Yofamb** [comment]
@zyulyaev could you please provide an example repo of how you set this up? Sounds like the only solution for now

**Comment by codykaup** [comment]
Closing because this should be supported now that we have [Modes](https://www.chromatic.com/docs/modes/).

**Comment by news-manishpatel** [comment]
I was hoping it would work with props so we can capture multiple versions of the component without creating a story for each. 

Sadly does not work, it seems it only works with global parameters. 
```
{
    ...
    chromatic: {
      modes: {
        one: {
          args: {
            teasers: fixtures.teasers.slice(0, 1),
          },
        },
        two: {
          args: {
            teasers: fixtures.teasers.slice(0, 2),
          },
        },
        three: {
          args: {
            teasers: fixtures.teasers.slice(0, 3),
          },
        },
        four: {
          args: {
            teasers: fixtures.teasers.slice(0, 4),
          },
        },
      },
    },
  },
  argTypes: {
    teasers: { control: 'object' },
  },
  args: {
    teasers: fixtures.teasers,
  },
  ...
```
