### ISSUE TITLE
Github deployment and branches with '/'

### ISSUE THREAD

**Issue by edoardocavazza** [chromaui/chromatic-cli#544]
Hello!

We have integrated the Github action in our Storybook pipeline, but it generates a wrong deployment url when the branch name contains a `/`. 

Example for branch `feat/panorama`:
https://feat/panorama--61671e2d40b29f003a0a2c55.chromatic.com

Am I missing something or is it a bug?

**Comment by winkerVSbecks** [comment]
Hey @edoardocavazza, this is a known issue. We currently do not support branch names with a / in the name. We have it on our roadmap to add support for this.

Meanwhile, not exactly the same thing, however, https://www.chromatic.com/library?appId=<appid>&branch=<branch> would take you to the library page for that branch which then does have a link to Storybook.

**Comment by geryit** [comment]
Any update on this @winkerVSbecks ?
