### ISSUE TITLE
'Retrieved story files affected by recent changes' not working on Windows

### ISSUE THREAD

**Issue by MattCarr147** [chromaui/chromatic-cli#548]
Thanks again for putting in a fix for #547.

Unfortunately we are still unable to get TurboSnap working correctly on Windows environments, with another issue occurring later on in the process. 

I've been testing by making a small change to the same file as before, which is now being picked up correctly:

```
Found 1 changed files:
  src/pages/ActivityOverview/ActivityOverview.js
Retrieved git information
    → Commit '700c79a' on branch 'Bugfix/NN-497'; found 1 parent build and 1 changed file
```

However it fails later on:

```
Found affected story files:

Retrieved story files affected by recent changes
    → Found 0 story files affected by recent changes
```

Note that I have ran the chromatic trace command locally, passing in the path to ActivityOverview.js and it seems to work fine, resolving to the ActivityOverview.stories.js as expected:

```
npx chromatic trace src/pages/ActivityOverview/ActivityOverview.js --stats-file C:\\Users\\mattc\\AppData\\Local\\Temp\\chromatic--37060-ryfM42TRkOlk\\preview-stats.json
i Traced 1 changed file to 1 affected story file:

— src/pages/ActivityOverview/ActivityOverview.stories.js + 8 modules [changed]
  ∟ [story index]

Set --mode (-m) to 'expanded' to reveal underlying modules.
```

Notably, we tested the same command using Linux Subsystem for Windows and when run in there (identical codebase etc) the change is picked up correctly (_Found 1 story file affected by recent changes_). 

I'm afraid in this instance we haven't had a chance to dig into the code, so can't really offer any real pointers as to where the issue is originating.

The precise chromatic command we've been running, in case its useful at all (as mentioned previously, we're trying to let Chromatic use its defaults wherever possible)

```
yarn chromatic -- --only-changed --project-token **** --debug
```

**Comment by tmeasday** [comment]
Hi @MattCarr147 are you running Chromatic in CI on windows?

**Comment by MattCarr147** [comment]
@tmeasday as it stands yes, is this supported? We've not encountered any issues until trying to get the TurboSnap feature working, which I think will be an important one for us going forwards. 

Currently using via Jenkins multibranch pipeline, relevant step below. Failure is currently the same as experienced when running locally on Windows. 

```
steps {
    bat 'npx yarn chromatic --project-token=%CHROMATIC_PROJECT_TOKEN% --exit-zero-on-changes --only-changed'
}
```

**Comment by tmeasday** [comment]
@MattCarr147 I guess I was just checking that you weren't just testing TS on windows, but running Chromatic on a non-windows box :)

**Comment by paulelliott** [comment]
Closed due to age. Please reopen if you feel this is still relevant for you.
