### ISSUE TITLE
UI Review is not skipped when passing true to the skip flag

### ISSUE THREAD

**Issue by AndysonDK** [chromaui/chromatic-cli#549]
The problem is happening is this PR:
https://github.com/AndysonDK/syncbase/pull/6

Would be nice if the `skip` flag when given the value `true` also would skip the `UI Review` status github check

**Comment by ethriel3695** [comment]
@AndysonDK 
Thank you for creating this issue.

We have created a ticket to address this and will update you as we investigate!

**Comment by ethriel3695** [comment]
@AndysonDK 
A fix has been implemented for the issue you are experiencing. Please re-deploy your workflow and let us know if you have any further issues!

**Comment by AndysonDK** [comment]
Awesome it works, thanks!
