### ISSUE TITLE
github action sometimes fails to update UI tests PR check

### ISSUE THREAD

**Issue by burhanuday** [chromaui/chromatic-cli#552]
We use chromatic for visual diffing.

We run the action on every push. Sometimes, even after the tests have run successfully, the check in the PR does not get updated

![image](https://user-images.githubusercontent.com/25934701/159685083-24f610b9-4101-435e-9c2e-a25e63723ee5.png)

Over here you can see that it says pending but clicking on the details button, all tests have passed

![image](https://user-images.githubusercontent.com/25934701/159685160-91888d96-2274-4a61-b8e4-c525690c7dd0.png)

A way to get around this was to re-run the action. But lately the workaround does not work anymore and the action says that the check has already been run so it gets skipped and does not update the PR status

![image](https://user-images.githubusercontent.com/25934701/159685357-a713ca85-f325-46d5-ba1b-c292a75a48bf.png)

This is a problem for us because UI tests is a mandatory check and blocks merges.

**Comment by ethriel3695** [comment]
Hello @burhanuday!
Do you have a link to the specific build in Chromatic?

**Comment by maxeber** [comment]
I've had a lengthy discussion over the chat support. But this issue hasn't been fixed yet right? How can I track it this gets resolved? Is there any tracking available over Github? The chat ended up with:

![image](https://github.com/chromaui/chromatic-cli/assets/16073961/be190b6b-7095-4e3d-b519-7907de97a02f)

Are there any ETA?

**Comment by andrewortwein** [comment]
Hi @maxeber. You are correct—this issue has not been fixed yet. Our ticket system is internal, so there is no way to automatically track it here on GitHub. But, because you opened a conversation with us in Intercom, you will get a notification via email when its status has changed.

**Comment by maxeber** [comment]
Hi @andrewortwein, thanks for the reply. Would you guys have this planned or something? Must be pretty low priority I suspect so probably not planned yet.

**Comment by andrewortwein** [comment]
Hi @maxeber. While this is not currently planned for a specific target date or cycle, it is something we are continuing to track.
