### ISSUE TITLE
Turbosnap always detecting changes package-lock.json even when there are none

### ISSUE THREAD

**Issue by karrui** [chromaui/chromatic-cli#561]
This is resulting in the full suite of stories being compared against even when there are no changes (and massively increasing the costs). 

I suspect that this is due to Chromatic reinstalling the repository using npm7 or above, resulting in `package-lock.json` being rebuilt with `lockfileVersion: 2` even though the repository's own package-lock is of `lockfileVersion: 1`, resulting in a diff.

Can I check whether that is the case, and if there are any ways to ignore `package-lock.json` changes (and only care about `package.json` changes) for Turbosnap?

**Comment by ghengeveld** [comment]
Can you share more info about your setup? What environment are you running Chromatic in, and with which options/flags? That'll allow us to investigate unintended package-lock changes.

As a workaround, you can use `--untraced package-lock.json` to use TurboSnap regardless of any changes to that file.

**Comment by karrui** [comment]
This is being used in https://github.com/opengovsg/FormSG/tree/form-v2/develop, specifically the `form-v2/develop` branch. You can see the workflow file [here](https://github.com/opengovsg/FormSG/blob/form-v2/develop/.github/workflows/chromatic.yml) if that helps.

Good tip on the `untraced` flag! Will try that in the meantime.

**Comment by karrui** [comment]
Tracing the workflow, almost sure it is due to v1 and v2 mismatches, since
`npm i` in the GitHub workflow step outputs:

```
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
```

**Comment by karrui** [comment]
Fixed by using [actions/setup-node@v1](https://github.com/actions/setup-node) to pin the node version to 14 (which uses npm@6). Not a Chromatic issue after all!
