### ISSUE TITLE
Question: How to add/show storybook control in chromatic?

### ISSUE THREAD

**Issue by RatikantHM** [chromaui/chromatic-cli#563]
Just like in storybook, we have controls to change attributes of the components dynamically and validate, how can I achieve this in chromatic?

**Comment by RatikantHM** [comment]
Thanks a lot!
What I was trying to ask is:

![image](https://user-images.githubusercontent.com/73573421/165683900-52559d4d-8f08-4a46-bcc8-951874877218.png)

**Comment by codykaup** [comment]
That's what I figured! If you open up a build on Chromatic, there will be a link for `View Storybook` which will be your hosted Storybook and will include any controls configured for the story!

**Comment by domyen** [comment]
Closing because this is a Chromatic usage question (not CLI as far as I can tell). Use our in-app chat for the fastest place to get support.
