### ISSUE TITLE
New storybook  v6.4.22 version is failing in Github Action env

### ISSUE THREAD

**Issue by konsalex** [chromaui/chromatic-cli#568]
Tried to upgrade to `v6.4.22` and suddenly the CI environment in Github Actions started breaking.

The versions that were bumped from -> to

```
    "@storybook/addon-a11y": "^6.4.19",
    "@storybook/addon-actions": "^6.3.12",
    "@storybook/addon-essentials": "^6.3.12",
    "@storybook/addon-links": "^6.3.12",
    "@storybook/addon-storysource": "^6.4.19",
    "@storybook/react": "^6.3.12",
```

```
    "@storybook/addon-a11y": "^6.4.22",
    "@storybook/addon-actions": "^6.4.22",
    "@storybook/addon-essentials": "^6.4.22",
    "@storybook/addon-links": "^6.4.22",
    "@storybook/addon-storysource": "^6.4.22",
    "@storybook/react": "^6.4.22",
```

And the issue appeared when the `npm run` command was executed every time. When I reverted back the yarn.lock file everything worked again.

The debug logs from the Github action is also attached in case you find it helpful

**[visual-testing-logs.txt](https://github.com/chromaui/chromatic-cli/files/8686707/1_visual-testing.txt)**

**Comment by tmeasday** [comment]
Hi @konsalex it looks like your Storybook isn't building properly, likely due to a webpack mis-configuration. Have you tried running `yarn build-storybook`?

**Comment by konsalex** [comment]
Hey @tmeasday sorry for the late reply, yes I tried `yarn build-storybook` and it worked fine.

**Comment by tmeasday** [comment]
Hmm, that's surprising. It looks like the babel configuration is broken in the action but I have no idea why it wouldn't have the same issue on your local machine. Perhaps try running `yarn build-storybook` directly in the action?

**Comment by konsalex** [comment]
The thing @tmeasday is that the `chromatic` CLI runs `Running command: npm run --silent build-storybook -- --output-dir /tmp/chromatic--2064-ULWFN5w5htDg` which breaks, not the `yarn build-storybook`.

Can I explicitly say chromatic to use the `yarn`?

**Comment by tmeasday** [comment]
@konsalex do you have a reason to think `npm run` would fail in this way (due to a missing babel config) where `yarn run` wouldn't?

**Comment by konsalex** [comment]
That could work indeed. Is there a way to explicitly state the package manager we want chromatic cli to use?

But the most weird thing again is that the `npm run...` command in the previous version `6.3.xx` works fine, upgrading sb introduced the issue.

As I have a workaround feel free to close the issue, and if more people will land on this issue you can reopen

**Comment by tmeasday** [comment]
@konsalex what is that line of code in `iframe-webpack.config.js`?

My guess would be almost certainly this error is due to mismatching versions of SB packages.

**Comment by konsalex** [comment]
Not sure @tmeasday , the issue I can see as all packages are using the latest version:
[issue](https://issuehunt.io/r/storybookjs/storybook/issues/17996)

When I manually added the `'@storybook/addon-actions'` in `main.js` the build completed but with some issues (no stories at all inside)

```
Chromatic CLI v6.6.3
https://www.chromatic.com/docs/cli
Authenticating with Chromatic
    → Connecting to https://index.chromatic.com
Authenticated with Chromatic
    → Using project token '********8166'
Retrieving git information
Retrieved git information
    → Commit '4468b41' on branch 'dropdown'; found 1 parent build
Collecting Storybook metadata
Collected Storybook metadata
    → ; no supported addons found
Initializing build
Initialized build
    → Build 136 initialized
Building your Storybook
    → Running command: npm run --silent build-storybook -- --output-dir /tmp/chromatic--1[9](https://github.com/neo4j/neo4j-design/runs/6968909713?check_suite_focus=true#step:5:10)06-9J9A[13](https://github.com/neo4j/neo4j-design/runs/6968909713?check_suite_focus=true#step:5:14)klZtPY
Storybook built in 41 seconds
    → View build log at /home/runner/work/neo4j-design/neo4j-design/packages/react-storybook/build-storybook.log
Publish your built Storybook
    → Validating Storybook files
Publishing your built Storybook
    → Retrieving target location
    → Starting publish
Publish complete in 5 seconds
    → View your Storybook at https://6[22](https://github.com/neo4j/neo4j-design/runs/6968909713?check_suite_focus=true#step:5:23)5e0c9734f0d003a2cf577-migvsbrnke.chromatic.com
Verifying your Storybook
    → This may take a few minutes
✖ Failed to extract stories from your Storybook
This is usually a problem with your published Storybook, not with Chromatic.
Build and open your Storybook locally and check the browser console for errors.
Visit your published Storybook at https://62[25](https://github.com/neo4j/neo4j-design/runs/6968909713?check_suite_focus=true#step:5:26)e0c97[34](https://github.com/neo4j/neo4j-design/runs/6968909713?check_suite_focus=true#step:5:35)f0d003a2cf577-migvsbrnke.chromatic.com
The following error was encountered while running your Storybook:
    → Failed to publish build
```

I would make an educated guess, that the issue is coming from the `npm run` rather than choosing `yarn` as locally it builds fine with the `yarn build`

**Comment by tmeasday** [comment]
@konsalex Thanks for the link to the issue. It really just confirmed my suspicion that the issue is caused by conflicting package versions. Have you checked `yarn.lock` to see if you have different versions of various SB packages?

**Comment by iamswain25** [comment]
local chromatic deployment works, while github action from chromaui/action@v1 fails with storybook ^6.5.9, react-scripts ^4.0.3. react ^17

**Comment by tmeasday** [comment]
@iamswain25 I'd advise writing in to Chromatic support with some details and we can help you out further.

**Comment by iamswain25** [comment]
> @iamswain25 I'd advise writing in to Chromatic support with some details and we can help you out further.

I got the response from Chromatic support, and the problem was due to missing env var in github actions. `firebase.initializeApp()` failure 

However, the error message was not reflecting the problem, I thought there was something wrong with my redux decorator.
```
Error: Evaluation failed: TypeError: Cannot read property 'I0' of undefined
    at AppBarLogo (https://60ccd5dc2f1cfd0039ac18e7-ninzinyxqa.capture.chromatic.com/main.cecb3fc8.iframe.bundle.js:1:173508)
```

anyway thanks for your help! @tmeasday
