### ISSUE TITLE
Unable to connect Chromatic with Private Gitlab.

### ISSUE THREAD

**Issue by NM-2000** [chromaui/chromatic-cli#586]
My company has Gitlab instance with the company's domain.
Instead of `gitlab.com`, it is `gitlab.<org-name>.com`.
How to connect Chromatic with it? Right now, Chromatic asks me to login to `gitlab.com`, even when I am logged into `gitlab.<org-name>.com`.

**Comment by tmeasday** [comment]
Hi @NM-2000 -- currently GL self-hosted is supported on our enterprise plan. You'll need to send a message to support to learn more about it -- either by emailing support@chromatic.com or using the intercom chat widget on our website.

**Comment by NM-2000** [comment]
Thanks @tmeasday!
