### ISSUE TITLE
[Question] Several packages are using the same projectToken. Can they have their own 'Storybook Publish' row?

### ISSUE THREAD

**Issue by dep** [chromaui/chromatic-cli#588]
I have several packages within my monorepo using the same `projectToken`. The publish job completes for each of them, and they all seem to have a unique URL within the "github workflows" log, however, back in the pull request, there's only one row-item for the Published storybook:

![image](https://user-images.githubusercontent.com/55112925/171877690-d0a4b168-cb4f-4c80-b6b5-4f3714e2badf.png)

Is it possible to have a row-item for each published storybook?  It'd be nice to have shown "Storybook Publish: Titan Core", "Storybook Publish: Titan Templates", etc. Seems like default the one listed is the "latest one"

**Comment by tmeasday** [comment]
Hi @dep, we are currently working on a "monorepo" project which will allow exactly the behaviour you are requesting here. It is in progress and will likely complete this month sometime. In the meantime, this is the best practice for what you are trying to do: https://www.chromatic.com/docs/monorepos#monorepos

**Comment by dep** [comment]
Great! I very much look forward to the monorepo functionality!

**Comment by paulelliott** [comment]
Closed due to age. Please reopen if you feel this is still relevant for you.
