### ISSUE TITLE
Unable to publish StoryBook on Chromatic

### ISSUE THREAD

**Issue by NM-2000** [chromaui/chromatic-cli#589]
The structure of my project is described below.

<img width="465" alt="Screenshot 2022-06-08 at 5 47 17 PM" src="https://user-images.githubusercontent.com/95714736/172614142-0d027799-b241-41eb-9ad3-fc4a401ea765.png">

I'm facing issues while publishing the storybook of package1 to Chromatic.
How do I configure the path of storybook for Chromatic to know where to find Storybook's main.js file and build it?

**Comment by tmeasday** [comment]
Hi @NM-2000 what issues are you seeing? If you have a `start-storybook` script defined in `packages/package1/package.json` and you run chromatic from `packages/package1` I would expect it to work!

**Comment by NM-2000** [comment]
In my package.json, scripts "start-storybook" and "build-storybook" exist like described below.

```
"start-storybook": "start-storybook -p 8000 -c src/storybook",
"build-storybook": "build-storybook"
```

I change my pwd to "package1", and I run the below command.

```
npx chromatic --project-token=********** --build-script-name build-storybook
```

<img width="1054" alt="Screenshot 2022-06-09 at 10 53 36 AM" src="https://user-images.githubusercontent.com/95714736/172770541-ac1c5e79-66a3-41a1-9d78-ef6ff8378f10.png">

In the build-storybook.log file that is generated, the following error is there:

```
ERR! Error: No configuration files have been found in your configDir (packages/package1/.storybook).
ERR! Storybook needs either a "main" or "config" file.
```
Why is it not looking for the storybook inside src folder. It's searching for storybook at wrong place. I tried storybook-base-dir and storybook-config-dir as mentioned in Chromatic CLI's documentation but that too didn't work. What am I doing wrong?

**Comment by tmeasday** [comment]
Hey @NM-2000 -- you'll need to add the `-c src/storybook` option to your `build-storybook` script also!
