### ISSUE TITLE
False positives from hashed classNames?

### ISSUE THREAD

**Issue by tuzmusic** [chromaui/chromatic-cli#593]
I will often push a build using the Chromatic CLI running locally, and get this success message:
```
✔ Build 86 passed!
No visual changes were found in this build.
```

But then I have a bunch of changes in the Chromatic UI. Not only new stories, but also stories with basically zero diff.

The code diffs appear to be only in the classnames generated by styled-components
![image](https://user-images.githubusercontent.com/22814728/174849090-36b41cd1-a4ba-45a6-af7e-15784848ec91.png)

The visual diffs say that the baseline is taller than the new snapshot, but only by a *single pixel* of height. Which seems to me to maybe be some kind of rounding error. I certainly don't see any difference myself.

![image](https://user-images.githubusercontent.com/22814728/174849404-266e736f-2e91-435d-a0e4-224a05e45f18.png)

FWIW, I am using Material UI, configured to use Styled-components instead of Emotion. This current branch may not actually have that style engine set up correctly, and I believe the theme is also not set up correctly (I have that fixed in a different branch) but I'm pretty sure the diff is between builds with the exact same config. (I'm assuming Chromatic only compares builds on the same branch?!?! otherwise that may be the explanation.)

## `main.js`
```js
module.exports = {
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
    '@storybook/preset-create-react-app',
    '@storybook/addon-a11y',
    'storybook-addon-react-dev-tools',
    'storybook-addon-react-router-v6',
    'storybook-mirage'
  ],
  features: { interactionsDebugger: true },
  framework: '@storybook/react',
  core: {
    builder: '@storybook/builder-webpack5',
  },
  typescript: {
    check: false,
    checkOptions: {},
    reactDocgen: 'react-docgen-typescript',
    reactDocgenTypescriptOptions: {
      shouldExtractLiteralValuesFromEnum: true,
      propFilter: prop => (prop.parent ? !/node_modules/.test(prop.parent.fileName) : true),
    },
  },
};
```

## `preview.js` (abridged)
```js
export const decorators = [
  withServer(createMockServer.bind({}, { environment: 'test' })),
  Story => (
    <>
      <header>
        <link
          href="https://fonts.googleapis.com/css?family=Roboto:100,200,300,400,500,600,700"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Roboto+Condensed:400,500,600,700"
          rel="stylesheet"
        />
      </header>
      <AppWrapper>{Story()}</AppWrapper>
    </>
  ),
];
```

## `AppWrapper.tsx`
```ts
import React, { useEffect } from 'react';
import { ThemeProvider } from 'styled-components';
import { globalStyles, theme } from './theme';
import { Provider } from 'react-redux';
import { createStore, RootState } from './configureStore';
import 'bootstrap/dist/css/bootstrap.min.css';

type Props = {
  store?: ReturnType<typeof createStore>;
  initialState?: RootState;
};

export const AppWrapper: React.FC<Props> = ({ children, store, initialState }) => {
  const appStore = store || createStore(initialState);

  return (
    <ThemeProvider theme={theme}>
      {globalStyles}
      <Provider store={appStore}>{children}</Provider>
    </ThemeProvider>
  );
};
```

**Comment by tuzmusic** [comment]
Ah, I see. I didn't even realize this was just the CLI repo. Thanks!

**Comment by KsavinN** [comment]
Hi, I found this closed Issue, but it seems related to my project. Does anyone @tuzmusic  or @jmhobbs suggest which repo is related or what could be a potential solution for this issue?

**Comment by jmhobbs** [comment]
Seeing diffs when you don't expect them is likely going to be something Chromatic support will be able to help with rather than a bug here, as most of that happens inside the Chromatic app.  support@chromatic.com is your best bet 👍
