### ISSUE TITLE
chromatic build error graphql

### ISSUE THREAD

**Issue by junyong3** [chromaui/chromatic-cli#595]
`npx chromatic --project-token` 
If you run the command from a certain moment, HTTPClient failed to fetch https://index.chromatic.com/graphql, got 400/Bad 

Request in the Initializing build order

The following error occurs: Please tell me how to debug or how to fix it.

Build success locally
Build failed in gitAction ㅜ

builder  -> use  builder-vite 

<img width="848" alt="image" src="https://user-images.githubusercontent.com/107021199/175466576-ca2695c6-dc29-4c75-a598-672d3a7a10a2.png">

**Comment by tmeasday** [comment]
Hi @junyong3 - it will be easier to debug this if you post it to Chromatic support

**Comment by junyong3** [comment]
Thanks😄
