### ISSUE TITLE
--only option is ignored under unknown circumstances

### ISSUE THREAD

**Issue by NiklasPor** [chromaui/chromatic-cli#604]
Hey all, thanks for building this tool – it greatly improves our dev workflow 🙏 

### Context
We're always running or chromatic checks with the `--only` flag to specifically only check stories which are designed for it. Starting today, pipelines started including all of our stories. We didn't apply any changes to our chromatics pipeline and the log output still says that the "only" filter is being applied:

Build output:
![image](https://user-images.githubusercontent.com/13211347/178685334-f9f1fe36-0a18-441e-8bc5-217ff1d3d583.png)

Story structure (excerpt):
![image](https://user-images.githubusercontent.com/13211347/178682078-80adedf5-c08d-4d3d-9d97-059563f45466.png)

But the chromatic tests still include all components:
![image](https://user-images.githubusercontent.com/13211347/178685630-ee785321-5e8e-448c-b04b-e004e4076608.png)

### Workaround
We needed to disable the visual regression tests, because otherwise our quota would fill up very, very fast.

Kind regards,
Niklas 🚀

**Comment by tmeasday** [comment]
Hi @NiklasPor -- which version of our CLI are you using? We shipped a *fix* for the `--only` flag for recent versions of the CLI in our backend yesterday. Maybe we broke it for older versions of the CLI? Or were very confused.
