### ISSUE TITLE
Action times out with storyStoreV7, works fine otherwise

### ISSUE THREAD

**Issue by thure** [chromaui/chromatic-cli#605]
I’d configured my project to use `storyStoreV7` to anticipate features Storybook would add in v7. It did cause the Chromatic step to take substantially longer, and now it’s begun to break. The log output looks like this:

```
Operation timed out
Error: non-zero exit code
ℹ Spawn settings:
{
  "client": "npm",
  "clientVersion": "6.14.17",
  "nodeVersion": "v14.20.0",
  "platform": "linux",
  "command": "npm",
  "clientArgs": [
    "run",
    "--silent"
  ],
  "scriptArgs": [
    "storybook:build",
    "--",
    "--output-dir",
    "/tmp/chromatic--{redacted}
  ]
}
```

Disabling `storyStoreV7` solved the problem (for now), though when v7 is released I imagine others will encounter this issue without knowing the etiology.

Is the timeout configurable? Can it be extended?

**Comment by tmeasday** [comment]
Hi @thure, it looks like there's an env var `STORYBOOK_BUILD_TIMEOUT` you can set! How long do you builds take? SSv7 can take a little longer but in my experience shouldn't really make a huge difference, perhaps something odd is going on here.

**Comment by thure** [comment]
I’ll consider adding `STORYBOOK_BUILD_TIMEOUT`, thank you!

Looking back at total CI action times, `storyStoreV7` appears to have about doubled it (i.e. disabling that feature halves the time).

Maybe the added time comes from the resource-sparse CI environment building so many bundles? What is the end-to-end CI action time difference in your experience?

**Comment by tmeasday** [comment]
> What is the end-to-end CI action time difference in your experience?

I don't have exact figures but probably like a 20-30% increase in time feels about right.

Are you using webpack5? You could look at using the FS cache and caching build assets on your CI between builds?

**Comment by stuthib** [comment]
@tmeasday super appreciate what you all do at chromatic and my team feels very empowered by Chromatic.
 
Not related, but we are running into timeout issues on CI as well. We are using chromatic `~6.10.1` and storybook-react `~6.5.12`. It seemed to working very well, but as we started to add more stories and interaction tests, it seems to timeout sporadically. It fails 1 out of 4 times on CI and is blocking the PRs from going in. 

Attached are some screenshots from the CI. Would appreciate your help that would help us unblock the PRs.

<img width="1033" alt="Screenshot 2023-11-22 at 2 08 58 PM" src="https://github.com/chromaui/chromatic-cli/assets/12240549/ab1a4a38-9951-4b98-8028-bb760f5d83da">

<img width="1047" alt="Screenshot 2023-11-22 at 2 07 18 PM" src="https://github.com/chromaui/chromatic-cli/assets/12240549/9fa1dc20-100d-43d8-bc47-3ccd0b820fd2">

**Comment by tmeasday** [comment]
Hi @stuthib - glad y'all are finding Chromatic valuable!

My first suspicion when CI times out like this is that it is running out of memory. I'm not sure if it's an option for you but you could look at using a [larger runner](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners) for GH actions? I'm not sure how to debug the memory usage of actions, I know that CircleCI has UI that helps you debug that, but I haven't seen that for GH (yet).

I'm also not sure how feasible it is but you could try using SB7 and see if it's better. For sure there were changes we made in 7.x that should help with this problem, although I can't really say how much. @kasperpeulen and @ndelangen might be able to say more.

**Comment by stuthib** [comment]
> Hi @stuthib - glad y'all are finding Chromatic valuable!
> 
> My first suspicion when CI times out like this is that it is running out of memory. I'm not sure if it's an option for you but you could look at using a [larger runner](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners) for GH actions? I'm not sure how to debug the memory usage of actions, I know that CircleCI has UI that helps you debug that, but I haven't seen that for GH (yet).
> 
> I'm also not sure how feasible it is but you could try using SB7 and see if it's better. For sure there were changes we made in 7.x that should help with this problem, although I can't really say how much. @kasperpeulen and @ndelangen might be able to say more.

@tmeasday thank you for the response. I think it would be a good idea for us to use SB7, I will give that a try. 

As for the memory, we tried increasing the limit but it did not seem to help.

**Comment by paulelliott** [comment]
Closed due to age. Please reopen if you feel this is still relevant for you.
