### ISSUE TITLE
Action function is not spied in chromatic interaction

### ISSUE THREAD

**Issue by swallowtail62** [chromaui/chromatic-cli#606]
As mentioned in the following link, In local storybook `action` mock works.

https://github.com/storybookjs/storybook/tree/v6.5.9/addons/interactions#usage

> Any args that are marked as an action (typically via argTypes or argTypesRegex) will be automatically wrapped in a [Jest mock function](https://jestjs.io/docs/jest-object#jestfnimplementation) so you can assert invocations. See [addon-actions](https://storybook.js.org/docs/react/essentials/actions) for how to setup actions.

However in chromatic, mock don't work and test fails. Error as shown in the following.

![image](https://user-images.githubusercontent.com/45661101/179130032-e86ebe12-2123-46ed-a411-ed6a42649e6c.png)

```
Error: expect(received).toBeCalledTimes(expected)

Matcher error: received value must be a mock or spy function

Received has type:  function
Received has value: [Function n]
```

**Comment by tmeasday** [comment]
Hey @swallowtail62 -- have you tried in your built storybook? I would expect Chromatic's behaviour would be very similar to ejecting from the build.

**Comment by swallowtail62** [comment]
Sorry, it wasn't chromatic.
It was because `initialArgs` property (function) name had been shortened in built storybook.

![image](https://user-images.githubusercontent.com/45661101/179136337-cdcc16f9-94f6-4048-b761-ad49b120547c.png)


The `name` had to be `actionHandler`.

https://github.com/storybookjs/storybook/blob/v6.5.9/addons/interactions/src/preset/preview.ts#L23

I'm using `@storybook/builder-vite` as a bulder so I'll take a look there, thanks.
