### ISSUE TITLE
Can chromatic follow the viewport specified by the viewport addon?

### ISSUE THREAD

**Issue by sballesteros** [chromaui/chromatic-cli#611]
👋  not sure if this is the best place for this (so feel free to close and move elsewhere).
I noticed that Chromatic doesn't seem to follow the viewport specified with the [viewport add-on](https://storybook.js.org/docs/react/essentials/viewport).

For instance (taking an example from the [addon documentation](https://storybook.js.org/docs/react/essentials/viewport#configuring-per-component-or-story)), if you have:

```js
export const MyStory = () => <MyComponent />;
MyStory.parameters = {
  viewport: {
    defaultViewport: 'iphonex',
  },
};
```

I would expect Chromatic to take a snapshot with a width corresponding to one specified by the addon (`375px` in the example).

Unless I am missing something this doesn't appear to be supported at the time and instead, we need to also set viewport using the [chromatic viewports settings](https://www.chromatic.com/docs/viewports):

```diff
 export const MyStory = () => <MyComponent />;
 MyStory.parameters = {
   viewport: {
     defaultViewport: 'iphonex',
   },
+  chromatic: { viewports: [375] },
 };
```

**Comment by tmeasday** [comment]
Hey @sballesteros, this is something we plan to address, I'd advise writing into support so you can be notified when it gets done.

**Comment by RyanClementsHax** [comment]
Is it safe to follow this issue to get notified when this is done?

**Comment by ThiagoMaia1** [comment]
Following!

**Comment by tmeasday** [comment]
I think that'll work, for now. We'll let you know if that changes.

**Comment by santiagopuentep** [comment]
Me too. Waiting for this to be fixed. The stories with viewport setup appear in something like firescreen size.

**Comment by erikpukinskis** [comment]
I would also love to see this... I have a story that tests whether our `<Dialog>` component looks right when scrolling. But the Chromatic viewport is too tall so it doesn't trigger the scrolling state. It works great in Storybook but I don't know how to make it work in Chromatic.

**Comment by winkerVSbecks** [comment]
This is now supported: https://www.chromatic.com/docs/viewports/#using-defaultviewport
