### ISSUE TITLE
[Question] Show "files changed" even if the snapshots are the same

### ISSUE THREAD

**Issue by cythilya** [chromaui/chromatic-cli#625]
In this project we do not change anything but the snapshots are updated with the message "7 changes accepted as baselines". Please see the [build](https://www.chromatic.com/build?appId=62d10396c36c853a5aa44fcb&number=44).

**Comment by domyen** [comment]
Hey @cythilya, please use our in-app chat to chat with our eng team. It's better for customer privacy too.

(this repo is for the CLI, which doesn't seem like the issue here)
