### ISSUE TITLE
Make snapshots testing part open-source

### ISSUE THREAD

**Issue by muratcorlu** [chromaui/chromatic-cli#633]
**Feature request**

Since we don't know the details how Chromatic takes screenshots, debugging snapshot issues (like [this issue](https://github.com/chromaui/storybook-addon-pseudo-states/issues/38)) is very difficult. Sometimes it doesn't work as on our local and the only way to debug it is just do some changes and push to chromatic and wait for up to 10 minutes. 

**Proposed solution**

Open-source snapshot part of chromatic and give us the chance to run snapshot testing on our local.

**Alternative solutions**

Alternatively, you can give more detailed context and document about details of snapshot testing. Even you can give some hooks/plugins that we can run during the snapshot testing process.

**Additional context**

I understand this feature is one of the key selling points of Chromatic but since your main users are developer, this need will be bigger and bigger in every day, I think. And even if you make snapshot part of the Chromatic open-source, still you are good at selling this whole flow as a service. Even though you'll lose some people who will run snapshot testing directly on their pipelines, many more will feel more trust about using your service.

This is also related with #622 A solution provided here can give us opportunities to use different tooling in snapshot testing process.

**Comment by ghengeveld** [comment]
Thanks for the detailed description. We've had similar requests in the past. Our current stance is that we don't plan to support Chromatic on-premise (on your own hardware, wherever that is). However, we may consider revealing some details about our Puppeteer/Playwright setup, perhaps as some sort of plugin, or provide the ability to run a single snapshot against our cloud infra for debugging.

For browser-debugging, we often use BrowserStack with Chrome 89 on Windows. You can use that along with `localtunnel` or `ngrok` to test against your local machine. Most of the time that will reproduce the issue.

I can reveal a couple of details that may help you test things locally. For Chrome, we use `chrome-aws-lambda`, which means it runs on AWS's version of Linux. We inject a bunch of scripts to disable animations and such, but most importantly we emit and listen for some Storybook events to determine when to take the screenshot. Here's the gist:

```js
const storyId = inputStoryId || toId(kind, story);
return new Promise((resolve, reject) => {
  channel.on('storyRendered', () => resolve(document.getElementById('root')));
  channel.on('storyUnchanged', () => resolve(document.getElementById('root')));
  channel.on('storyErrored', ({ title, description }) => reject(new Error(`${title}\n${description}`)));
  channel.on('storyThrewException', (error) => reject(error));
  channel.on('storyMissing', (id) => id === storyId && reject(new Error('storyMissing')));
  channel.emit('setCurrentStory', { storyId });
});
```

I've linked this ticket to our internal issue tracker so we'll follow up here if there's any progress on that. Closing this.

**Comment by muratcorlu** [comment]
@ghengeveld Thank you for the details. Can you also reply those questions?

* Do you open every stories on a separate instance to take screnshots or do you navigate them (or some) in same instance?
* Do you use `iframe.html` in Storybook to take screenshots?

**Comment by ghengeveld** [comment]
Yes, we batch snapshots, which means some will be in the same instance, and some won't. We reset the browser environment as much as possible between stories. 

We navigate to iframe.html, then call `setCurrentStory`. We never load index.html (the Storybook manager UI).
