### ISSUE TITLE
Use Node 16 in chromaui/action and stop using set-output

### ISSUE THREAD

**Issue by IanVS** [chromaui/chromatic-cli#652]
**Feature request**

I'm getting a deprecation warning in Github from the chromatic github action, since it's apparently using node 12:

>Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: chromaui/action

**Proposed solution**

Update to node 16.

**Comment by IanVS** [comment]
And while you're at it, it looks like `set-output` has also been deprecated, which is causing many more notices as well:

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/4616705/196975944-f57efd5a-4d7a-4742-a2c1-555c07aac94e.png">

 https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by chrillep** [comment]
@thafryer @skitterm ping!
```
[ci runner](https://github.com/yaytrade/yaytrade-components/actions/runs/3345850454/jobs/5541904067)
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: chromaui/action
```

**Comment by IanVS** [comment]
@chrillep i don't think GitHub actions can run using node 18 yet, just 12 or 16. 

It looks like the PR I referenced has been merged. So I suppose this can be closed now.

**Comment by thafryer** [comment]
@IanVS Yes, it has been merged. Thanks for closing! My apologies for getting back to you late!
