### ISSUE TITLE
<button /> browser default buttonface created no diff in build

### ISSUE THREAD

**Issue by dutscher** [chromaui/chromatic-cli#654]
Hi there, i have a problem with a browser default behavior.
We had a tailwind css reset which contains `button { background-color: transparent }`.
Which means our list item component should be white (transparent).

But due reasons we decided to remove this reset.

And now the bug is appearing!

The button gets the browser default background "backface" and the item gets grey:

![image](https://user-images.githubusercontent.com/14682/196184448-dc8b96d2-be66-4ccd-9057-3d837be107ff.png)

The bug is, that the chromatic build didnt get a diff and stop the build.
The same in the other direction, if i accept the buttonface grey, and add the transparent color back again.
Chromatic didnt stop the build. 

Grey buttonface browser default: 
![image](https://user-images.githubusercontent.com/14682/196191499-017373a7-52db-4c9c-b0d7-435d5ab4e47a.png)
https://www.chromatic.com/component?appId=618bdde9c1d8b8003a887c89&csfId=base-surfaces-menu--elevations&buildNumber=103&k=633d302d3df0f802ad237c23-1200-snapshot-true&h=6&b=-4

White background-color: transparent: 
![image](https://user-images.githubusercontent.com/14682/196191532-28c2428d-8e93-4eae-8df0-d0648e164edd.png)
https://www.chromatic.com/component?appId=618bdde9c1d8b8003a887c89&csfId=base-surfaces-menu--elevations&buildNumber=104&k=633d302d3df0f802ad237c23-1200-snapshot-true&h=7&b=-5

The snapshots are correct and a diff is clear visible. What can we do?

Did you need more?

cheers

**Comment by codykaup** [comment]
Hey @dutscher! 👋 

It appears those snapshots are just slightly under the default Chromatic threshold of `.063`. We have a [public Storybook](https://6262c53f521620003ac2ff49-ukmsdlppcb.chromatic.com/?path=/story/stories-diff-threshold-check--test-yours-out) to test this out and I was able to trigger the diff at `.060`. If you [change the threshold](https://www.chromatic.com/docs/threshold#setting-the-threshold) for that story, Chromatic should pick it up!

I hope this helps!

**Comment by dutscher** [comment]
@codykaup i was really hoping that the threshold solves my problem.
but i try at least the 0 threshold and there is no diff at the background.

![image](https://user-images.githubusercontent.com/14682/196711544-8deda086-f945-4f73-b71a-927732af5c29.png)

i mean threshold is a good point but the big area of difference is the snapshot should reach in the default 0.63 case a diff.

cheers

**Comment by codykaup** [comment]
Oh that's interesting! It appears this issue may be related to anti-aliasing so those backgrounds get filtered out. I'm able to replicate this by [enabling anti-aliasing](https://www.chromatic.com/docs/threshold#anti-aliasing). Not sure why I don't get an output image locally here but do you get better results by enabling anti-aliasing on that story?

**Comment by dutscher** [comment]
Nope...
![image](https://user-images.githubusercontent.com/14682/196780056-f361e3ec-3ca7-4668-9fb7-876135e2cf13.png)

https://www.chromatic.com/component?appId=618bdd7730c270003ae4c827&csfId=base-surfaces-menu--elevations&buildNumber=128&k=6350221e59f07de767f48c59-1200-snapshot-true&h=14&b=-5

Its confused. I try so much but nothing diff as expected. 
Threshold and antialiasing didnt help.

Thanks for your help and i hope we found a solution.

Cheers

**Comment by codykaup** [comment]
Bummer! I was hoping the fix was going to be one of those settings but it seems like this may require more investigation. Would you mind using our in-app chat to keep this conversation going? It's our preferred method of troubleshooting and it's better for customer privacy. This repo is used for issues specific to the CLI but this is going to be deeper in Chromatic.

Thanks!
