### ISSUE TITLE
Documentation for Chromatic UI review badge in github for PRs 

### ISSUE THREAD

**Issue by peter-coastpay-com** [chromaui/chromatic-cli#677]
The documentation for getting this PR UI review badge to appear in github is pretty lacking,  is there any way you guys could put together a more comprehensive resource on this ?  

![image](https://user-images.githubusercontent.com/102534600/201983149-fc70d963-ab73-44bb-a3cf-6435b0d5cbbc.png)

**Comment by ethriel3695** [comment]
Hi @peter-coastpay-com ,

The PR UI review badge is enabled by default if you follow the rest of the workflow in the document that you are referencing.
This section references that if you've set up the workflow correctly, you will see a PR status check for UI Review and also shares resources on how to enable it as a required check for each `git` provider.

I would be happy to edit the docs to make more sense, is your concern that this section is too ambiguous without the context of the rest of the page?

**Comment by peter-coastpay-com** [comment]
i think the issue was that when you first start a project, the primary screen of the chromatic web application is some redacted page that only shows your last build and obscures the app navigation.... i found this confusing because the docs reference navigating to pages that didn't appear to exist. 

Id suggest probably eliminating the existing behavior in the app that obscures the navigation for new projects and just always show the nav.
