### ISSUE TITLE
Drop `NODE_ENV=development` when building

### ISSUE THREAD

**Issue by tmeasday** [chromaui/chromatic-cli#68]
This is a historical accident. I'm not sure if it is a breaking change or not.

**Comment by lifeiscontent** [comment]
@tmeasday seems in CI when chromatic is running, it doesn't include env vars. so my storybook is busted until I can figure out how to overcome this. (using next.js) in preview.js

```js
import { setConfig } from 'next/config';

setConfig({
  publicRuntimeConfig: {
    API_HOST: process.env.API_HOST,
    GOOGLE_MAPS_API_KEY: process.env.GOOGLE_MAPS_API_KEY,
  },
});
```

apparently API_HOST and GOOGLE_MAPS_API_KEY are undefined when chromatic runs in CI

**Comment by tmeasday** [comment]
@lifeiscontent are the env vars used in the frontend? This seems like a storybook issue perhaps, we don't drop any env vars we just add a couple: https://github.com/chromaui/chromatic-cli/blob/master/bin/storybook/start-app.js#L60:L64

**Comment by lifeiscontent** [comment]
@tmeasday thanks for the response!

We’re using next.js so in the storybook config I’m using setConfig from “next/config” and setting the env vars we need from process.env.

I’m also using a custom web pack config for storybook to step over some of the issues with next.js e.g. Babel configs

**Comment by lifeiscontent** [comment]
also, fwiw, everything works as expected in development.

**Comment by tmeasday** [comment]
Does it work when you run `yarn build-storybook` though @lifeiscontent?

**Comment by lifeiscontent** [comment]
@tmeasday great question, let me try it!

**Comment by lifeiscontent** [comment]
@tmeasday yep, it builds, should I try and run it with serve?

**Comment by lifeiscontent** [comment]
@tmeasday I just ran it with serve, everything works fine.

**Comment by tmeasday** [comment]
You don't get any errors to the console?

**Comment by lifeiscontent** [comment]
@tmeasday None!

**Comment by lifeiscontent** [comment]
@tmeasday pinged you on Intercom
