### ISSUE TITLE
Error when trying to run Chromatic

### ISSUE THREAD

**Issue by w3bdesign** [chromaui/chromatic-cli#681]
**Bug report**

I have ran Chromatic without issues until today, when I started getting build errors in CircleCI.

I did a run today locally with the exact same command and in the same repo, with the command `yarn chromatic --project-token=xxxxxxx`

I tried both yarn and npx and got the same error. 

For reference, here are my version numbers for Node and npm:

$ node --version
v18.12.0

$ npm --version
8.19.2

The error I get is this: 

`ERR! ModuleNotFoundError: Module not found: Error: Can't resolve 'C:\GitHub\dfweb-v3\storybook-init-framework-entry.js' in 'C:\GitHub\dfweb-v3'`

**Comment by tobias-mintlify** [comment]
We started having issues today too when running in GitHub actions using `chromaui/action@v1`. You can see the entire error log here: https://github.com/mintlify/components/actions/runs/3526368423/jobs/5914214299

Publishing the Storybook from the CLI works (`npx chromatic --project-token=redacted`)

**Comment by kylegach** [comment]
I believe this is an issue with Storybook and not Chromatic.

Unfortunately, a transitive dependency of Storybook released a new minor version that is [incompatible with Storybook](https://github.com/webpack/enhanced-resolve/issues/362). We're working with the maintainers to come up with a solution, but in the meantime, you can pin the version to the last known working release:

**npm** (if on npm 8 or higher)
```json
{ "overrides": { "enhanced-resolve": "5.10.0" } }
```
**Yarn**
```json
{ "resolutions": { "enhanced-resolve": "5.10.0" } }
```
**pnpm**
```json
{ "pnpm": { "overrides": { "enhanced-resolve": "5.10.0" } } }
```

Sorry for the hassle!

**Comment by w3bdesign** [comment]
This fixed the issue for now, thanks!
