### ISSUE TITLE
timemachine.reset is erroring with Storybook 7.0.0 alpha

### ISSUE THREAD

**Issue by Tallyb** [chromaui/chromatic-cli#682]
**Bug report**
Angular 15
Storybook 7.0.0-alpha.53
chromatic@6.11.4

Calling timemachine.reset() throws an error on storybook: 
TypeError: Cannot assign to read only property 'prototype' of function 'function Date() { [native code] }'
this occurs on 
```
        Date.prototype = OriginalDate.prototype;
```
Not sure what is blocking the assignment. Works ok on SB 6.5.

**Comment by ghengeveld** [comment]
Does this error occur only in Chromatic, or also when you run Storybook locally?

This issue does not appear to be related to the CLI, so I'm closing the ticket. Please reach out to [Chromatic support](https://www.chromatic.com/docs/support) if you think this is an issue with Chromatic, or use the [Storybook support](https://storybook.js.org/community/#support) channels if it's a problem with Storybook.
