### ISSUE TITLE
[Question] How to enable Chromatic result stats on Github using Jenkins

### ISSUE THREAD

**Issue by dgonzalezr** [chromaui/chromatic-cli#697]
**Question**

We have our repo hosted on a private GitHub Enterprise repository. The chromatic Github app has been enabled for the repo in the matter and we use Jenkins for our CI workflow. Unfortunately, we cannot see the Chromatic result stats in the PR after the Chromatic steps run on Jenkins, even when in the output it says so.

```yaml
sh  label: 'Publish PR changes to Chromatic',
    script: $/
      . \$HOME/.nvm/nvm.sh
      nvm use ${node_version}
      npm run build
      npx chromatic --project-token=${CHROMATIC_PROJECT_TOKEN} --storybook-build-dir=packages/panenka/docs --branch-name="${env.CHANGE_BRANCH}" --ci --only-changed --zip --exit-zero-on-changes
    /$
```

![CleanShot 2022-12-12 at 19 42 55](https://user-images.githubusercontent.com/328492/207116382-05875b5a-5455-424e-a830-5e755cd13403.png)

![CleanShot 2022-12-12 at 19 34 15](https://user-images.githubusercontent.com/328492/207114221-753c8a56-344a-4f4f-97b3-3ec26bfa5664.png)

is there some specific requirement for this or does it work only by using the chromatic Github action? I expect to see something similar 👇🏼  on our PR checks. (_the screenshot below is from another project that actually uses the chromatic GitHub action_)

![CleanShot 2022-12-12 at 19 30 33](https://user-images.githubusercontent.com/328492/207114092-68c87971-b683-4687-914e-8890a2412b83.png)

Please notice that we have a linked project with UI review enabled:

![CleanShot 2022-12-12 at 19 35 44](https://user-images.githubusercontent.com/328492/207114617-73fd9b9f-c4cb-4551-b624-68287cd614e4.png)

**Comment by skitterm** [comment]
Hi @dgonzalezr, thanks for reaching out. For this one it's best to write into Chromatic support (chat icon in bottom-right corner of Chromatic) so we can dig into the specifics of what you are doing. Please reach out there and supply your project ID. Thanks!
