### ISSUE TITLE
Don't increment build number when using `--dry-run`

### ISSUE THREAD

**Issue by rosen-kanev** [chromaui/chromatic-cli#708]
**Bug report**

When running the Chromatic CLI with `--dry-run` the build number is incremented. The counter seems to be incremented even if you don't wait for the command to exit and `Ctrl^C` it.

I stumbled upon it on the very first run of `yarn chromatic --dry-run` and then without the `--dry-run` flag. The deploy was successful and the Chromatic dashboard showed that I have only one build with the name "Build 2". When I opened it, there was an info section below the header with the text: 
Build 2 is based on a commit without ancestor builds, which is unusual. Check out our [build documentation](https://www.chromatic.com/docs/test#why-do-i-see-build-x-is-based-on-a-commit-without-ancestor-build)

Probably low on your radar since it's pretty minor, but worth looking into it. IMO a dry run shouldn't produce side effects.

**Comment by paulelliott** [comment]
Closed due to age. Please reopen if you feel this is still relevant for you.
