### ISSUE TITLE
Storybook builds suddenly fail with all components errors at GH action

### ISSUE THREAD

**Issue by nilshendriks** [chromaui/chromatic-cli#716]
Suddenly builds are being published but **fail** all tests:

No idea what's going on... any hints? 

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/694301/218059561-610b68bd-70bd-4605-a71a-9b1211388b0b.png">

on chromatic build site for every component it reports this

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/694301/218060017-d1c2a8fb-aba9-4ffe-a773-80ebc2251238.png">

I have not changed how all components are written.
- running storybook works locally
- chromatic build storybook works also
- all components fail and therefor no review option

**Comment by nilshendriks** [comment]
Figured out this is caused by some addon that doesnt play nice. Not sure which addon exactly yet but at least it is not a chromatic issue. feel free to close this issue.

**Comment by andrewortwein** [comment]
Thanks for digging in on that @nilshendriks! If you happen to find out which add-on is causing the problem and feel like sharing, please leave a comment here.
