### ISSUE TITLE
Storybook addon-coverage support from the CI chromatic task

### ISSUE THREAD

**Issue by majoncas-ue** [chromaui/chromatic-cli#724]
**Feature request**

Currently the test-storybook command is automatically handled by our Github CI task but there are no way to connect it to the Storybook "addon-coverage" (https://github.com/storybookjs/addon-coverage) tool at the moment.

**Proposed solution**

I would expect being able to set a configuration object or some flags so I can use the addon-coverage tool the same way as I do locally. I would also expect being able to generate nyc report and make my pipeline failing if I don't meet the expected coverage threshold. 

**Alternative solutions**

I could run my custom "yarn test-storybook --coverage" and then run this other command "yarn npx nyc report --check-coverage --branches=93 --functions=80 --lines=89 --statements=90 --reporter=lcov -t coverage/storybook --report-dir coverage/storybook" through the CI but it would mean that we would run the storybook tests twice (one time in Chromatic step and another time in the second step). This would increase the pipeline execution time and I think this should be avoided.

**Comment by winkerVSbecks** [comment]
Thanks, this is something on our roadmap. I've tagged your issue to our internal feature request tracker.

**Comment by IPWright83** [comment]
@winkerVSbecks is there any update on this? Could you 👍🏻 the internal feature request tracker please? This definitely prevents us from relying too heavily on any automated Storybooks which would be incredibly useful.

**Comment by winkerVSbecks** [comment]
@victorcarvalhosp sorry my bad, we're still tracking this internally. Storybook is shifting to jest for component testing and will offer coverage via that: https://storybook.js.org/blog/storybook-test-sneak-peek/ We're likely going to build on that to offer coverage in Chromatic.

**Comment by stjepanGrego** [comment]
@winkerVSbecks any updates for this after latest storybook releases?

**Comment by winkerVSbecks** [comment]
@ndelangen @JReinhold I know you all were looking into this. Any updates that you can share?

**Comment by winkerVSbecks** [comment]
@stjepanGrego not at the moment, it's still on the roadmap though.
