### ISSUE TITLE
Improve error message if `build-storybook` fails

### ISSUE THREAD

**Issue by shilman** [chromaui/chromatic-cli#73]
The chromatic CLI passes in `--log-level error` to the build storybook command, but this fails when the user is using `vue-cli-service storybook:build`

The CLI needs to be smarter about the options at appends to the build command. It's currently based only on the version of Storybook being used (> 5.1.0), but I don't think that's enough.

**Comment by ndelangen** [comment]
I think in edge-cases like this we should just tell the user to first: build-storybook and then use the resulting directory and pass that ref to the chromatic-cli.

We do not want to be responsible for every little edge-case like this.

**Comment by ndelangen** [comment]
Do you agree @shilman @tmeasday ?

**Comment by tmeasday** [comment]
Yeah I think are right. Can figure out something like this has happened, show the error in a more actionable way and provide the advice on the cli? That’d be ideal.

Another option would be to update SB to set the log level via an env var. Wdyt about that?

**Comment by ndelangen** [comment]
I think getting a lib that auto syncs cli-options and env-vars would be great

**Comment by tmeasday** [comment]
OK, should we create a SB issue about that? In the meantime let's make this ticket just be about showing SB build errors in a more actionable way.

**Comment by tmeasday** [comment]
Here's another example of how the CLI failure can be confusing when storybook fails to build: https://app.circleci.com/jobs/github/chromaui/chromatic/28994

**Comment by ndelangen** [comment]
This is what I see in the log you link to:
```
$ build-storybook -o /tmp/chromatic-921WcVRnFlP6F1O --loglevel error
(node:956) UnhandledPromiseRejectionWarning: Error: => Create a storybook config file in "./.storybook/config.{ext}".
    at createPreviewEntry (/home/circleci/chromatic/examples/simple-app/node_modules/@storybook/core/dist/server/preview/entries.js:21:11)
    at <anonymous>
(node:956) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:956) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by tmeasday** [comment]
@ndelangen I didn't mean I couldn't figure out what had happened, just as a user if you look at the logs, you see all this at the end:

```
chromatic info Uploading your built Storybook... 
uploading [] Infinitykb/s 1% 0.0suploading [] 2067kb/s 14% 1.3suploading [] 2160kb/s 16% 1.2suploading [] 1596kb/s 18% 1.6suploading [] 2169kb/s 27% 1.0suploading [] 2169kb/s 35% 0.9suploading [] 3500kb/s 61% 0.3suploading [] 4532kb/s 85% 0.1suploading [] 5263kb/s 100% 0.0s

chromatic info Uploaded your build, verifying 
chromatic info Uploading and verifying build (this may take a few minutes depending on your connection) 
chromatic ERR! ** Chromatic build failed. **
Please note the session id: '81bff261-9b7d-40b3-9e8e-1cfd74befaf5'
contact support@hichroma.com -or- open a support ticket at https://chromaticqa.com
 

chromatic ERR! Problems encountered: 

chromatic ERR! 404 - {"type":"Buffer","data":[52,48,52]} 
 
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code exit status 255
CircleCI received exit code 255
```

Chances are you'll miss the real error which is just above (in fact I think that exact thing happened to the user who ran into this ticket).

**Comment by tmeasday** [comment]
Also, maybe we should check that that the `build-script-name` exists in `package.json`?

**Comment by tmeasday** [comment]
LGTM on next

**Comment by ndelangen** [comment]
✔️

**Comment by ndelangen** [comment]
https://github.com/chromaui/chromatic-cli/pull/74/commits/2b7828a76688286a9d30f56ee23f5ef149ce6730
