### ISSUE TITLE
Error: INTERNAL_SERVER_ERROR - Publishing a subset of stories is no longer supported

### ISSUE THREAD

**Issue by gkio** [chromaui/chromatic-cli#746]
**Bug report**

We are using `chromatic@6.11` to publish our Storybook, but we're receiving an error that says "INTERNAL_SERVER_ERROR: Publishing a subset of stories is no longer supported. Make sure to include all stories in your Storybook and remove the --preserve-missing flag." The error occurs when using the following command:

`yarn chromatic --ci --exit-zero-on-changes --only-story-names 'Project/Screens/**' --exit-once-uploaded --projectToken=XXXX
`

We believe this error is caused by the `--only-story-names` flag, which we're using to publish a subset of stories. According to the error message.

We would greatly appreciate your assistance in resolving this issue, as it is imperative that we are able to publish our Storybook using chromatic-cli and selectively choose specific screens for publication, rather than all of them. Thank you in advance for your help.

The first error occurred on May 8, 2023 at 12:42pm GMT+0400

**Comment by cgbl-90** [comment]
Hello @gkio, we've completely removed support for `--preserve-missing` as of today, but `--preserve-missing` may still be triggered for anyone not using Chromatic v16.17.3. Can you upgrade your CLI for now? We will disconnect `--preserve-missing` from `--only-story-names` for older versions of CLI.

**Comment by thafryer** [comment]
Hi @gkio! In the latest versions (6.17.3 and later) of the CLI, we have disconnected the preserve missing behavior from the `--only-story-names`. Please reopen this issue if you are still experiencing problems.
