### ISSUE TITLE
Support for GitHub Releases

### ISSUE THREAD

**Issue by landsman** [chromaui/chromatic-cli#748]
**Feature request**

My flow for production is based on GitHub Releases.
I tried Chromatic and I really like it! So it's sad for me to see this error message:

```
release event is not supported in this action
```

Please add support for this event. I don't see a problem when I operate in GitHub Actions where I can do whatever I want with git etc.

**Comment by withinfocus** [comment]
Could be combined with https://github.com/chromaui/chromatic-cli/issues/797 on generated tags and releases.

**Comment by paulelliott** [comment]
Closed due to age. Please reopen if you feel this is still relevant for you.
