### ISSUE TITLE
Cannot skip project without specifying a way to build the storybook

### ISSUE THREAD

**Issue by MJez29** [chromaui/chromatic-cli#751]
**Bug report**

My storybook is being built as a separate step before I run chromatic so when I want to upload it I call

```
chromatic -d build-dir
```

When I want to skip uploading the storybook I would expect this to work

```
chromatic --skip
```

However I am seeing the following error

```
The CLI didn't find a script called "build-storybook" in your package.json.
Make sure you set the --build-script-name option to the value of the script name that builds your Storybook.
```

I can get around this by doing

```
chromatic --skip -d build-dir
```

But ideally this shouldn't be necessary

**Comment by paulelliott** [comment]
Closed due to age. Please reopen if you feel this is still relevant for you.
