### ISSUE TITLE
--exit-once-uploaded seeming not to work?

### ISSUE THREAD

**Issue by DigTheDoug** [chromaui/chromatic-cli#77]
As mentioned in [this help post](https://intercom.help/chromatickb/en/articles/3538628-building-and-uploading-your-storybook) and in this pr: #63, I am trying to get the `chromatic` command to exit once the folder has been uploaded using `--exit-once-uploaded`. 

For some reason, could be user error, I can't seem to get it to work; it always stays open until the tests are finished running, the expected behavior without the flag.

Here's the example output
```
➜  frontend-library-hello git:(build/test-chromatic-exit) ✗ export CHROMATIC_APP_CODE=<removed> && npx chromatic --storybook-build-dir preview --exit-once-uploaded
chromatic info Uploading your built Storybook... 
uploading [====================] 1048kb/s 100% 0.0s

chromatic info Uploaded your build, verifying 
chromatic info Uploading and verifying build (this may take a few minutes depending on your connection) 
chromatic info Found 1 story 
chromatic info Started Build 23 (1 component, 1 story, 3 snapshots).

View it online at https://www.chromaticqa.com/build?appId=<removed>&number=23. 
chromatic info 3/3 snapshots remain to test. (0 changes, 0 errors) 
chromatic info 2/3 snapshots remain to test. (0 changes, 0 errors) 
chromatic info Build 23 passed! View it online at https://www.chromaticqa.com/build?appId=<removed>&number=23. 
➜  frontend-library-hello git:(build/test-chromatic-exit) ✗ 
```
It runs successfully, but it keeps the thread open after uploading. 
This runs from an already compiled version of storybook, as noted in the command.

Version details:
`storybook-chromatic@3.4.1`

Is there anything I am missing to how this should work?

**Comment by tmeasday** [comment]
Hmm, no that looks like it should work @DigTheDoug, we'll take a look.

**Comment by DigTheDoug** [comment]
Hey @tmeasday has there been any update on this? Some of our larger libraries take 4-5 minutes for Chromatic to run the checks and it'd be helpful if that didn't tie up the build agents for that time. Do you need any further info or reproduction steps?

**Comment by tmeasday** [comment]
Hi Doug, sorry about the delay here, I guess it was that time of year ;)

I just ran a command basically identical to what you have above with version 3.4.1 and it worked as expected.

```
npx storybook-chromatic --app-code=<snip> --storybook-build-dir /tmp/storybook --exit-once-uploaded
chromatic info Uploading your built Storybook...
uploading [====================] 883kb/s 100% 0.0s

chromatic info Uploaded your build, verifying
chromatic info Uploading and verifying build (this may take a few minutes depending on your connection)
chromatic info Found 3 stories
chromatic info Started Build 597 (1 component, 2 stories, 5 snapshots).

View it online at https://www.chromaticqa.com/build?appId=<snip>&number=597.

[done]

**Comment by DigTheDoug** [comment]
Thanks. Looking at your command lead me to dig deeper into it (running npx with `storybook-chromatic` vs `chromatic`) and I believe that the issue was that there were multiple versions of the library installed it it was running the older one. After fully clearing out the `node_modules` folder and reinstalling everything at the latest the command works as expected. Thanks!
