### ISSUE TITLE
Deal with `build-storybook` being an alias to another script

### ISSUE THREAD

**Issue by tmeasday** [chromaui/chromatic-cli#79]
This fairly uncontroversial setup:

https://github.com/planningcenter/design/blob/2531a8ab7437b96581c310c3a8fee82fd1c7820e/package.json#L42-L43

Stuffs us up because the `-o` flag doesn't end up getting passed through to the `build` script.

Related to #78

**Comment by ndelangen** [comment]
I don't see a `-o` in the linked example?

**Comment by tmeasday** [comment]
We add a `-o $tmpdir` flag and I guess the way npm/yarn works it didn't end up passing through to the final command.

**Comment by ndelangen** [comment]
The user can use the --build-script-name to point the cli to the correct script OR they could use yarn (which does passes though any flags) OR they could use something like:

```
    "build": "build-storybook",
    "build-storybook": "npm run build --",
```
