### ISSUE TITLE
Keep older version tags of GitHub Action

### ISSUE THREAD

**Issue by itchyny** [chromaui/chromatic-cli#797]
**Feature request**

The [Chromatic GitHub Action](https://github.com/chromaui/action) does not keep the git history and older version tags, but we really need them.
As usual for reproducible build, we lock the patch version of chromatic in package.json and use the exactly same version of `chromaui/action` by tag pinning.
This normally works well because GitHub Action Runner locally cache the action version, but it starts to fail when the cache expires.

We also have problem on integration with [Renovate](https://github.com/renovatebot/renovate).
In order to conform to my company security rule, we actually use digest pinning for the action.
However, since you forcibly push and drop the git history of the action repository, Renovate fails to look up the configured digest from the repository.
This makes us unable to update the action version using Renovate, and we keep using older version which may expire at unexpected timing.

**Proposed solution**

Keep git history and older tags of [chromaui/action](https://github.com/chromaui/action).

**Alternative solutions**

Not sure.

**Additional context**

Nothing.

**Comment by withinfocus** [comment]
Here's an example: https://github.com/bitwarden/clients/pull/6120 -- we'd like to add a comment after the digest so we can pin to a specific version / tag.

**Comment by ghengeveld** [comment]
FWIW, the alternative is to write your own GitHub Action workflow which invokes our CLI (which follows semver) directly, rather than using `chromaui/action`. The main thing is does is for pull_request events set `event.payload.pull_request.head.ref` as `CHROMATIC_BRANCH` and `event.payload.pull_request.head.ref` as `CHROMATIC_PULL_REQUEST_SHA` (env vars). See [this file](https://github.com/chromaui/chromatic-cli/blob/main/action-src/main.ts).

Needless to say the release process for the action is lacking and we want to address it. We just haven't gotten around to doing that yet.

**Comment by bmuenzenmeyer** [comment]
also found this issue in pursuit of associating a chromai/action sha with a semver tag - was slightly alarmed to see the history getting overwritten...it is literally harder to do what you are doing then just letting them remain out there, right?

my code: https://github.com/nodejs/nodejs.org/blob/main/.github/workflows/lint-and-tests.yml#L219

**Comment by ghengeveld** [comment]
We have plans to add versioning to the GitHub Action by introducing tags for major and patch releases (e.g. v7 and v7.0.1), which is what many other popular actions do as well. I can't pick this up short-term, but may be able to get to it later this month. No guarantees.

**Comment by itchyny** [comment]
Thanks for keeping old tags, we're now happy because Renovate can update the action version. Although git history is still lost, I'm okay with closing the issue because the original Renovate issue was resolved, but is there anyone really need old git history?

**Comment by ghengeveld** [comment]
Keeping history is still the intention but is a bit more work that’s hard to prioritize unfortunately.

**Comment by paulelliott** [comment]
This should be fixed. Please reopen if you feel this is still relevant for you.
