### ISSUE TITLE
Story level viewports don't override default viewport parameters with CSF

### ISSUE THREAD

**Issue by kylesuss** [chromaui/chromatic-cli#80]
`"storybook-chromatic": "^3.4.1"`

Given this default export:
https://github.com/kylesuss/gh-provider-test/blob/45e20ad58547f498ca7295db38c1c865ee9718b1/stories/index.stories.js#L8-L13

```js
const VIEWPORT_XSMALL = 400;
const VIEWPORT_SMALL = 768;
const VIEWPORT_MEDIUM = 1280;

export default {
  title: "Demo",
  parameters: {
    chromatic: { viewports: [VIEWPORT_XSMALL, VIEWPORT_SMALL, VIEWPORT_MEDIUM] }
  }
};
```

and this story:
https://github.com/kylesuss/gh-provider-test/blob/45e20ad58547f498ca7295db38c1c865ee9718b1/stories/index.stories.js#L51-L65

```js
export const Button = () => {
  const button = document.createElement("button");
  button.type = "button";
  button.style = "color:green;";
  button.innerText = "Hello Buttonz";
  button.addEventListener("click", e => console.log(e));
  return button;
};

Button.story = {
  name: "button",
  parameters: {
    chromatic: { viewports: [VIEWPORT_SMALL, VIEWPORT_MEDIUM] }
  }
};
```

I would expect that the `Button` story only captured 2 viewports. However, 3 viewports were captured (the 3 from the default export).

I have confirmed that at least _some_ of the `chromatic` parameters are being used by tossing `{ chromatic: { disable: true } }` in the story (and the corresponding opposite of that in the default export) and seeing the story disappear.

**Comment by kylesuss** [comment]
Closing this as I think this is actually happening on the Storybook side. I have done some investigation and it seems that `storyStore.extract()` is returning the 3 viewports. Therefore, we are just reading what Storybook sends.

**Comment by kylesuss** [comment]
Found this:

https://github.com/storybookjs/storybook/blob/9a6557ca77b0ace9538028e5f6bc9033e6350989/lib/client-api/src/client_api.ts#L17

**Comment by tmeasday** [comment]
@kylesuss actually that code is not relevant to this problem -- that is explicitly not used for arrays, so shouldn't apply here:https://github.com/storybookjs/storybook/blob/9a6557ca77b0ace9538028e5f6bc9033e6350989/lib/client-api/src/client_api.ts#L249-L252

I wonder what is happening? If you have a sec, maybe try debugging through your example project.

**Comment by tmeasday** [comment]
Oh.. or maybe it is used one level in. I take it back.
