### ISSUE TITLE
Capture snapshots on demand

### ISSUE THREAD

**Issue by ValeFranchi** [chromaui/chromatic-cli#815]
**Feature request**

We are using chromatic snapshots along with interactions, As documented, the snapshot is taken after the story has finished loading and the `.play()` interaction execution is finished. It would simplify the ability to take snapshots during different steps through the interaction, Is it possible to add some API or functionality to be able to do this? is there any other way of doing this?

**Proposed solution**

API to take snapshots

**Comment by ghengeveld** [comment]
Hey @ValeFranchi and @mririgoyen,

Chromatic always takes snapshots at the end of the play function, and intentionally doesn't support snapshotting through an imperative API. There is a better solution, and that's to split up your play function into separate stories, and use composition to avoid duplication. Here's how that works (based on the example provided above):

```jsx
const ModalOpen = {
  args: {},
  play: async ({ canvasElement, chromatic, step }) => {
    const canvas = within(canvasElement);
    const body = within(canvasElement.ownerDocument.body);
    await userEvent.click(canvas.getByRole('button'));
    await body.findByTestId('modal-content');
  },
};

const ModalClosed = {
  ...ModalOpen,
  play: async (context) => {
    await ModalOpen.play(context);

    const body = within(context.canvasElement.ownerDocument.body);
    waitForElementToBeRemoved(body.getByTestId('modal-content'));
    await userEvent.click(body.getByTestId('modal-overlay'));
  },
};
```

We do have [an API](https://www.chromatic.com/docs/e2e-visual-tests/#manual-snapshots) that's somewhat like what you're asking for, but it's only for E2E tests, not Storybook stories. This `takeArchive` API actually generates a story for each invocation, so it ends up behaving similar to what I described above.

If you have any feedback on why splitting and composing stories wouldn't work, we'd love to hear about it so we may reconsider our approach. For now I'll close this ticket.

**Comment by mririgoyen** [comment]
> Hey @ValeFranchi and @mririgoyen,
> 
> There is a better solution, and that's to split up your play function into separate stories, and use composition to avoid duplication.

This is really not a better solution for the reasons I pointed out in my post:

> There are workarounds, but most of them are ugly are hard to maintain. We can write very specific stories that stop when the modal is open, but now these clutter up the Stories view of our documentation and add unwanted stories to the sidebar. We can tag the stories and write filters to remove them from the sidebar. We can stop using <Stories /> in our MDX and manually add each <Story /> we want to show. But this is not ideal. It's a lot of maintenance just to get snapshots when they should happen for these types of components.

I don't need a story with the modal closed and a story with the modal pre-opened in my docs and now I have to do extra work and maintenance on subsequent updates to ensure the _documentation_ is up-to-date to satisfy the testing framework. 

I really, really hope you reconsider adding an imperative API for advanced use-cases, such as the ones proposed in this thread.

**Comment by ghengeveld** [comment]
@mririgoyen I forwarded your feedback to the product team. There's consensus on needing a better solution, and we're at least pretty close to a way to tidy up the Storybook sidebar using tags. This may not be totally satisfactory but would make it possible to have both a neat sidebar for docs and the capability to create stories just for testing. 

Long term we may have a way to take ad hoc snapshots as well, but likely that would be a side-effect of better story-writing capabilities or the consolidation of CSF with our E2E API (which needs to mature first before we can even know whether that makes sense).

I recommend that you also share your feedback with our customer support team via Intercom (or email to support), because they actually track feature requests.
