### ISSUE TITLE
Warn user about missing `preview-stats.json` when running with `--only-changed`

### ISSUE THREAD

**Issue by gurschitz** [chromaui/chromatic-cli#868]
**Feature request**

It would be great if the CLI could show a warning or error when running with `--only-changed` and the built storybook doesn't have the `preview-stats.json`.

We ran into a situation where we didn't notice for a while that our TurboSnap wasn't working anymore on our project. We recently migrated our Storybook from using webpack to using vite, and since TurboSnap was set up way before that, and because of that it wasn't obvious to us that we needed to add [`vite-plugin-turbosnap`](https://github.com/IanVS/vite-plugin-turbosnap) to make it work again. 

Since to me it sounds like TurboSnap only works with `preview-stats.json` anyways (it's even [mentioned in the tooltip in chromatic](https://share.slab.com/GnDFJczB), but no one from our team saw that early enough), it would be great to get feedback on this as early as possible, ideally from the CLI. Does this make sense?

Edit: 
Looks like the CLI actually prints a warning, but no one of our team has perceived this. 
![CleanShot 2023-12-05 at 13 41 35](https://github.com/chromaui/chromatic-cli/assets/4624537/26b22732-0fd3-4454-b69f-0b5d4cf93279)
It's easy to miss since it looks visually very much like the warning when TurboSnap is disabled due to rebuild.
![Screenshot 2023-12-05 at 13 29 31](https://github.com/chromaui/chromatic-cli/assets/4624537/3d073678-c16c-498e-a6f1-1cb7f9ff3238)

So I think it would be best if the command just fails in this case altogether, what do you think?

**Comment by winkerVSbecks** [comment]
This was fixed in a recent release
