### ISSUE TITLE
CLI fails to find a branch with quotes in the name

### ISSUE THREAD

**Issue by dallonf** [chromaui/chromatic-cli#872]
**Bug report**

A teammate pushed up a PR with a branch called `checkout/"professional"-styles`, as a little joke referencing the previous styles which were, let's say _whimsical_.

However, the PR status check for Chromatic didn't update despite the CLI finishing successfully, and I found this in the logs:

> :warning: Branch ‘checkout/“professional”-styles’ does not exist
 We tried to retrieve its latest commit but couldn’t find it in your Git history.
 Falling back to de04c1c, but commit details (date, author) will be missing.
 We will not be able to retain baselines from builds created by the Visual Tests addon.
 Pull request status updates likely won’t work properly.

When the teammate published a new PR with a branch without the quotes, everything worked as expected.

**Comment by paulelliott** [comment]
Closed due to age. Please reopen if you feel this is still relevant for you.
