### ISSUE TITLE
Snapshot of react component which uses subgrid renders completely broken in snapshot

### ISSUE THREAD

**Issue by tklepzig** [chromaui/chromatic-cli#896]
We have a react component which uses `subgrid` internally. When viewing it in storybook everything looks fine, but in the chromatic snapshot the design is completely broken. It seems chromatic doesn't understand `subgrid`. As this has been supported in nearly all major browsers since September/October 2023 I'd expect this to work in chromatic snapshots as well.

**Comment by cgbl-90** [comment]
hello @tklepzig `subgrid` isn't supported yet. The versions our Capture stack supports are listed here:
https://www.chromatic.com/docs/infrastructure-release-notes/#version-5

`subgrid` browser compatibility: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout/Subgrid#browser_compatibility

**Comment by tklepzig** [comment]
> hello @tklepzig `subgrid` isn't supported yet. The browser versions our Capture stack supports are listed here: [chromatic.com/docs/infrastructure-release-notes/#version-5](https://www.chromatic.com/docs/infrastructure-release-notes/#version-5)
> 
> `subgrid` browser compatibility: [developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout/Subgrid#browser_compatibility](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout/Subgrid#browser_compatibility)

Ok, when do you plan to update these?

**Comment by cgbl-90** [comment]
@tklepzig Our Capture team is working on the next iteration of our Capture infrastructure to support this and other features/browser versions. We will announce it on our social media, chat, and other channels when Capture 6 is released.
