### ISSUE TITLE
Chromatic 'delay' parameter issues in MDX

### ISSUE THREAD

**Issue by fredvisser** [chromaui/chromatic-cli#90]
I have a modal component (defined in Storybook MDX) that that animates in, so by default, the Chromatic snapshot renders it as:

<img width="305" alt="Screen Shot 2020-01-28 at 11 57 20 PM" src="https://user-images.githubusercontent.com/1458528/73331624-ff261680-4229-11ea-9994-09b1fee6fb47.png">

I am trying to add a delay so that the Chromatic snapshot renders it as:
<img width="278" alt="Screen Shot 2020-01-28 at 11 57 30 PM" src="https://user-images.githubusercontent.com/1458528/73331630-03eaca80-422a-11ea-9976-2df9a2687e87.png">

Looking at the [delay documentation](https://docs.chromaticqa.com/delay) and the [MDX documentation](https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/mdx.md#decorators-and-parameters), I expected the following to work:  

```javascript
<Preview>
    <Story name="Slide-in" height="400px" parameters={{ chromatic: { delay: 1000 }}}>
        {() => `<div style="width:800px; height:600px">
                    <mc-dialog header="Header Text" position="right">
                        <div slot="content">
                            <p>Some dialog content</p>
                        </div>
                    </mc-dialog>
                </div>`}
    </Story>
</Preview>
``` 

…but the `parameters={{ chromatic: { delay: 1000 }}}` property doesn't have any affect – Either at the Story or Component levels.

Other Chromatic properties *do* work correctly. I.e. `parameters={{ chromatic: { disable: true }}}`

Do you have any insight into why this might be the case, or how to resolve this?
Thanks!

**Comment by tmeasday** [comment]
Hi @fredvisser -- I'm guessing you are running into this: http://docs.chromaticqa.com/animations ?

**Comment by fredvisser** [comment]
Unfortunately, neither `parameters={{ chromatic: { pauseAnimationAtEnd: true }}}` or `parameters={{ chromatic: { pauseAnimationAtEnd: true, delay: 1000 }}}` have the expected effect, and the snapshot continues to be taken at ~50ms into the animation.

Even adding `addParameters({ chromatic: { pauseAnimationAtEnd: true } });` to the `config.js` file doesn't appear to change the snapshot results.

The animation we're using is super simple:

```css
@keyframes mc-dialog-modal-fade-in {
    from {
        opacity: 0
    }
    to {
        opacity: 1
    }
}

.mc-dialog-modal-right {
    animation: mc-dialog-modal-fade-in .5s;
}
```

How does `pauseAnimationAtEnd` work?

**Comment by tmeasday** [comment]
@fredvisser that's pretty surprising, that's exactly the kind of animation this feature is designed for.

Can we continue this discussion in Chromatic's support (The intercom button, bottom right)? I'd like to take a closer look at the stories in quesion
