### ISSUE TITLE
Provide type export for @chromatic-com/playwright

### ISSUE THREAD

**Issue by albusphan** [chromaui/chromatic-cli#945]
**Bug report**
ENV:
Chromatic version: 11.0.7
@chromatic-com/playwright version:  0.6.1

In the old documentation about how to use Playwright with Chromatic, I'm still able to see the type definition of the package, after switching to the new package, the type is not exported anymore

https://github.com/chromaui/chromatic-e2e/issues/115

**Comment by winkerVSbecks** [comment]
resolved https://github.com/chromaui/chromatic-e2e/issues/115
