### ISSUE TITLE
TurrboSnap and preview.js dependencies issue

### ISSUE THREAD

**Issue by brian-patrick-3** [chromaui/chromatic-cli#970]
**<How is the user affected? And what is the expected behavior?>**

> We use [@storybook/web-components and a custom-elements.json](https://github.com/storybookjs/storybook/blob/next/code/addons/docs/web-components/README.md#installation) file to document all of our Args. The custom-elements.json file changes with pretty much every commit, and because this is a dependency in preview.js, it is always disabling TurboSnap. Is there a way to ignore these changes so TurboSnap remains enabled? I've tried `untraced: '**/custom-elements.js'` and `untraced: '**/preview.js'` and it did not work.
>
> Because of how the custom-elements.json is used in preview.js for @storybook/web-components, it is flagged as a full rebuild anytime that file changes, which is all the time. @storybook/web-components installation docs for reference: [https://github.com/storybookjs/storybook/blob/next/code/addons/docs/web-components/README.md#installation](https://app.intercom.com/a/inbox/\_/external-link?href=https%3A%2F%2Fgithub.com%2Fstorybookjs%2Fstorybook%2Fblob%2Fnext%2Fcode%2Faddons%2Fdocs%2Fweb-components%2FREADME.md%23installation)

Build logs show:

> Found a Storybook config change in .storybook/preview.js or one of its 4 module siblings:
>
> 2024-04-26T14:13:43.3792780Z               → .storybook/DocumentationTemplate.mdx
>
> 2024-04-26T14:13:43.3793601Z               → custom-elements.json
>
> 2024-04-26T14:13:43.3794545Z               → .storybook/global.scss
>
> 2024-04-26T14:13:43.3795303Z               → .storybook/usageBlock.jsx

But the file custom-elements.json was untraced.

**<How many and/or what class of users does this impact?>** 

1, [kyndryl.com](http://kyndryl.com)

potentially all [@storybook/web-components and a custom-elements.json](https://github.com/storybookjs/storybook/blob/next/code/addons/docs/web-components/README.md#installation) users

**<Is there a workaround?>** 

No.

**<What are the steps for reproducing the issue?>** 

N/A

**<Any other information to share?>**

Logs from customer's build below:

[4_Run.Chromatic.txt](https://uploads.linear.app/cfa7d1b1-ff77-4dbe-ae92-8cf23f92a7a9/2acc66eb-20f4-488d-b47f-8ca08497dee4/40bbd2fb-3bae-438e-bf9d-628f9a3d547c?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2NmYTdkMWIxLWZmNzctNGRiZS1hZTkyLThjZjIzZjkyYTdhOS8yYWNjNjZlYi0yMGY0LTQ4OGQtYjQ3Zi04Y2EwODQ5N2RlZTQvNDBiYmQyZmItM2JhZS00MzhlLWJmOWQtNjI4ZjlhM2Q1NDdjIiwiaWF0IjoxNzE0MTczMzgzLCJleHAiOjMzMjg0NzMzMzgzfQ.xQFlIy97wMCNjOffZXOkNbn4uVBELSggu5rbBNwGvH8)

**Comment by cgbl-90** [comment]
hey @brian-patrick-3, 
Can you add the `--debug` flag to your command to get more info about what Chromatic is doing, run a build, and send the output to in-app support? Thank you!

**Comment by brian-patrick-3** [comment]
I have another log where TurboSnap got disabled. Is it because of the dependency update?
[0_chromatic.txt](https://github.com/chromaui/chromatic-cli/files/15339324/0_chromatic.txt)

**Comment by cgbl-90** [comment]
Hey, @brian-patrick-3, dependency updates may trigger a full rebuild. Learn more [here](https://www.chromatic.com/docs/turbosnap/#full-rebuilds).
