### ISSUE TITLE
--exit-zero-on-changes true flag does not change anything

### ISSUE THREAD

**Issue by ivanignatiev** [chromaui/chromatic-cli#973]
**Bug report**

I am launching `npx chromatic` inside Azure Pipelines with following arguments:

```sh
npx chromatic --exit-zero-on-changes true --debug true --ci true --no-interactive --log-file false --junit-report /home/vsts/work/1/junit_report-100.xml
```

but I am getting always the same error, exit code 1:

```
✖ Found 3 visual changes: Review the changes
ℹ For CI/CD use cases, this command failed with exit code 1
Pass --exit-zero-on-changes to succeed this command regardless of changes.
Pass --auto-accept-changes to succeed and automatically accept any changes.
``` 

jUnit report is saved to the correct file, so I suppose arguments are good.

I have tried to add `chromatic.config.json` with following content:

```json
{
    "projectId": "Project:xxxx",
    "debug": true,
    "exitZeroOnChanges": true
}
```

but nothing changes, it is keeping to exit with 1.

Runtime: 
```
{
 "nodePlatform": "linux",
 "nodeVersion": "18.20.2",
  "packageManager": "npm",
  "packageManagerVersion": "10.5.0"
}
```

Anybody have the same issue?

**Comment by winkerVSbecks** [comment]
Is the command generating the log file and junit-report? If not, then something's preventing the flags from passing into the chromatic command.

What happens when you run the command locally? Does it exit with zero?
